// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

option go_package = "go.chromium.org/chromiumos/config/go/api/software";

package chromiumos.config.api.software;

message SchedulerConfig {
  // Scheduler's boost value(%) for urgent tasks. When an urgent thread is
  // created, chrome applies this value to scheduler attribute. Tasks with
  // higher boost value are more likely to have higher operating power point
  // even when the system is low utilized.
  // Minimum value: 0x0. Maximum value: 0x64.
  optional uint32 boost_urgent = 1;

  // Non-urgent task are only allowed to use given CPUs.
  optional string cpuset_nonurgent = 2;

  // Chromium kernel has a cpu-boost feature, which boosts CPUs for a short
  // duration when user interaction is detected from input devices. This value
  // specifies how much CPUs will be boosted.
  // Minimum value: 0x0. Maximum value: 0x64.
  optional uint32 input_boost = 3;
}
