syntax = "proto3";

package chromiumos.config.api.software;

option go_package = "go.chromium.org/chromiumos/config/go/api/software";

import "chromiumos/config/api/software/portage.proto";

// Defines config used to generate Chrome OS system image builds.
message SystemImage {
  // Defines build target config required to generate a Chrome OS system image.
  // See:
  // https://chromium.googlesource.com/chromiumos/docs/+/master/developer_guide.md#Build-a-disk-image-for-your-board
  message BuildTarget {
    Portage.BuildTarget portage_build_target = 1;
  }

  // Defines all of the metadata generated as a result of creating a system
  // build.  This metadata is made available for reporting/test-planning/...
  // as an artifact of the build.
  message BuildMetadata {
    // Target passed when the build was generated.
    BuildTarget build_target = 1;

    // All of the portage packages/versions included in the build.
    repeated Portage.Package packages = 2;

    // NOTE: This is a minimalist implementation for now, but more metadata
    // will be added as test planning is further refined.
  }

  // Used to serialize build metadata reports to proto[json|text|binary]
  message BuildMetadataList {
    repeated BuildMetadata values = 1;
  }
}
