# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/design_config_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/design_config_id.proto',
  package='chromiumos.config.api',
  syntax='proto3',
  serialized_options=_b('Z(go.chromium.org/chromiumos/config/go/api'),
  serialized_pb=_b('\n\x1a\x61pi/design_config_id.proto\x12\x15\x63hromiumos.config.api\"\x1f\n\x0e\x44\x65signConfigId\x12\r\n\x05value\x18\x01 \x01(\tB*Z(go.chromium.org/chromiumos/config/go/apib\x06proto3')
)




_DESIGNCONFIGID = _descriptor.Descriptor(
  name='DesignConfigId',
  full_name='chromiumos.config.api.DesignConfigId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='chromiumos.config.api.DesignConfigId.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['DesignConfigId'] = _DESIGNCONFIGID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DesignConfigId = _reflection.GeneratedProtocolMessageType('DesignConfigId', (_message.Message,), dict(
  DESCRIPTOR = _DESIGNCONFIGID,
  __module__ = 'api.design_config_id_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.api.DesignConfigId)
  ))
_sym_db.RegisterMessage(DesignConfigId)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
