// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/test/artifact/test_plan.proto

package artifact

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "go.chromium.org/chromiumos/config/go/test/api/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Captures artifact for test plans.
// NEXT TAG: 2
type TestPlanArtifact struct {
	// Captures hardware test plans
	HwTestPlans          []*v1.HWTestPlan `protobuf:"bytes,1,rep,name=hw_test_plans,json=hwTestPlans,proto3" json:"hw_test_plans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TestPlanArtifact) Reset()         { *m = TestPlanArtifact{} }
func (m *TestPlanArtifact) String() string { return proto.CompactTextString(m) }
func (*TestPlanArtifact) ProtoMessage()    {}
func (*TestPlanArtifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_71882251c83a8ca8, []int{0}
}

func (m *TestPlanArtifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestPlanArtifact.Unmarshal(m, b)
}
func (m *TestPlanArtifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestPlanArtifact.Marshal(b, m, deterministic)
}
func (m *TestPlanArtifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestPlanArtifact.Merge(m, src)
}
func (m *TestPlanArtifact) XXX_Size() int {
	return xxx_messageInfo_TestPlanArtifact.Size(m)
}
func (m *TestPlanArtifact) XXX_DiscardUnknown() {
	xxx_messageInfo_TestPlanArtifact.DiscardUnknown(m)
}

var xxx_messageInfo_TestPlanArtifact proto.InternalMessageInfo

func (m *TestPlanArtifact) GetHwTestPlans() []*v1.HWTestPlan {
	if m != nil {
		return m.HwTestPlans
	}
	return nil
}

func init() {
	proto.RegisterType((*TestPlanArtifact)(nil), "chromiumos.test.artifact.TestPlanArtifact")
}

func init() {
	proto.RegisterFile("chromiumos/test/artifact/test_plan.proto", fileDescriptor_71882251c83a8ca8)
}

var fileDescriptor_71882251c83a8ca8 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x48, 0xce, 0x28, 0xca,
	0xcf, 0xcd, 0x2c, 0xcd, 0xcd, 0x2f, 0xd6, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x4f, 0x2c, 0x2a, 0xc9,
	0x4c, 0x4b, 0x4c, 0x2e, 0x01, 0xf3, 0xe2, 0x0b, 0x72, 0x12, 0xf3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x24, 0x10, 0x2a, 0xf5, 0x40, 0x72, 0x7a, 0x30, 0x95, 0x52, 0x8a, 0x18, 0x66, 0x14,
	0x64, 0xea, 0x97, 0x19, 0xea, 0x23, 0x34, 0x2b, 0x45, 0x71, 0x09, 0x84, 0xa4, 0x16, 0x97, 0x04,
	0xe4, 0x24, 0xe6, 0x39, 0x42, 0xb5, 0x09, 0xb9, 0x71, 0xf1, 0x66, 0x94, 0xc7, 0xc3, 0xad, 0x29,
	0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x52, 0xd2, 0xc3, 0xb0, 0xa8, 0x20, 0x53, 0xaf, 0xcc,
	0x50, 0xcf, 0x23, 0x1c, 0x66, 0x44, 0x10, 0x77, 0x46, 0x39, 0x8c, 0x5d, 0xec, 0x64, 0x12, 0x65,
	0x94, 0x9e, 0x0f, 0xd7, 0xa4, 0x97, 0x5f, 0x94, 0xae, 0x8f, 0xe4, 0xa0, 0xe4, 0xfc, 0xbc, 0xb4,
	0xcc, 0x74, 0xfd, 0xf4, 0x7c, 0x54, 0xef, 0x25, 0xb1, 0x81, 0x1d, 0x66, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x38, 0x24, 0x4b, 0x70, 0x01, 0x01, 0x00, 0x00,
}
