// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api.metadata;

option go_package = "go.chromium.org/chromiumos/config/go/test/api/metadata";

import "chromiumos/test/artifact/test_result.proto";

// NEXT TAG: 7
message PublishRdbMetadata {
  // Current invocation id
  string current_invocation_id = 1;

  // Test results
  chromiumos.test.artifact.TestResult test_result = 2;

  // Stainless url where artifacts have been uploaded
  string stainless_url = 3 [deprecated = true];

  // Testhaus url where artifacts have been uploaded
  string testhaus_url = 4;

  // Sources captures information about the code sources tested by
  // the invocation.
  message Sources {
    // The path to the file in Google Cloud Storage that describes the
    // sources used in the Chrome OS build.
    // The sources themselves should be a JSON-serialized
    // luci.resultdb.v1.Sources proto.
    //
    // Format: "gs://<bucket>/<build>/metadata/sources.jsonpb".
    string gs_path = 1;

    // Indicates whether the deployment contains items other than
    // a Chrome OS system image built from the above sources.
    // For example, a different version of Lacros (for Lacros CI),
    // or a different version of firmware.
    //
    // When set, it indicates the sources above are incomplete and certain
    // analyses (e.g. regression or changepoint analysis) cannot be
    // reliably performed based on the Chrome OS source version alone.
    bool is_deployment_dirty = 2;
  }

  // The code sources tested.
  Sources sources = 5;

  // BaseVariant will be added to the variant of each test result within an
  // invocation. If there are duplicate keys, the variant value given by the
  // test command always wins.
  map<string, string> base_variant = 6;
}
