// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/config/api/device_brand.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Defines device branding characteristics for each unique Chromium OS device
// brand.
type DeviceBrand struct {
	// Globally unique device brand identifier.
	Id *DeviceBrandId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Hardware design used for the given brand.
	DesignId *DesignId `protobuf:"bytes,2,opt,name=design_id,json=designId,proto3" json:"design_id,omitempty"`
	// OEM for the given device brand.
	OemId *PartnerId `protobuf:"bytes,3,opt,name=oem_id,json=oemId,proto3" json:"oem_id,omitempty"`
	// Brand code assigned and set during manufacturing.
	BrandCode string `protobuf:"bytes,4,opt,name=brand_code,json=brandCode,proto3" json:"brand_code,omitempty"`
	// Brand marketing name.
	BrandName            string   `protobuf:"bytes,5,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceBrand) Reset()         { *m = DeviceBrand{} }
func (m *DeviceBrand) String() string { return proto.CompactTextString(m) }
func (*DeviceBrand) ProtoMessage()    {}
func (*DeviceBrand) Descriptor() ([]byte, []int) {
	return fileDescriptor_03ba172a0266babf, []int{0}
}

func (m *DeviceBrand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceBrand.Unmarshal(m, b)
}
func (m *DeviceBrand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceBrand.Marshal(b, m, deterministic)
}
func (m *DeviceBrand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceBrand.Merge(m, src)
}
func (m *DeviceBrand) XXX_Size() int {
	return xxx_messageInfo_DeviceBrand.Size(m)
}
func (m *DeviceBrand) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceBrand.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceBrand proto.InternalMessageInfo

func (m *DeviceBrand) GetId() *DeviceBrandId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DeviceBrand) GetDesignId() *DesignId {
	if m != nil {
		return m.DesignId
	}
	return nil
}

func (m *DeviceBrand) GetOemId() *PartnerId {
	if m != nil {
		return m.OemId
	}
	return nil
}

func (m *DeviceBrand) GetBrandCode() string {
	if m != nil {
		return m.BrandCode
	}
	return ""
}

func (m *DeviceBrand) GetBrandName() string {
	if m != nil {
		return m.BrandName
	}
	return ""
}

type DeviceBrandList struct {
	Value                []*DeviceBrand `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeviceBrandList) Reset()         { *m = DeviceBrandList{} }
func (m *DeviceBrandList) String() string { return proto.CompactTextString(m) }
func (*DeviceBrandList) ProtoMessage()    {}
func (*DeviceBrandList) Descriptor() ([]byte, []int) {
	return fileDescriptor_03ba172a0266babf, []int{1}
}

func (m *DeviceBrandList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceBrandList.Unmarshal(m, b)
}
func (m *DeviceBrandList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceBrandList.Marshal(b, m, deterministic)
}
func (m *DeviceBrandList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceBrandList.Merge(m, src)
}
func (m *DeviceBrandList) XXX_Size() int {
	return xxx_messageInfo_DeviceBrandList.Size(m)
}
func (m *DeviceBrandList) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceBrandList.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceBrandList proto.InternalMessageInfo

func (m *DeviceBrandList) GetValue() []*DeviceBrand {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceBrand)(nil), "chromiumos.config.api.DeviceBrand")
	proto.RegisterType((*DeviceBrandList)(nil), "chromiumos.config.api.DeviceBrandList")
}

func init() { proto.RegisterFile("src/config/api/device_brand.proto", fileDescriptor_03ba172a0266babf) }

var fileDescriptor_03ba172a0266babf = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0x67, 0x87, 0x4d, 0x0f, 0x42, 0x40, 0x28, 0x03, 0x5d, 0x2d, 0x3b, 0xf4, 0x94,
	0xc2, 0xa6, 0xe8, 0xc1, 0xd3, 0xf4, 0x52, 0x14, 0x91, 0x1e, 0xbd, 0x8c, 0xac, 0x2f, 0xd6, 0x80,
	0xe9, 0x2b, 0x69, 0xb7, 0xbf, 0xdd, 0xa3, 0x34, 0x9d, 0x6d, 0xfd, 0x31, 0x77, 0x0b, 0x79, 0x9f,
	0x4f, 0xf8, 0xbe, 0x7c, 0xc9, 0x45, 0xa5, 0xb3, 0x38, 0xc3, 0xe2, 0x55, 0xe6, 0x31, 0x2f, 0x65,
	0x0c, 0x62, 0x2b, 0x33, 0xb1, 0x5a, 0x6b, 0x5e, 0x00, 0x2b, 0x35, 0xd6, 0x48, 0x4f, 0xb3, 0x37,
	0x8d, 0x4a, 0x6e, 0x14, 0x56, 0xac, 0x25, 0x19, 0x2f, 0xe5, 0xe4, 0xfc, 0x97, 0x59, 0xc9, 0xbc,
	0x58, 0xc9, 0x9d, 0x36, 0x99, 0xfd, 0xf3, 0x72, 0x4f, 0x4d, 0x7f, 0x50, 0x25, 0xd7, 0x75, 0x21,
	0x74, 0x07, 0x84, 0x1f, 0x16, 0xf1, 0xee, 0x8d, 0xba, 0x6c, 0x4c, 0x7a, 0x49, 0x6c, 0x09, 0xbe,
	0x15, 0x58, 0x91, 0x37, 0x9f, 0xb1, 0x3f, 0xa3, 0xb1, 0x01, 0x9f, 0x40, 0x6a, 0x4b, 0xa0, 0xb7,
	0xc4, 0xed, 0xf2, 0xf9, 0xb6, 0x91, 0xa7, 0x7b, 0xe5, 0x86, 0x4b, 0x20, 0x3d, 0x86, 0xdd, 0x89,
	0x5e, 0x93, 0x31, 0x0a, 0xd5, 0xa8, 0x23, 0xa3, 0x06, 0x7b, 0xd4, 0xe7, 0x36, 0x7c, 0x02, 0xa9,
	0x83, 0x42, 0x25, 0x40, 0xcf, 0x08, 0x69, 0xf7, 0xcd, 0x10, 0x84, 0x7f, 0x14, 0x58, 0x91, 0x9b,
	0xba, 0xe6, 0xe6, 0x0e, 0x41, 0xf4, 0xe3, 0x82, 0x2b, 0xe1, 0x3b, 0x83, 0xf1, 0x13, 0x57, 0x22,
	0x7c, 0x20, 0x27, 0x83, 0x4d, 0x1e, 0x65, 0x55, 0xd3, 0x1b, 0xe2, 0x6c, 0xf9, 0xfb, 0x46, 0xf8,
	0x56, 0x30, 0x8a, 0xbc, 0x79, 0x78, 0xf8, 0x03, 0xd2, 0x56, 0x58, 0x5e, 0xbd, 0x2c, 0x72, 0xec,
	0x70, 0x86, 0x3a, 0x8f, 0x7b, 0xf7, 0xab, 0x81, 0x1c, 0xe3, 0xef, 0x7d, 0xac, 0xc7, 0xa6, 0x85,
	0xc5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0x0d, 0x7b, 0x3c, 0x28, 0x02, 0x00, 0x00,
}
