// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.plan;

option go_package = "go.chromium.org/chromiumos/config/go/test/plan";

import "chromiumos/test/api/coverage_rule.proto";

message TestPlan {
    message TestPlanId {
        string value = 1;
    }

    TestPlanId id = 1;
    repeated chromiumos.test.api.CoverageRule coverage_rules = 2;
}