// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.plan;

option go_package = "go.chromium.org/chromiumos/config/go/test/plan";

// Describes the test cases that run when a given set of files are changed.
//
// This message is intended to be specified as text proto in a DIR_METADATA file
// in the source tree, and should be concise enough Starlark, or another config
// generation tool, is not needed.
//
// NEXT ID: 15
message SourceTestPlan {
  reserved 1;

  // Paths that will trigger the SourceTestPlan.
  //
  // Must be a repo-absolute ChromeOS path. For example,
  // “arc/adbd/.*” for
  // https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/arc/adbd.
  //
  // Paths can only match files in the subtree of the DIR_METADATA file.
  // For example, paths specified in "a/b/DIR_METADATA" must start with "a/b/".
  //
  // Patterns use Google Re2 syntax. The comparison is a full match. The pattern
  // is implicitly anchored with ^ and $, so there is no need to add them.
  //
  // If path_regexp is not specified, it is implied to be all files in
  // the directory of the DIR_METADATA file and all files in subdirectories.
  //
  // If a file is matched by both path_regexp and path_regexp_exclude, it is
  // excluded.
  repeated string path_regexps = 2;
  repeated string path_regexp_excludes = 3;

  // A Starlark file that will be evaluated to generate HW/VMTestPlan protos.
  //
  // The Starlark file must output a list of HW/VMTestPlan protos based on an
  // input BuildMetadataList and FlatConfigList.
  message TestPlanStarlarkFile {
    // Gitiles hostname, e.g. "chromium.googlesource.com".
    string host = 1;

    // Repository name on the host, e.g. "chromium/src".
    string project = 2;

    // Absolute path within the repo to the Starlark file. Regexes are not
    // allowed.
    string path = 3;
  }

  // Starlark files to evaluate to generate HW/VMTestPlan protos.
  repeated TestPlanStarlarkFile test_plan_starlark_files = 15;

  reserved 4 to 14;
}
