// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: chromiumos/test/api/android_provision_state.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AndroidProvisionState defines all of the installable (provisionable) elements on an
// Android test device as part of device setup for test operations.
// Next Tag: 3
type AndroidProvisionState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *AndroidProvisionState_Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Required. CIPD packages to provision.
	CipdPackages []*CIPDPackage `protobuf:"bytes,2,rep,name=cipd_packages,json=cipdPackages,proto3" json:"cipd_packages,omitempty"`
}

func (x *AndroidProvisionState) Reset() {
	*x = AndroidProvisionState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_android_provision_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AndroidProvisionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndroidProvisionState) ProtoMessage() {}

func (x *AndroidProvisionState) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_android_provision_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndroidProvisionState.ProtoReflect.Descriptor instead.
func (*AndroidProvisionState) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_android_provision_state_proto_rawDescGZIP(), []int{0}
}

func (x *AndroidProvisionState) GetId() *AndroidProvisionState_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AndroidProvisionState) GetCipdPackages() []*CIPDPackage {
	if x != nil {
		return x.CipdPackages
	}
	return nil
}

// Required. String encoded id that uniquely reflects a given AndroidProvisionState.
type AndroidProvisionState_Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AndroidProvisionState_Id) Reset() {
	*x = AndroidProvisionState_Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chromiumos_test_api_android_provision_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AndroidProvisionState_Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndroidProvisionState_Id) ProtoMessage() {}

func (x *AndroidProvisionState_Id) ProtoReflect() protoreflect.Message {
	mi := &file_chromiumos_test_api_android_provision_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndroidProvisionState_Id.ProtoReflect.Descriptor instead.
func (*AndroidProvisionState_Id) Descriptor() ([]byte, []int) {
	return file_chromiumos_test_api_android_provision_state_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AndroidProvisionState_Id) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_chromiumos_test_api_android_provision_state_proto protoreflect.FileDescriptor

var file_chromiumos_test_api_android_provision_state_proto_rawDesc = []byte{
	0x0a, 0x31, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x34, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69,
	0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x64, 0x72, 0x6f, 0x69, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb9,
	0x01, 0x0a, 0x15, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3d, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f,
	0x73, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x6e, 0x64, 0x72, 0x6f,
	0x69, 0x64, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x45, 0x0a, 0x0d, 0x63, 0x69, 0x70, 0x64, 0x5f,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x49, 0x50, 0x44, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x52, 0x0c, 0x63, 0x69, 0x70, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x1a,
	0x0a, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x6f,
	0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68,
	0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f,
	0x67, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_chromiumos_test_api_android_provision_state_proto_rawDescOnce sync.Once
	file_chromiumos_test_api_android_provision_state_proto_rawDescData = file_chromiumos_test_api_android_provision_state_proto_rawDesc
)

func file_chromiumos_test_api_android_provision_state_proto_rawDescGZIP() []byte {
	file_chromiumos_test_api_android_provision_state_proto_rawDescOnce.Do(func() {
		file_chromiumos_test_api_android_provision_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_chromiumos_test_api_android_provision_state_proto_rawDescData)
	})
	return file_chromiumos_test_api_android_provision_state_proto_rawDescData
}

var file_chromiumos_test_api_android_provision_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chromiumos_test_api_android_provision_state_proto_goTypes = []interface{}{
	(*AndroidProvisionState)(nil),    // 0: chromiumos.test.api.AndroidProvisionState
	(*AndroidProvisionState_Id)(nil), // 1: chromiumos.test.api.AndroidProvisionState.Id
	(*CIPDPackage)(nil),              // 2: chromiumos.test.api.CIPDPackage
}
var file_chromiumos_test_api_android_provision_state_proto_depIdxs = []int32{
	1, // 0: chromiumos.test.api.AndroidProvisionState.id:type_name -> chromiumos.test.api.AndroidProvisionState.Id
	2, // 1: chromiumos.test.api.AndroidProvisionState.cipd_packages:type_name -> chromiumos.test.api.CIPDPackage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chromiumos_test_api_android_provision_state_proto_init() }
func file_chromiumos_test_api_android_provision_state_proto_init() {
	if File_chromiumos_test_api_android_provision_state_proto != nil {
		return
	}
	file_chromiumos_test_api_android_provision_metadata_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chromiumos_test_api_android_provision_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AndroidProvisionState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chromiumos_test_api_android_provision_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AndroidProvisionState_Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chromiumos_test_api_android_provision_state_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chromiumos_test_api_android_provision_state_proto_goTypes,
		DependencyIndexes: file_chromiumos_test_api_android_provision_state_proto_depIdxs,
		MessageInfos:      file_chromiumos_test_api_android_provision_state_proto_msgTypes,
	}.Build()
	File_chromiumos_test_api_android_provision_state_proto = out.File
	file_chromiumos_test_api_android_provision_state_proto_rawDesc = nil
	file_chromiumos_test_api_android_provision_state_proto_goTypes = nil
	file_chromiumos_test_api_android_provision_state_proto_depIdxs = nil
}
