// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/test/api/chameleon_lib_service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckChameleonHealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckChameleonHealthRequest) Reset()         { *m = CheckChameleonHealthRequest{} }
func (m *CheckChameleonHealthRequest) String() string { return proto.CompactTextString(m) }
func (*CheckChameleonHealthRequest) ProtoMessage()    {}
func (*CheckChameleonHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d656d6dac088827, []int{0}
}

func (m *CheckChameleonHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckChameleonHealthRequest.Unmarshal(m, b)
}
func (m *CheckChameleonHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckChameleonHealthRequest.Marshal(b, m, deterministic)
}
func (m *CheckChameleonHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckChameleonHealthRequest.Merge(m, src)
}
func (m *CheckChameleonHealthRequest) XXX_Size() int {
	return xxx_messageInfo_CheckChameleonHealthRequest.Size(m)
}
func (m *CheckChameleonHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckChameleonHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckChameleonHealthRequest proto.InternalMessageInfo

type CheckChameleonHealthResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckChameleonHealthResponse) Reset()         { *m = CheckChameleonHealthResponse{} }
func (m *CheckChameleonHealthResponse) String() string { return proto.CompactTextString(m) }
func (*CheckChameleonHealthResponse) ProtoMessage()    {}
func (*CheckChameleonHealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d656d6dac088827, []int{1}
}

func (m *CheckChameleonHealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckChameleonHealthResponse.Unmarshal(m, b)
}
func (m *CheckChameleonHealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckChameleonHealthResponse.Marshal(b, m, deterministic)
}
func (m *CheckChameleonHealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckChameleonHealthResponse.Merge(m, src)
}
func (m *CheckChameleonHealthResponse) XXX_Size() int {
	return xxx_messageInfo_CheckChameleonHealthResponse.Size(m)
}
func (m *CheckChameleonHealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckChameleonHealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckChameleonHealthResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CheckChameleonHealthRequest)(nil), "chromiumos.test.api.CheckChameleonHealthRequest")
	proto.RegisterType((*CheckChameleonHealthResponse)(nil), "chromiumos.test.api.CheckChameleonHealthResponse")
}

func init() {
	proto.RegisterFile("chromiumos/test/api/chameleon_lib_service.proto", fileDescriptor_1d656d6dac088827)
}

var fileDescriptor_1d656d6dac088827 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4f, 0xce, 0x28, 0xca,
	0xcf, 0xcd, 0x2c, 0xcd, 0xcd, 0x2f, 0xd6, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x4f, 0x2c, 0xc8, 0xd4,
	0x4f, 0xce, 0x48, 0xcc, 0x4d, 0xcd, 0x49, 0xcd, 0xcf, 0x8b, 0xcf, 0xc9, 0x4c, 0x8a, 0x2f, 0x4e,
	0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x46, 0x68, 0xd0,
	0x03, 0x69, 0xd0, 0x4b, 0x2c, 0xc8, 0x54, 0x92, 0xe5, 0x92, 0x76, 0xce, 0x48, 0x4d, 0xce, 0x76,
	0x86, 0x69, 0xf4, 0x48, 0x4d, 0xcc, 0x29, 0xc9, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51,
	0x92, 0xe3, 0x92, 0xc1, 0x2e, 0x5d, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x6a, 0x34, 0x85, 0x91, 0x4b,
	0x18, 0x2e, 0xe7, 0x93, 0x99, 0x14, 0x0c, 0xb1, 0x51, 0xa8, 0x96, 0x4b, 0x04, 0x9b, 0x3e, 0x21,
	0x03, 0x3d, 0x2c, 0x8e, 0xd0, 0xc3, 0xe3, 0x02, 0x29, 0x43, 0x12, 0x74, 0x40, 0x1c, 0x65, 0xc0,
	0xe8, 0xa4, 0x1f, 0xa5, 0x9b, 0x9e, 0x0f, 0xd7, 0xa8, 0x97, 0x5f, 0x94, 0x8e, 0x1c, 0x5a, 0xc9,
	0xf9, 0x79, 0x69, 0x99, 0xe9, 0xfa, 0xe9, 0xf9, 0xf0, 0x70, 0x4b, 0x62, 0x03, 0x07, 0x91, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x39, 0xf2, 0x96, 0x47, 0x55, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChameleonLibServiceClient is the client API for ChameleonLibService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChameleonLibServiceClient interface {
	// Verifies the connection/status of the chameleon device
	CheckChameleonHealth(ctx context.Context, in *CheckChameleonHealthRequest, opts ...grpc.CallOption) (ChameleonLibService_CheckChameleonHealthClient, error)
}

type chameleonLibServiceClient struct {
	cc *grpc.ClientConn
}

func NewChameleonLibServiceClient(cc *grpc.ClientConn) ChameleonLibServiceClient {
	return &chameleonLibServiceClient{cc}
}

func (c *chameleonLibServiceClient) CheckChameleonHealth(ctx context.Context, in *CheckChameleonHealthRequest, opts ...grpc.CallOption) (ChameleonLibService_CheckChameleonHealthClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChameleonLibService_serviceDesc.Streams[0], "/chromiumos.test.api.ChameleonLibService/CheckChameleonHealth", opts...)
	if err != nil {
		return nil, err
	}
	x := &chameleonLibServiceCheckChameleonHealthClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChameleonLibService_CheckChameleonHealthClient interface {
	Recv() (*CheckChameleonHealthResponse, error)
	grpc.ClientStream
}

type chameleonLibServiceCheckChameleonHealthClient struct {
	grpc.ClientStream
}

func (x *chameleonLibServiceCheckChameleonHealthClient) Recv() (*CheckChameleonHealthResponse, error) {
	m := new(CheckChameleonHealthResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChameleonLibServiceServer is the server API for ChameleonLibService service.
type ChameleonLibServiceServer interface {
	// Verifies the connection/status of the chameleon device
	CheckChameleonHealth(*CheckChameleonHealthRequest, ChameleonLibService_CheckChameleonHealthServer) error
}

// UnimplementedChameleonLibServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChameleonLibServiceServer struct {
}

func (*UnimplementedChameleonLibServiceServer) CheckChameleonHealth(req *CheckChameleonHealthRequest, srv ChameleonLibService_CheckChameleonHealthServer) error {
	return status.Errorf(codes.Unimplemented, "method CheckChameleonHealth not implemented")
}

func RegisterChameleonLibServiceServer(s *grpc.Server, srv ChameleonLibServiceServer) {
	s.RegisterService(&_ChameleonLibService_serviceDesc, srv)
}

func _ChameleonLibService_CheckChameleonHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CheckChameleonHealthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChameleonLibServiceServer).CheckChameleonHealth(m, &chameleonLibServiceCheckChameleonHealthServer{stream})
}

type ChameleonLibService_CheckChameleonHealthServer interface {
	Send(*CheckChameleonHealthResponse) error
	grpc.ServerStream
}

type chameleonLibServiceCheckChameleonHealthServer struct {
	grpc.ServerStream
}

func (x *chameleonLibServiceCheckChameleonHealthServer) Send(m *CheckChameleonHealthResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ChameleonLibService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chromiumos.test.api.ChameleonLibService",
	HandlerType: (*ChameleonLibServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckChameleonHealth",
			Handler:       _ChameleonLibService_CheckChameleonHealth_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chromiumos/test/api/chameleon_lib_service.proto",
}
