// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/test/api/cros_publish_cli.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CrosPublishRequest specifies a local directory that will be uploaded to a GS
// path.
// NEXT TAG: 3
type CrosPublishRequest struct {
	// GS path to upload to, e.g. gs://foo/bar/baz/
	GsDirectory string `protobuf:"bytes,1,opt,name=gs_directory,json=gsDirectory,proto3" json:"gs_directory,omitempty"`
	// Absolute path to local directory to upload to GS, e.g. /usr/local/foo/bar
	LocalDirectory       string   `protobuf:"bytes,2,opt,name=local_directory,json=localDirectory,proto3" json:"local_directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrosPublishRequest) Reset()         { *m = CrosPublishRequest{} }
func (m *CrosPublishRequest) String() string { return proto.CompactTextString(m) }
func (*CrosPublishRequest) ProtoMessage()    {}
func (*CrosPublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c7614b5efbf1c9e, []int{0}
}

func (m *CrosPublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrosPublishRequest.Unmarshal(m, b)
}
func (m *CrosPublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrosPublishRequest.Marshal(b, m, deterministic)
}
func (m *CrosPublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrosPublishRequest.Merge(m, src)
}
func (m *CrosPublishRequest) XXX_Size() int {
	return xxx_messageInfo_CrosPublishRequest.Size(m)
}
func (m *CrosPublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrosPublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrosPublishRequest proto.InternalMessageInfo

func (m *CrosPublishRequest) GetGsDirectory() string {
	if m != nil {
		return m.GsDirectory
	}
	return ""
}

func (m *CrosPublishRequest) GetLocalDirectory() string {
	if m != nil {
		return m.LocalDirectory
	}
	return ""
}

// CrosPublishResponse includes the GS url for the uploaded data. If failed,
// populates the error message.
// NEXT TAG: 4
type CrosPublishResponse struct {
	// URL of Google Storage location containing offloaded files
	GsUrl string `protobuf:"bytes,1,opt,name=gs_url,json=gsUrl,proto3" json:"gs_url,omitempty"`
	// If the publish process finished successfully or not.
	Error bool `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	// Error message when the publish process failed.
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrosPublishResponse) Reset()         { *m = CrosPublishResponse{} }
func (m *CrosPublishResponse) String() string { return proto.CompactTextString(m) }
func (*CrosPublishResponse) ProtoMessage()    {}
func (*CrosPublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c7614b5efbf1c9e, []int{1}
}

func (m *CrosPublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrosPublishResponse.Unmarshal(m, b)
}
func (m *CrosPublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrosPublishResponse.Marshal(b, m, deterministic)
}
func (m *CrosPublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrosPublishResponse.Merge(m, src)
}
func (m *CrosPublishResponse) XXX_Size() int {
	return xxx_messageInfo_CrosPublishResponse.Size(m)
}
func (m *CrosPublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrosPublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrosPublishResponse proto.InternalMessageInfo

func (m *CrosPublishResponse) GetGsUrl() string {
	if m != nil {
		return m.GsUrl
	}
	return ""
}

func (m *CrosPublishResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *CrosPublishResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*CrosPublishRequest)(nil), "chromiumos.test.api.CrosPublishRequest")
	proto.RegisterType((*CrosPublishResponse)(nil), "chromiumos.test.api.CrosPublishResponse")
}

func init() {
	proto.RegisterFile("chromiumos/test/api/cros_publish_cli.proto", fileDescriptor_7c7614b5efbf1c9e)
}

var fileDescriptor_7c7614b5efbf1c9e = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xa9, 0xd2, 0xa2, 0xb1, 0x2a, 0xa4, 0x0a, 0x3d, 0x6a, 0x3d, 0x28, 0x82, 0xc9, 0xc1,
	0x37, 0x50, 0xaf, 0x82, 0x2c, 0x78, 0xf1, 0x12, 0xb7, 0x71, 0x9c, 0x06, 0xb2, 0x9d, 0x38, 0x93,
	0x1c, 0x7c, 0x7b, 0x31, 0x6b, 0xeb, 0xf6, 0x96, 0x7c, 0x7c, 0xf3, 0x0f, 0xf3, 0xab, 0x5b, 0xbf,
	0x62, 0xea, 0x42, 0xe9, 0x48, 0x6c, 0x06, 0xc9, 0xb6, 0x4d, 0xc1, 0x7a, 0x26, 0x71, 0xa9, 0x2c,
	0x63, 0x90, 0x95, 0xf3, 0x31, 0x98, 0xc4, 0x94, 0x49, 0xcf, 0xfe, 0x5d, 0xf3, 0xeb, 0x9a, 0x36,
	0x85, 0xc5, 0xbb, 0xd2, 0x8f, 0x4c, 0xf2, 0xd2, 0xdb, 0x0d, 0x7c, 0x15, 0x90, 0xac, 0x2f, 0xd5,
	0x14, 0xc5, 0x7d, 0x04, 0x06, 0x9f, 0x89, 0xbf, 0xe7, 0xa3, 0x8b, 0xd1, 0xcd, 0x61, 0x73, 0x84,
	0xf2, 0xb4, 0x41, 0xfa, 0x5a, 0x9d, 0x46, 0xf2, 0x6d, 0x1c, 0x58, 0x7b, 0xd5, 0x3a, 0xa9, 0x78,
	0x2b, 0x2e, 0x50, 0xcd, 0x76, 0x36, 0x48, 0xa2, 0xb5, 0x80, 0x3e, 0x57, 0x13, 0x14, 0x57, 0x38,
	0xfe, 0x85, 0x8f, 0x51, 0x5e, 0x39, 0xea, 0x33, 0x35, 0x06, 0x66, 0xe2, 0x1a, 0x76, 0xd0, 0xf4,
	0x1f, 0x7d, 0xa5, 0x8e, 0xeb, 0xc3, 0x75, 0x20, 0xd2, 0x22, 0xcc, 0xf7, 0xeb, 0xcc, 0xb4, 0xc2,
	0xe7, 0x9e, 0x3d, 0xd8, 0xb7, 0x3b, 0x24, 0xb3, 0x39, 0xd2, 0x10, 0xa3, 0x1d, 0xb4, 0xe3, 0x69,
	0xfd, 0x19, 0xd0, 0x22, 0x6d, 0x7b, 0x5a, 0x4e, 0x6a, 0x2f, 0xf7, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x59, 0x0f, 0xfe, 0xd4, 0x45, 0x01, 0x00, 0x00,
}
