// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/test/api/cros_tool_runner_container_service_extensions.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Extensions to the LoginRegistry API. Extensions will be handled before login.
type LoginRegistryExtensions struct {
	// Provides a hook to execute `gcloud auth activate-service-account` before
	// login. The value are the arguments of the command documented in
	// http://cloud/sdk/gcloud/reference/auth/activate-service-account.
	// e.g. ["service_account@domain.com", "--key-file=/path/key.json"] or
	// ["--key-file", "/path/key.json"]
	GcloudAuthServiceAccountArgs []string `protobuf:"bytes,1,rep,name=gcloud_auth_service_account_args,json=gcloudAuthServiceAccountArgs,proto3" json:"gcloud_auth_service_account_args,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *LoginRegistryExtensions) Reset()         { *m = LoginRegistryExtensions{} }
func (m *LoginRegistryExtensions) String() string { return proto.CompactTextString(m) }
func (*LoginRegistryExtensions) ProtoMessage()    {}
func (*LoginRegistryExtensions) Descriptor() ([]byte, []int) {
	return fileDescriptor_58380f6bca81c1b8, []int{0}
}

func (m *LoginRegistryExtensions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRegistryExtensions.Unmarshal(m, b)
}
func (m *LoginRegistryExtensions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRegistryExtensions.Marshal(b, m, deterministic)
}
func (m *LoginRegistryExtensions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRegistryExtensions.Merge(m, src)
}
func (m *LoginRegistryExtensions) XXX_Size() int {
	return xxx_messageInfo_LoginRegistryExtensions.Size(m)
}
func (m *LoginRegistryExtensions) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRegistryExtensions.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRegistryExtensions proto.InternalMessageInfo

func (m *LoginRegistryExtensions) GetGcloudAuthServiceAccountArgs() []string {
	if m != nil {
		return m.GcloudAuthServiceAccountArgs
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRegistryExtensions)(nil), "chromiumos.test.api.LoginRegistryExtensions")
}

func init() {
	proto.RegisterFile("chromiumos/test/api/cros_tool_runner_container_service_extensions.proto", fileDescriptor_58380f6bca81c1b8)
}

var fileDescriptor_58380f6bca81c1b8 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x4b, 0xc5, 0x40,
	0x0c, 0x87, 0x11, 0x41, 0xb0, 0xe3, 0x73, 0xd0, 0xc1, 0xe1, 0xe1, 0xe4, 0xe2, 0xdd, 0xe0, 0x5f,
	0x50, 0x41, 0x5d, 0x9c, 0x9e, 0x9b, 0xcb, 0x71, 0x9e, 0x67, 0x1a, 0x68, 0xf3, 0x2b, 0x49, 0x4e,
	0xf4, 0xbf, 0x97, 0x5a, 0xac, 0x6e, 0x19, 0xbe, 0x7c, 0xc9, 0xd7, 0x3d, 0x96, 0x41, 0x31, 0x71,
	0x9b, 0x60, 0xd1, 0xab, 0x79, 0xcc, 0x33, 0xc7, 0xa2, 0xb0, 0xe4, 0xc0, 0x98, 0xb4, 0x89, 0x54,
	0x4d, 0x05, 0xe2, 0x99, 0x97, 0xc9, 0xaa, 0x7e, 0x70, 0xa9, 0xa9, 0x7e, 0x7a, 0x15, 0x63, 0x88,
	0x85, 0x59, 0xe1, 0xd8, 0x9d, 0xfd, 0x89, 0xc2, 0x22, 0x0a, 0x79, 0xe6, 0xab, 0xdc, 0x9d, 0x3f,
	0x81, 0x58, 0x0e, 0x95, 0xd8, 0x5c, 0xbf, 0xee, 0xb7, 0xad, 0xdd, 0x43, 0xb7, 0xa7, 0x32, 0xa2,
	0xbd, 0xa5, 0xdc, 0x7c, 0xd8, 0xbc, 0xb9, 0x14, 0x34, 0xf1, 0x94, 0x95, 0xec, 0xe2, 0x68, 0x7f,
	0x7c, 0x7d, 0x7a, 0xb8, 0x5c, 0xb9, 0xbe, 0xf9, 0xf0, 0xbc, 0x52, 0xfd, 0x0a, 0xf5, 0x4a, 0x76,
	0x17, 0x5f, 0x6e, 0x08, 0xe1, 0xf7, 0x78, 0x80, 0x52, 0xfc, 0x97, 0x54, 0x20, 0xef, 0x4c, 0x91,
	0xb0, 0xc5, 0xbd, 0x9e, 0xfc, 0xfc, 0x7b, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x28, 0x37, 0x49,
	0xe0, 0xfa, 0x00, 0x00, 0x00,
}
