// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/test/api/provision_state.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_go "go.chromium.org/chromiumos/config/go"
	api "go.chromium.org/chromiumos/config/go/build/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ProvisionState defines all of the installable (provisionable) elements on a
// ChromeOS test device as part of device setup for test operations.
//
// This record is used to define the following:
//   How devices should be provisioned based on the client's respective needs.
//     E.g.
//       CrOS CI - System image only
//       Lacros CI - System image + Lacros component
//   How device provisioning state is reported for corresponding test results.
//     Every test result will link to a provisioning record for
//     analysis/debugging.
type ProvisionState struct {
	// String encoded id that uniquely reflects a given ProvisionState.
	// This is used for both scheduling and reporting purposes.
	// For scheduling, is used to determine if a device is in the requested
	// provisioning state for testing or it needs to be reprovisioned.
	// For reporting, this can be used to compare the entire provision state
	// (in a summarized string) across different test results.
	Id          *ProvisionState_Id          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Firmware    *api.FirmwareConfig         `protobuf:"bytes,2,opt,name=firmware,proto3" json:"firmware,omitempty"`
	SystemImage *ProvisionState_SystemImage `protobuf:"bytes,3,opt,name=system_image,json=systemImage,proto3" json:"system_image,omitempty"`
	Packages    []*ProvisionState_Package   `protobuf:"bytes,4,rep,name=packages,proto3" json:"packages,omitempty"`
	// Prevents device reboot during system image provisioning.
	PreventReboot        bool     `protobuf:"varint,5,opt,name=prevent_reboot,json=preventReboot,proto3" json:"prevent_reboot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionState) Reset()         { *m = ProvisionState{} }
func (m *ProvisionState) String() string { return proto.CompactTextString(m) }
func (*ProvisionState) ProtoMessage()    {}
func (*ProvisionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5607429c827e42, []int{0}
}

func (m *ProvisionState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionState.Unmarshal(m, b)
}
func (m *ProvisionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionState.Marshal(b, m, deterministic)
}
func (m *ProvisionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionState.Merge(m, src)
}
func (m *ProvisionState) XXX_Size() int {
	return xxx_messageInfo_ProvisionState.Size(m)
}
func (m *ProvisionState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionState.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionState proto.InternalMessageInfo

func (m *ProvisionState) GetId() *ProvisionState_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ProvisionState) GetFirmware() *api.FirmwareConfig {
	if m != nil {
		return m.Firmware
	}
	return nil
}

func (m *ProvisionState) GetSystemImage() *ProvisionState_SystemImage {
	if m != nil {
		return m.SystemImage
	}
	return nil
}

func (m *ProvisionState) GetPackages() []*ProvisionState_Package {
	if m != nil {
		return m.Packages
	}
	return nil
}

func (m *ProvisionState) GetPreventReboot() bool {
	if m != nil {
		return m.PreventReboot
	}
	return false
}

type ProvisionState_Id struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionState_Id) Reset()         { *m = ProvisionState_Id{} }
func (m *ProvisionState_Id) String() string { return proto.CompactTextString(m) }
func (*ProvisionState_Id) ProtoMessage()    {}
func (*ProvisionState_Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5607429c827e42, []int{0, 0}
}

func (m *ProvisionState_Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionState_Id.Unmarshal(m, b)
}
func (m *ProvisionState_Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionState_Id.Marshal(b, m, deterministic)
}
func (m *ProvisionState_Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionState_Id.Merge(m, src)
}
func (m *ProvisionState_Id) XXX_Size() int {
	return xxx_messageInfo_ProvisionState_Id.Size(m)
}
func (m *ProvisionState_Id) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionState_Id.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionState_Id proto.InternalMessageInfo

func (m *ProvisionState_Id) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ProvisionState_SystemImage struct {
	// Unique version used in constructing the overall Id
	Version         string           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	SystemImagePath *_go.StoragePath `protobuf:"bytes,2,opt,name=system_image_path,json=systemImagePath,proto3" json:"system_image_path,omitempty"`
	// List of DLCs that were built/archived for a given system image and are
	// installed as part of provisioning.
	Dlcs []*api.Dlc_Id `protobuf:"bytes,3,rep,name=dlcs,proto3" json:"dlcs,omitempty"`
	// An optional tarball to be extracted at the root of the filesystem to
	// overwrite existing binary payloads.
	OverwritePayload     *_go.StoragePath `protobuf:"bytes,4,opt,name=overwrite_payload,json=overwritePayload,proto3" json:"overwrite_payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProvisionState_SystemImage) Reset()         { *m = ProvisionState_SystemImage{} }
func (m *ProvisionState_SystemImage) String() string { return proto.CompactTextString(m) }
func (*ProvisionState_SystemImage) ProtoMessage()    {}
func (*ProvisionState_SystemImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5607429c827e42, []int{0, 1}
}

func (m *ProvisionState_SystemImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionState_SystemImage.Unmarshal(m, b)
}
func (m *ProvisionState_SystemImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionState_SystemImage.Marshal(b, m, deterministic)
}
func (m *ProvisionState_SystemImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionState_SystemImage.Merge(m, src)
}
func (m *ProvisionState_SystemImage) XXX_Size() int {
	return xxx_messageInfo_ProvisionState_SystemImage.Size(m)
}
func (m *ProvisionState_SystemImage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionState_SystemImage.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionState_SystemImage proto.InternalMessageInfo

func (m *ProvisionState_SystemImage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ProvisionState_SystemImage) GetSystemImagePath() *_go.StoragePath {
	if m != nil {
		return m.SystemImagePath
	}
	return nil
}

func (m *ProvisionState_SystemImage) GetDlcs() []*api.Dlc_Id {
	if m != nil {
		return m.Dlcs
	}
	return nil
}

func (m *ProvisionState_SystemImage) GetOverwritePayload() *_go.StoragePath {
	if m != nil {
		return m.OverwritePayload
	}
	return nil
}

type ProvisionState_Package struct {
	// Package names must match actual portage package names that
	// exist in a given ChromeOS test image.
	// Package versions may be in any scheme that is relevant to the clients
	// versioning scheme (e.g. Lacros build versions).
	PortagePackage       *api.Portage_Package `protobuf:"bytes,1,opt,name=portage_package,json=portagePackage,proto3" json:"portage_package,omitempty"`
	PackagePath          *_go.StoragePath     `protobuf:"bytes,2,opt,name=package_path,json=packagePath,proto3" json:"package_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProvisionState_Package) Reset()         { *m = ProvisionState_Package{} }
func (m *ProvisionState_Package) String() string { return proto.CompactTextString(m) }
func (*ProvisionState_Package) ProtoMessage()    {}
func (*ProvisionState_Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5607429c827e42, []int{0, 2}
}

func (m *ProvisionState_Package) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionState_Package.Unmarshal(m, b)
}
func (m *ProvisionState_Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionState_Package.Marshal(b, m, deterministic)
}
func (m *ProvisionState_Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionState_Package.Merge(m, src)
}
func (m *ProvisionState_Package) XXX_Size() int {
	return xxx_messageInfo_ProvisionState_Package.Size(m)
}
func (m *ProvisionState_Package) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionState_Package.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionState_Package proto.InternalMessageInfo

func (m *ProvisionState_Package) GetPortagePackage() *api.Portage_Package {
	if m != nil {
		return m.PortagePackage
	}
	return nil
}

func (m *ProvisionState_Package) GetPackagePath() *_go.StoragePath {
	if m != nil {
		return m.PackagePath
	}
	return nil
}

// User configurable provisioning settings.  These inform the final
// ProvisionState that's requested from the provisioning service.
type ProvisionConfig struct {
	Firmware *api.FirmwareConfig       `protobuf:"bytes,1,opt,name=firmware,proto3" json:"firmware,omitempty"`
	Dlcs     []*api.Dlc_Id             `protobuf:"bytes,2,rep,name=dlcs,proto3" json:"dlcs,omitempty"`
	Packages []*ProvisionState_Package `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	// Variant on the primary build target to test with.
	//   Eg: If we were targeting a 'coral' board for testing, setting this
	//   to 'kernelnext' woul duse the coral-kernelnext image from the build for
	//   testing.
	BoardVariant string `protobuf:"bytes,4,opt,name=board_variant,json=boardVariant,proto3" json:"board_variant,omitempty"`
	// Optional tarball to pass through to provisioning.
	OverwritePayload     *_go.StoragePath `protobuf:"bytes,5,opt,name=overwrite_payload,json=overwritePayload,proto3" json:"overwrite_payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProvisionConfig) Reset()         { *m = ProvisionConfig{} }
func (m *ProvisionConfig) String() string { return proto.CompactTextString(m) }
func (*ProvisionConfig) ProtoMessage()    {}
func (*ProvisionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b5607429c827e42, []int{1}
}

func (m *ProvisionConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionConfig.Unmarshal(m, b)
}
func (m *ProvisionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionConfig.Marshal(b, m, deterministic)
}
func (m *ProvisionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionConfig.Merge(m, src)
}
func (m *ProvisionConfig) XXX_Size() int {
	return xxx_messageInfo_ProvisionConfig.Size(m)
}
func (m *ProvisionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionConfig proto.InternalMessageInfo

func (m *ProvisionConfig) GetFirmware() *api.FirmwareConfig {
	if m != nil {
		return m.Firmware
	}
	return nil
}

func (m *ProvisionConfig) GetDlcs() []*api.Dlc_Id {
	if m != nil {
		return m.Dlcs
	}
	return nil
}

func (m *ProvisionConfig) GetPackages() []*ProvisionState_Package {
	if m != nil {
		return m.Packages
	}
	return nil
}

func (m *ProvisionConfig) GetBoardVariant() string {
	if m != nil {
		return m.BoardVariant
	}
	return ""
}

func (m *ProvisionConfig) GetOverwritePayload() *_go.StoragePath {
	if m != nil {
		return m.OverwritePayload
	}
	return nil
}

func init() {
	proto.RegisterType((*ProvisionState)(nil), "chromiumos.test.api.ProvisionState")
	proto.RegisterType((*ProvisionState_Id)(nil), "chromiumos.test.api.ProvisionState.Id")
	proto.RegisterType((*ProvisionState_SystemImage)(nil), "chromiumos.test.api.ProvisionState.SystemImage")
	proto.RegisterType((*ProvisionState_Package)(nil), "chromiumos.test.api.ProvisionState.Package")
	proto.RegisterType((*ProvisionConfig)(nil), "chromiumos.test.api.ProvisionConfig")
}

func init() {
	proto.RegisterFile("chromiumos/test/api/provision_state.proto", fileDescriptor_1b5607429c827e42)
}

var fileDescriptor_1b5607429c827e42 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x25, 0xe9, 0xd6, 0xed, 0xde, 0x74, 0x5b, 0x77, 0x14, 0x0c, 0x41, 0xa5, 0x54, 0x57, 0xaa,
	0x62, 0x22, 0x2b, 0xf8, 0xe0, 0x93, 0xb8, 0x8b, 0xd2, 0x17, 0x09, 0x53, 0xf0, 0xc1, 0x97, 0x30,
	0x4d, 0x66, 0xd3, 0xc1, 0xa4, 0x13, 0x66, 0xa6, 0x59, 0xf6, 0x43, 0xfc, 0x18, 0xff, 0xc7, 0x17,
	0xff, 0x42, 0x32, 0x99, 0x64, 0xb3, 0x10, 0xa4, 0xea, 0xe3, 0xdc, 0x39, 0xe7, 0xce, 0x99, 0x73,
	0x0f, 0x17, 0x9e, 0xc7, 0x1b, 0xc1, 0x73, 0xb6, 0xcb, 0xb9, 0x0c, 0x14, 0x95, 0x2a, 0x20, 0x05,
	0x0b, 0x0a, 0xc1, 0x4b, 0x26, 0x19, 0xdf, 0x46, 0x52, 0x11, 0x45, 0xfd, 0x42, 0x70, 0xc5, 0xd1,
	0xbd, 0x1b, 0xa8, 0x5f, 0x41, 0x7d, 0x52, 0x30, 0xef, 0x71, 0x87, 0xbf, 0xde, 0xb1, 0x2c, 0xd1,
	0x0d, 0x92, 0x2c, 0xae, 0x49, 0xde, 0x8b, 0xde, 0xfb, 0x4b, 0x26, 0xf2, 0x2b, 0x22, 0x68, 0x14,
	0xf3, 0xed, 0x25, 0x4b, 0x0d, 0x76, 0xde, 0x8b, 0x2d, 0xb8, 0x50, 0x24, 0x35, 0x22, 0xbc, 0x47,
	0x1d, 0x8c, 0x54, 0x5c, 0x90, 0x94, 0x46, 0x05, 0x51, 0x9b, 0xfa, 0x7a, 0xfe, 0x6b, 0x08, 0x93,
	0xb0, 0x51, 0xbf, 0xaa, 0xc4, 0xa3, 0xb7, 0x60, 0xb3, 0xc4, 0xb5, 0x66, 0xd6, 0xc2, 0x39, 0x7b,
	0xe6, 0xf7, 0xfc, 0xc1, 0xbf, 0x4d, 0xf0, 0x97, 0x09, 0xb6, 0x59, 0x82, 0xde, 0xc3, 0xa8, 0x91,
	0xe9, 0xda, 0x9a, 0xfd, 0xb4, 0xcb, 0xd6, 0x02, 0x35, 0xfd, 0xa3, 0x41, 0x9d, 0xeb, 0xbf, 0xe0,
	0x96, 0x85, 0x30, 0x8c, 0xe5, 0xb5, 0x54, 0x34, 0x8f, 0x58, 0x4e, 0x52, 0xea, 0x0e, 0x74, 0x97,
	0x60, 0x1f, 0x0d, 0x2b, 0xcd, 0x5b, 0x56, 0x34, 0xec, 0xc8, 0x9b, 0x03, 0xfa, 0x04, 0xa3, 0x82,
	0xc4, 0xdf, 0x48, 0x4a, 0xa5, 0x7b, 0x30, 0x1b, 0x2c, 0x9c, 0xb3, 0x97, 0xfb, 0xf4, 0x0b, 0x6b,
	0x0e, 0x6e, 0xc9, 0xe8, 0x14, 0x26, 0x85, 0xa0, 0x25, 0xdd, 0xaa, 0x48, 0xd0, 0x35, 0xe7, 0xca,
	0x1d, 0xce, 0xac, 0xc5, 0x08, 0x1f, 0x9b, 0x2a, 0xd6, 0x45, 0xcf, 0x03, 0x7b, 0x99, 0xa0, 0xfb,
	0x30, 0x2c, 0x49, 0xb6, 0xa3, 0xda, 0xc6, 0x23, 0x5c, 0x1f, 0xbc, 0x9f, 0x16, 0x38, 0x1d, 0xa1,
	0xc8, 0x85, 0xc3, 0x92, 0x8a, 0xea, 0x51, 0x83, 0x6b, 0x8e, 0xe8, 0x1c, 0x4e, 0xba, 0x4e, 0xe8,
	0x89, 0x19, 0x53, 0x1f, 0x74, 0xe5, 0xaf, 0xea, 0x89, 0x86, 0x44, 0x6d, 0xf0, 0xb4, 0xf3, 0xed,
	0xaa, 0x80, 0x5e, 0xc3, 0x41, 0x92, 0xc5, 0xd2, 0x1d, 0xe8, 0x6f, 0x3f, 0xec, 0x1f, 0xc6, 0x45,
	0x16, 0x57, 0x03, 0xd4, 0x48, 0x74, 0x01, 0x27, 0xbc, 0xa4, 0xe2, 0x4a, 0x30, 0x55, 0xbd, 0x79,
	0x9d, 0x71, 0x92, 0xb8, 0x07, 0x7f, 0x7e, 0xf6, 0x6e, 0xcb, 0x08, 0x6b, 0x82, 0xf7, 0xdd, 0x82,
	0x43, 0xe3, 0x1f, 0xfa, 0x0c, 0x53, 0x93, 0xc7, 0xc8, 0x38, 0x69, 0x92, 0x75, 0xda, 0x2f, 0x27,
	0x34, 0xe1, 0x6d, 0xfc, 0x9f, 0x18, 0x76, 0xd3, 0xef, 0x1d, 0x8c, 0x4d, 0x9f, 0xbd, 0x3c, 0x71,
	0x0c, 0xb8, 0x3a, 0xcc, 0x7f, 0xd8, 0x30, 0x6d, 0xc7, 0x5c, 0x87, 0xef, 0x56, 0x68, 0xad, 0x7f,
	0x0a, 0x6d, 0xe3, 0xb2, 0xbd, 0xb7, 0xcb, 0xdd, 0x48, 0x0e, 0xfe, 0x27, 0x92, 0x4f, 0xe0, 0x78,
	0xcd, 0x89, 0x48, 0xa2, 0x92, 0x08, 0x46, 0xb6, 0x4a, 0x8f, 0xea, 0x08, 0x8f, 0x75, 0xf1, 0x4b,
	0x5d, 0xeb, 0x9f, 0xe9, 0xf0, 0x2f, 0x67, 0xfa, 0x21, 0xf8, 0xfa, 0x2a, 0xe5, 0x2d, 0xdc, 0xe7,
	0x22, 0x0d, 0x3a, 0x8b, 0xa5, 0xde, 0x4a, 0x41, 0xca, 0xdb, 0x95, 0xb8, 0xbe, 0xa3, 0xf7, 0xcb,
	0x9b, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0x10, 0x16, 0x88, 0x30, 0x05, 0x00, 0x00,
}
