// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/test/api/servod_service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	longrunning "go.chromium.org/chromiumos/config/go/longrunning"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CallServodRequest_Method int32

const (
	CallServodRequest_DOC CallServodRequest_Method = 0
	CallServodRequest_GET CallServodRequest_Method = 1
	CallServodRequest_SET CallServodRequest_Method = 2
)

var CallServodRequest_Method_name = map[int32]string{
	0: "DOC",
	1: "GET",
	2: "SET",
}

var CallServodRequest_Method_value = map[string]int32{
	"DOC": 0,
	"GET": 1,
	"SET": 2,
}

func (x CallServodRequest_Method) String() string {
	return proto.EnumName(CallServodRequest_Method_name, int32(x))
}

func (CallServodRequest_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{9, 0}
}

type StartServodRequest struct {
	// The path (URI) for the servod (containerized or running as a daemon) host.
	// If cros-servod and docker-servod live on the same host, this parameter
	// should be empty.
	ServoHostPath string `protobuf:"bytes,1,opt,name=servo_host_path,json=servoHostPath,proto3" json:"servo_host_path,omitempty"`
	// The servod Docker container name.
	DockerServodName string `protobuf:"bytes,2,opt,name=docker_servod_name,json=dockerServodName,proto3" json:"docker_servod_name,omitempty"`
	// The build version of Chrome OS.
	// This will be used as the tag name for the servod image to pull from GCR.
	BuildVersion string `protobuf:"bytes,3,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	// The --BOARD parameter value for servod command.
	Board string `protobuf:"bytes,4,opt,name=board,proto3" json:"board,omitempty"`
	// The --MODEL parameter value for servod command.
	Model string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	// The --SERIALNAME parameter value for servod command.
	SerialName string `protobuf:"bytes,6,opt,name=serial_name,json=serialName,proto3" json:"serial_name,omitempty"`
	// The --PORT parameter value for servod command.
	Port string `protobuf:"bytes,7,opt,name=port,proto3" json:"port,omitempty"`
	// The --DEBUG parameter value for servod command.
	Debug string `protobuf:"bytes,8,opt,name=debug,proto3" json:"debug,omitempty"`
	// The --RECOVERY_MODE parameter value for servod command.
	RecoveryMode string `protobuf:"bytes,9,opt,name=recovery_mode,json=recoveryMode,proto3" json:"recovery_mode,omitempty"`
	// The --CONFIG parameter value for servod command.
	Config string `protobuf:"bytes,10,opt,name=config,proto3" json:"config,omitempty"`
	// The --ALLOW-DUAL-V4 parameter value for servod command.
	AllowDualV4          string   `protobuf:"bytes,11,opt,name=allow_dual_v4,json=allowDualV4,proto3" json:"allow_dual_v4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartServodRequest) Reset()         { *m = StartServodRequest{} }
func (m *StartServodRequest) String() string { return proto.CompactTextString(m) }
func (*StartServodRequest) ProtoMessage()    {}
func (*StartServodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{0}
}

func (m *StartServodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartServodRequest.Unmarshal(m, b)
}
func (m *StartServodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartServodRequest.Marshal(b, m, deterministic)
}
func (m *StartServodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartServodRequest.Merge(m, src)
}
func (m *StartServodRequest) XXX_Size() int {
	return xxx_messageInfo_StartServodRequest.Size(m)
}
func (m *StartServodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartServodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartServodRequest proto.InternalMessageInfo

func (m *StartServodRequest) GetServoHostPath() string {
	if m != nil {
		return m.ServoHostPath
	}
	return ""
}

func (m *StartServodRequest) GetDockerServodName() string {
	if m != nil {
		return m.DockerServodName
	}
	return ""
}

func (m *StartServodRequest) GetBuildVersion() string {
	if m != nil {
		return m.BuildVersion
	}
	return ""
}

func (m *StartServodRequest) GetBoard() string {
	if m != nil {
		return m.Board
	}
	return ""
}

func (m *StartServodRequest) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *StartServodRequest) GetSerialName() string {
	if m != nil {
		return m.SerialName
	}
	return ""
}

func (m *StartServodRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *StartServodRequest) GetDebug() string {
	if m != nil {
		return m.Debug
	}
	return ""
}

func (m *StartServodRequest) GetRecoveryMode() string {
	if m != nil {
		return m.RecoveryMode
	}
	return ""
}

func (m *StartServodRequest) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *StartServodRequest) GetAllowDualV4() string {
	if m != nil {
		return m.AllowDualV4
	}
	return ""
}

type StartServodResponse struct {
	// Types that are valid to be assigned to Result:
	//	*StartServodResponse_Success_
	//	*StartServodResponse_Failure_
	Result               isStartServodResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *StartServodResponse) Reset()         { *m = StartServodResponse{} }
func (m *StartServodResponse) String() string { return proto.CompactTextString(m) }
func (*StartServodResponse) ProtoMessage()    {}
func (*StartServodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{1}
}

func (m *StartServodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartServodResponse.Unmarshal(m, b)
}
func (m *StartServodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartServodResponse.Marshal(b, m, deterministic)
}
func (m *StartServodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartServodResponse.Merge(m, src)
}
func (m *StartServodResponse) XXX_Size() int {
	return xxx_messageInfo_StartServodResponse.Size(m)
}
func (m *StartServodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartServodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartServodResponse proto.InternalMessageInfo

type isStartServodResponse_Result interface {
	isStartServodResponse_Result()
}

type StartServodResponse_Success_ struct {
	Success *StartServodResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type StartServodResponse_Failure_ struct {
	Failure *StartServodResponse_Failure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*StartServodResponse_Success_) isStartServodResponse_Result() {}

func (*StartServodResponse_Failure_) isStartServodResponse_Result() {}

func (m *StartServodResponse) GetResult() isStartServodResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *StartServodResponse) GetSuccess() *StartServodResponse_Success {
	if x, ok := m.GetResult().(*StartServodResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (m *StartServodResponse) GetFailure() *StartServodResponse_Failure {
	if x, ok := m.GetResult().(*StartServodResponse_Failure_); ok {
		return x.Failure
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StartServodResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StartServodResponse_Success_)(nil),
		(*StartServodResponse_Failure_)(nil),
	}
}

// Empty response for success.
type StartServodResponse_Success struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartServodResponse_Success) Reset()         { *m = StartServodResponse_Success{} }
func (m *StartServodResponse_Success) String() string { return proto.CompactTextString(m) }
func (*StartServodResponse_Success) ProtoMessage()    {}
func (*StartServodResponse_Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{1, 0}
}

func (m *StartServodResponse_Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartServodResponse_Success.Unmarshal(m, b)
}
func (m *StartServodResponse_Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartServodResponse_Success.Marshal(b, m, deterministic)
}
func (m *StartServodResponse_Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartServodResponse_Success.Merge(m, src)
}
func (m *StartServodResponse_Success) XXX_Size() int {
	return xxx_messageInfo_StartServodResponse_Success.Size(m)
}
func (m *StartServodResponse_Success) XXX_DiscardUnknown() {
	xxx_messageInfo_StartServodResponse_Success.DiscardUnknown(m)
}

var xxx_messageInfo_StartServodResponse_Success proto.InternalMessageInfo

// Error message for failure.
type StartServodResponse_Failure struct {
	ErrorMessage         string   `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartServodResponse_Failure) Reset()         { *m = StartServodResponse_Failure{} }
func (m *StartServodResponse_Failure) String() string { return proto.CompactTextString(m) }
func (*StartServodResponse_Failure) ProtoMessage()    {}
func (*StartServodResponse_Failure) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{1, 1}
}

func (m *StartServodResponse_Failure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartServodResponse_Failure.Unmarshal(m, b)
}
func (m *StartServodResponse_Failure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartServodResponse_Failure.Marshal(b, m, deterministic)
}
func (m *StartServodResponse_Failure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartServodResponse_Failure.Merge(m, src)
}
func (m *StartServodResponse_Failure) XXX_Size() int {
	return xxx_messageInfo_StartServodResponse_Failure.Size(m)
}
func (m *StartServodResponse_Failure) XXX_DiscardUnknown() {
	xxx_messageInfo_StartServodResponse_Failure.DiscardUnknown(m)
}

var xxx_messageInfo_StartServodResponse_Failure proto.InternalMessageInfo

func (m *StartServodResponse_Failure) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type StartServodMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartServodMetadata) Reset()         { *m = StartServodMetadata{} }
func (m *StartServodMetadata) String() string { return proto.CompactTextString(m) }
func (*StartServodMetadata) ProtoMessage()    {}
func (*StartServodMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{2}
}

func (m *StartServodMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartServodMetadata.Unmarshal(m, b)
}
func (m *StartServodMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartServodMetadata.Marshal(b, m, deterministic)
}
func (m *StartServodMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartServodMetadata.Merge(m, src)
}
func (m *StartServodMetadata) XXX_Size() int {
	return xxx_messageInfo_StartServodMetadata.Size(m)
}
func (m *StartServodMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_StartServodMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_StartServodMetadata proto.InternalMessageInfo

type StopServodRequest struct {
	// The path (URI) for the servod (containerized or running as a daemon) host.
	// If cros-servod and docker-servod live on the same host, this parameter
	// should be empty.
	ServoHostPath string `protobuf:"bytes,1,opt,name=servo_host_path,json=servoHostPath,proto3" json:"servo_host_path,omitempty"`
	// The servod Docker container name.
	DockerServodName string `protobuf:"bytes,2,opt,name=docker_servod_name,json=dockerServodName,proto3" json:"docker_servod_name,omitempty"`
	// The port that servod is running on the servo host.
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServodRequest) Reset()         { *m = StopServodRequest{} }
func (m *StopServodRequest) String() string { return proto.CompactTextString(m) }
func (*StopServodRequest) ProtoMessage()    {}
func (*StopServodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{3}
}

func (m *StopServodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServodRequest.Unmarshal(m, b)
}
func (m *StopServodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServodRequest.Marshal(b, m, deterministic)
}
func (m *StopServodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServodRequest.Merge(m, src)
}
func (m *StopServodRequest) XXX_Size() int {
	return xxx_messageInfo_StopServodRequest.Size(m)
}
func (m *StopServodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopServodRequest proto.InternalMessageInfo

func (m *StopServodRequest) GetServoHostPath() string {
	if m != nil {
		return m.ServoHostPath
	}
	return ""
}

func (m *StopServodRequest) GetDockerServodName() string {
	if m != nil {
		return m.DockerServodName
	}
	return ""
}

func (m *StopServodRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type StopServodResponse struct {
	// Types that are valid to be assigned to Result:
	//	*StopServodResponse_Success_
	//	*StopServodResponse_Failure_
	Result               isStopServodResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *StopServodResponse) Reset()         { *m = StopServodResponse{} }
func (m *StopServodResponse) String() string { return proto.CompactTextString(m) }
func (*StopServodResponse) ProtoMessage()    {}
func (*StopServodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{4}
}

func (m *StopServodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServodResponse.Unmarshal(m, b)
}
func (m *StopServodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServodResponse.Marshal(b, m, deterministic)
}
func (m *StopServodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServodResponse.Merge(m, src)
}
func (m *StopServodResponse) XXX_Size() int {
	return xxx_messageInfo_StopServodResponse.Size(m)
}
func (m *StopServodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopServodResponse proto.InternalMessageInfo

type isStopServodResponse_Result interface {
	isStopServodResponse_Result()
}

type StopServodResponse_Success_ struct {
	Success *StopServodResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type StopServodResponse_Failure_ struct {
	Failure *StopServodResponse_Failure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*StopServodResponse_Success_) isStopServodResponse_Result() {}

func (*StopServodResponse_Failure_) isStopServodResponse_Result() {}

func (m *StopServodResponse) GetResult() isStopServodResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *StopServodResponse) GetSuccess() *StopServodResponse_Success {
	if x, ok := m.GetResult().(*StopServodResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (m *StopServodResponse) GetFailure() *StopServodResponse_Failure {
	if x, ok := m.GetResult().(*StopServodResponse_Failure_); ok {
		return x.Failure
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StopServodResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StopServodResponse_Success_)(nil),
		(*StopServodResponse_Failure_)(nil),
	}
}

// Empty response for success.
type StopServodResponse_Success struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServodResponse_Success) Reset()         { *m = StopServodResponse_Success{} }
func (m *StopServodResponse_Success) String() string { return proto.CompactTextString(m) }
func (*StopServodResponse_Success) ProtoMessage()    {}
func (*StopServodResponse_Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{4, 0}
}

func (m *StopServodResponse_Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServodResponse_Success.Unmarshal(m, b)
}
func (m *StopServodResponse_Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServodResponse_Success.Marshal(b, m, deterministic)
}
func (m *StopServodResponse_Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServodResponse_Success.Merge(m, src)
}
func (m *StopServodResponse_Success) XXX_Size() int {
	return xxx_messageInfo_StopServodResponse_Success.Size(m)
}
func (m *StopServodResponse_Success) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServodResponse_Success.DiscardUnknown(m)
}

var xxx_messageInfo_StopServodResponse_Success proto.InternalMessageInfo

// Error message for failure.
type StopServodResponse_Failure struct {
	ErrorMessage         string   `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServodResponse_Failure) Reset()         { *m = StopServodResponse_Failure{} }
func (m *StopServodResponse_Failure) String() string { return proto.CompactTextString(m) }
func (*StopServodResponse_Failure) ProtoMessage()    {}
func (*StopServodResponse_Failure) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{4, 1}
}

func (m *StopServodResponse_Failure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServodResponse_Failure.Unmarshal(m, b)
}
func (m *StopServodResponse_Failure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServodResponse_Failure.Marshal(b, m, deterministic)
}
func (m *StopServodResponse_Failure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServodResponse_Failure.Merge(m, src)
}
func (m *StopServodResponse_Failure) XXX_Size() int {
	return xxx_messageInfo_StopServodResponse_Failure.Size(m)
}
func (m *StopServodResponse_Failure) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServodResponse_Failure.DiscardUnknown(m)
}

var xxx_messageInfo_StopServodResponse_Failure proto.InternalMessageInfo

func (m *StopServodResponse_Failure) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type StopServodMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServodMetadata) Reset()         { *m = StopServodMetadata{} }
func (m *StopServodMetadata) String() string { return proto.CompactTextString(m) }
func (*StopServodMetadata) ProtoMessage()    {}
func (*StopServodMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{5}
}

func (m *StopServodMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServodMetadata.Unmarshal(m, b)
}
func (m *StopServodMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServodMetadata.Marshal(b, m, deterministic)
}
func (m *StopServodMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServodMetadata.Merge(m, src)
}
func (m *StopServodMetadata) XXX_Size() int {
	return xxx_messageInfo_StopServodMetadata.Size(m)
}
func (m *StopServodMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServodMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_StopServodMetadata proto.InternalMessageInfo

type ExecCmdRequest struct {
	// The path (URI) for the servod (containerized or running as a daemon) host.
	// If cros-servod and docker-servod live on the same host, this parameter
	// should be empty.
	ServoHostPath string `protobuf:"bytes,1,opt,name=servo_host_path,json=servoHostPath,proto3" json:"servo_host_path,omitempty"`
	// The servod Docker container name.
	DockerServodName string `protobuf:"bytes,2,opt,name=docker_servod_name,json=dockerServodName,proto3" json:"docker_servod_name,omitempty"`
	// The command to execute on the servo host.
	// Example commands:
	// "dut-control -p $PORT power_state:off"
	Command string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	// stdin is passed to the command as the program's stdin.
	// The stream does not support seeking.
	// An empty bytes is not treated specially; if the command reads
	// from stdin, it will receive zero bytes.
	Stdin                []byte   `protobuf:"bytes,4,opt,name=stdin,proto3" json:"stdin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecCmdRequest) Reset()         { *m = ExecCmdRequest{} }
func (m *ExecCmdRequest) String() string { return proto.CompactTextString(m) }
func (*ExecCmdRequest) ProtoMessage()    {}
func (*ExecCmdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{6}
}

func (m *ExecCmdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecCmdRequest.Unmarshal(m, b)
}
func (m *ExecCmdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecCmdRequest.Marshal(b, m, deterministic)
}
func (m *ExecCmdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecCmdRequest.Merge(m, src)
}
func (m *ExecCmdRequest) XXX_Size() int {
	return xxx_messageInfo_ExecCmdRequest.Size(m)
}
func (m *ExecCmdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecCmdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecCmdRequest proto.InternalMessageInfo

func (m *ExecCmdRequest) GetServoHostPath() string {
	if m != nil {
		return m.ServoHostPath
	}
	return ""
}

func (m *ExecCmdRequest) GetDockerServodName() string {
	if m != nil {
		return m.DockerServodName
	}
	return ""
}

func (m *ExecCmdRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ExecCmdRequest) GetStdin() []byte {
	if m != nil {
		return m.Stdin
	}
	return nil
}

type ExecCmdResponse struct {
	// The exit information that is set when the command has exited
	// or failed to start.
	ExitInfo *ExecCmdResponse_ExitInfo `protobuf:"bytes,1,opt,name=exit_info,json=exitInfo,proto3" json:"exit_info,omitempty"`
	// The shell command's stdout output since the last response in the stream.
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// The shell command's stderr output since the last response in the stream.
	Stderr               []byte   `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecCmdResponse) Reset()         { *m = ExecCmdResponse{} }
func (m *ExecCmdResponse) String() string { return proto.CompactTextString(m) }
func (*ExecCmdResponse) ProtoMessage()    {}
func (*ExecCmdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{7}
}

func (m *ExecCmdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecCmdResponse.Unmarshal(m, b)
}
func (m *ExecCmdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecCmdResponse.Marshal(b, m, deterministic)
}
func (m *ExecCmdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecCmdResponse.Merge(m, src)
}
func (m *ExecCmdResponse) XXX_Size() int {
	return xxx_messageInfo_ExecCmdResponse.Size(m)
}
func (m *ExecCmdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecCmdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecCmdResponse proto.InternalMessageInfo

func (m *ExecCmdResponse) GetExitInfo() *ExecCmdResponse_ExitInfo {
	if m != nil {
		return m.ExitInfo
	}
	return nil
}

func (m *ExecCmdResponse) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *ExecCmdResponse) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

type ExecCmdResponse_ExitInfo struct {
	// status provides information about how the command process
	// terminated.
	//
	// If the command failed to start, status is set to an arbitrary
	// non-zero value.
	//
	// If signaled is set, status is set to the signal that caused
	// the command to terminate.
	//
	// Otherwise, status is set to the exit status of the process.
	// Exit statuses outside of 0 to 255 inclusive are not supported;
	// they will be mapped to an arbitrary non-zero value.
	//
	// status is zero if and only if the process was successfully
	// started and exited with a zero status.
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// signaled indicates whether the command exited due to a signal.
	// If set, status contains the signal.
	Signaled bool `protobuf:"varint,2,opt,name=signaled,proto3" json:"signaled,omitempty"`
	// started indicates whether the command was started.
	Started bool `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	// error_message provides a human readable explanation for some errors.
	// This MUST NOT be inspected by programs.
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecCmdResponse_ExitInfo) Reset()         { *m = ExecCmdResponse_ExitInfo{} }
func (m *ExecCmdResponse_ExitInfo) String() string { return proto.CompactTextString(m) }
func (*ExecCmdResponse_ExitInfo) ProtoMessage()    {}
func (*ExecCmdResponse_ExitInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{7, 0}
}

func (m *ExecCmdResponse_ExitInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecCmdResponse_ExitInfo.Unmarshal(m, b)
}
func (m *ExecCmdResponse_ExitInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecCmdResponse_ExitInfo.Marshal(b, m, deterministic)
}
func (m *ExecCmdResponse_ExitInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecCmdResponse_ExitInfo.Merge(m, src)
}
func (m *ExecCmdResponse_ExitInfo) XXX_Size() int {
	return xxx_messageInfo_ExecCmdResponse_ExitInfo.Size(m)
}
func (m *ExecCmdResponse_ExitInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecCmdResponse_ExitInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ExecCmdResponse_ExitInfo proto.InternalMessageInfo

func (m *ExecCmdResponse_ExitInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ExecCmdResponse_ExitInfo) GetSignaled() bool {
	if m != nil {
		return m.Signaled
	}
	return false
}

func (m *ExecCmdResponse_ExitInfo) GetStarted() bool {
	if m != nil {
		return m.Started
	}
	return false
}

func (m *ExecCmdResponse_ExitInfo) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type ExecCmdMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecCmdMetadata) Reset()         { *m = ExecCmdMetadata{} }
func (m *ExecCmdMetadata) String() string { return proto.CompactTextString(m) }
func (*ExecCmdMetadata) ProtoMessage()    {}
func (*ExecCmdMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{8}
}

func (m *ExecCmdMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecCmdMetadata.Unmarshal(m, b)
}
func (m *ExecCmdMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecCmdMetadata.Marshal(b, m, deterministic)
}
func (m *ExecCmdMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecCmdMetadata.Merge(m, src)
}
func (m *ExecCmdMetadata) XXX_Size() int {
	return xxx_messageInfo_ExecCmdMetadata.Size(m)
}
func (m *ExecCmdMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecCmdMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ExecCmdMetadata proto.InternalMessageInfo

type CallServodRequest struct {
	// The path (URI) for the servod (containerized or running as a daemon) host.
	// If cros-servod and docker-servod live on the same host, this parameter
	// should be empty.
	ServoHostPath string `protobuf:"bytes,1,opt,name=servo_host_path,json=servoHostPath,proto3" json:"servo_host_path,omitempty"`
	// The servod Docker container name.
	DockerServodName string `protobuf:"bytes,2,opt,name=docker_servod_name,json=dockerServodName,proto3" json:"docker_servod_name,omitempty"`
	// The method to call.
	Method CallServodRequest_Method `protobuf:"varint,3,opt,name=method,proto3,enum=chromiumos.test.api.CallServodRequest_Method" json:"method,omitempty"`
	// The arguments to pass to the method.
	// For the doc and get methods, there will be a single argument which is
	// the control name (e.g. fakedisconnect).
	// For the set method, it will be the control name and the value separated
	// with a colon and wrapped inside a quote (e.g. "fakedisconnect:100 2000").
	Args                 string   `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallServodRequest) Reset()         { *m = CallServodRequest{} }
func (m *CallServodRequest) String() string { return proto.CompactTextString(m) }
func (*CallServodRequest) ProtoMessage()    {}
func (*CallServodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{9}
}

func (m *CallServodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallServodRequest.Unmarshal(m, b)
}
func (m *CallServodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallServodRequest.Marshal(b, m, deterministic)
}
func (m *CallServodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallServodRequest.Merge(m, src)
}
func (m *CallServodRequest) XXX_Size() int {
	return xxx_messageInfo_CallServodRequest.Size(m)
}
func (m *CallServodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallServodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallServodRequest proto.InternalMessageInfo

func (m *CallServodRequest) GetServoHostPath() string {
	if m != nil {
		return m.ServoHostPath
	}
	return ""
}

func (m *CallServodRequest) GetDockerServodName() string {
	if m != nil {
		return m.DockerServodName
	}
	return ""
}

func (m *CallServodRequest) GetMethod() CallServodRequest_Method {
	if m != nil {
		return m.Method
	}
	return CallServodRequest_DOC
}

func (m *CallServodRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type CallServodResponse struct {
	// Types that are valid to be assigned to Result:
	//	*CallServodResponse_Success_
	//	*CallServodResponse_Failure_
	Result               isCallServodResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CallServodResponse) Reset()         { *m = CallServodResponse{} }
func (m *CallServodResponse) String() string { return proto.CompactTextString(m) }
func (*CallServodResponse) ProtoMessage()    {}
func (*CallServodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{10}
}

func (m *CallServodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallServodResponse.Unmarshal(m, b)
}
func (m *CallServodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallServodResponse.Marshal(b, m, deterministic)
}
func (m *CallServodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallServodResponse.Merge(m, src)
}
func (m *CallServodResponse) XXX_Size() int {
	return xxx_messageInfo_CallServodResponse.Size(m)
}
func (m *CallServodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallServodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallServodResponse proto.InternalMessageInfo

type isCallServodResponse_Result interface {
	isCallServodResponse_Result()
}

type CallServodResponse_Success_ struct {
	Success *CallServodResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type CallServodResponse_Failure_ struct {
	Failure *CallServodResponse_Failure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*CallServodResponse_Success_) isCallServodResponse_Result() {}

func (*CallServodResponse_Failure_) isCallServodResponse_Result() {}

func (m *CallServodResponse) GetResult() isCallServodResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CallServodResponse) GetSuccess() *CallServodResponse_Success {
	if x, ok := m.GetResult().(*CallServodResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (m *CallServodResponse) GetFailure() *CallServodResponse_Failure {
	if x, ok := m.GetResult().(*CallServodResponse_Failure_); ok {
		return x.Failure
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CallServodResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CallServodResponse_Success_)(nil),
		(*CallServodResponse_Failure_)(nil),
	}
}

// Response for success.
type CallServodResponse_Success struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallServodResponse_Success) Reset()         { *m = CallServodResponse_Success{} }
func (m *CallServodResponse_Success) String() string { return proto.CompactTextString(m) }
func (*CallServodResponse_Success) ProtoMessage()    {}
func (*CallServodResponse_Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{10, 0}
}

func (m *CallServodResponse_Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallServodResponse_Success.Unmarshal(m, b)
}
func (m *CallServodResponse_Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallServodResponse_Success.Marshal(b, m, deterministic)
}
func (m *CallServodResponse_Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallServodResponse_Success.Merge(m, src)
}
func (m *CallServodResponse_Success) XXX_Size() int {
	return xxx_messageInfo_CallServodResponse_Success.Size(m)
}
func (m *CallServodResponse_Success) XXX_DiscardUnknown() {
	xxx_messageInfo_CallServodResponse_Success.DiscardUnknown(m)
}

var xxx_messageInfo_CallServodResponse_Success proto.InternalMessageInfo

func (m *CallServodResponse_Success) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// Error message for failure.
type CallServodResponse_Failure struct {
	ErrorMessage         string   `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallServodResponse_Failure) Reset()         { *m = CallServodResponse_Failure{} }
func (m *CallServodResponse_Failure) String() string { return proto.CompactTextString(m) }
func (*CallServodResponse_Failure) ProtoMessage()    {}
func (*CallServodResponse_Failure) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{10, 1}
}

func (m *CallServodResponse_Failure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallServodResponse_Failure.Unmarshal(m, b)
}
func (m *CallServodResponse_Failure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallServodResponse_Failure.Marshal(b, m, deterministic)
}
func (m *CallServodResponse_Failure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallServodResponse_Failure.Merge(m, src)
}
func (m *CallServodResponse_Failure) XXX_Size() int {
	return xxx_messageInfo_CallServodResponse_Failure.Size(m)
}
func (m *CallServodResponse_Failure) XXX_DiscardUnknown() {
	xxx_messageInfo_CallServodResponse_Failure.DiscardUnknown(m)
}

var xxx_messageInfo_CallServodResponse_Failure proto.InternalMessageInfo

func (m *CallServodResponse_Failure) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type CallServodMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallServodMetadata) Reset()         { *m = CallServodMetadata{} }
func (m *CallServodMetadata) String() string { return proto.CompactTextString(m) }
func (*CallServodMetadata) ProtoMessage()    {}
func (*CallServodMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_88add0f20deb49eb, []int{11}
}

func (m *CallServodMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallServodMetadata.Unmarshal(m, b)
}
func (m *CallServodMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallServodMetadata.Marshal(b, m, deterministic)
}
func (m *CallServodMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallServodMetadata.Merge(m, src)
}
func (m *CallServodMetadata) XXX_Size() int {
	return xxx_messageInfo_CallServodMetadata.Size(m)
}
func (m *CallServodMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_CallServodMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_CallServodMetadata proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("chromiumos.test.api.CallServodRequest_Method", CallServodRequest_Method_name, CallServodRequest_Method_value)
	proto.RegisterType((*StartServodRequest)(nil), "chromiumos.test.api.StartServodRequest")
	proto.RegisterType((*StartServodResponse)(nil), "chromiumos.test.api.StartServodResponse")
	proto.RegisterType((*StartServodResponse_Success)(nil), "chromiumos.test.api.StartServodResponse.Success")
	proto.RegisterType((*StartServodResponse_Failure)(nil), "chromiumos.test.api.StartServodResponse.Failure")
	proto.RegisterType((*StartServodMetadata)(nil), "chromiumos.test.api.StartServodMetadata")
	proto.RegisterType((*StopServodRequest)(nil), "chromiumos.test.api.StopServodRequest")
	proto.RegisterType((*StopServodResponse)(nil), "chromiumos.test.api.StopServodResponse")
	proto.RegisterType((*StopServodResponse_Success)(nil), "chromiumos.test.api.StopServodResponse.Success")
	proto.RegisterType((*StopServodResponse_Failure)(nil), "chromiumos.test.api.StopServodResponse.Failure")
	proto.RegisterType((*StopServodMetadata)(nil), "chromiumos.test.api.StopServodMetadata")
	proto.RegisterType((*ExecCmdRequest)(nil), "chromiumos.test.api.ExecCmdRequest")
	proto.RegisterType((*ExecCmdResponse)(nil), "chromiumos.test.api.ExecCmdResponse")
	proto.RegisterType((*ExecCmdResponse_ExitInfo)(nil), "chromiumos.test.api.ExecCmdResponse.ExitInfo")
	proto.RegisterType((*ExecCmdMetadata)(nil), "chromiumos.test.api.ExecCmdMetadata")
	proto.RegisterType((*CallServodRequest)(nil), "chromiumos.test.api.CallServodRequest")
	proto.RegisterType((*CallServodResponse)(nil), "chromiumos.test.api.CallServodResponse")
	proto.RegisterType((*CallServodResponse_Success)(nil), "chromiumos.test.api.CallServodResponse.Success")
	proto.RegisterType((*CallServodResponse_Failure)(nil), "chromiumos.test.api.CallServodResponse.Failure")
	proto.RegisterType((*CallServodMetadata)(nil), "chromiumos.test.api.CallServodMetadata")
}

func init() {
	proto.RegisterFile("chromiumos/test/api/servod_service.proto", fileDescriptor_88add0f20deb49eb)
}

var fileDescriptor_88add0f20deb49eb = []byte{
	// 877 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x0e, 0x65, 0x5b, 0x92, 0x47, 0x76, 0x62, 0x6f, 0xd2, 0x82, 0xd0, 0xa5, 0x0d, 0x5d, 0xc4,
	0x46, 0x5b, 0x93, 0x46, 0x9a, 0x17, 0x48, 0x1c, 0xb5, 0x69, 0x53, 0x35, 0x05, 0x15, 0xf8, 0xd0,
	0x0b, 0xb1, 0x22, 0x57, 0xd4, 0xa2, 0x24, 0x97, 0xdd, 0x5d, 0xaa, 0xee, 0x21, 0xb7, 0x1e, 0x0a,
	0xb4, 0xe7, 0x3e, 0x58, 0x8e, 0x7d, 0x81, 0xa2, 0xe7, 0x02, 0x3d, 0x17, 0xfb, 0x23, 0x4a, 0x96,
	0xe8, 0x44, 0x41, 0x90, 0x9c, 0xb8, 0x33, 0x3b, 0x33, 0x3b, 0xbb, 0xdf, 0x7c, 0xc3, 0x81, 0x93,
	0x78, 0xca, 0x59, 0x4e, 0xab, 0x9c, 0x89, 0x40, 0x12, 0x21, 0x03, 0x5c, 0xd2, 0x40, 0x10, 0x3e,
	0x63, 0x49, 0xa4, 0x3e, 0x34, 0x26, 0x7e, 0xc9, 0x99, 0x64, 0xe8, 0xf6, 0xc2, 0xd2, 0x57, 0x96,
	0x3e, 0x2e, 0x69, 0xff, 0x78, 0xc9, 0x3d, 0x63, 0x45, 0xca, 0xab, 0xa2, 0xa0, 0x45, 0x1a, 0xb0,
	0x92, 0x70, 0x2c, 0x29, 0x2b, 0x84, 0xf1, 0xf6, 0xfe, 0x6e, 0x01, 0x1a, 0x49, 0xcc, 0xe5, 0x48,
	0xc7, 0x0e, 0xc9, 0x4f, 0x15, 0x11, 0x12, 0xdd, 0x83, 0x5b, 0xfa, 0xb0, 0x68, 0xca, 0x84, 0x8c,
	0x4a, 0x2c, 0xa7, 0xae, 0xf3, 0xb1, 0x73, 0xb2, 0x1b, 0xee, 0x6b, 0xf5, 0x13, 0x26, 0xe4, 0xf7,
	0x58, 0x4e, 0xd1, 0xe7, 0x80, 0x12, 0x16, 0xff, 0x48, 0x78, 0x64, 0x73, 0x2b, 0x70, 0x4e, 0xdc,
	0x96, 0x36, 0x3d, 0x30, 0x3b, 0x26, 0xf0, 0x77, 0x38, 0x27, 0xe8, 0x08, 0xf6, 0xc7, 0x15, 0xcd,
	0x92, 0x68, 0x46, 0xb8, 0xa0, 0xac, 0x70, 0xb7, 0xb4, 0xe1, 0x9e, 0x56, 0x5e, 0x18, 0x1d, 0xba,
	0x03, 0x3b, 0x63, 0x86, 0x79, 0xe2, 0x6e, 0xeb, 0x4d, 0x23, 0x28, 0x6d, 0xce, 0x12, 0x92, 0xb9,
	0x3b, 0x46, 0xab, 0x05, 0xf4, 0x11, 0xf4, 0x04, 0xe1, 0x14, 0x67, 0xe6, 0xdc, 0xb6, 0xde, 0x03,
	0xa3, 0xd2, 0x27, 0x22, 0xd8, 0x2e, 0x19, 0x97, 0x6e, 0x47, 0xef, 0xe8, 0xb5, 0x0a, 0x95, 0x90,
	0x71, 0x95, 0xba, 0x5d, 0x13, 0x4a, 0x0b, 0x2a, 0x37, 0x4e, 0x62, 0x36, 0x23, 0xfc, 0x97, 0x48,
	0x05, 0x77, 0x77, 0x4d, 0x6e, 0x73, 0xe5, 0x90, 0x25, 0x04, 0x7d, 0x08, 0xed, 0x98, 0x15, 0x13,
	0x9a, 0xba, 0xa0, 0x77, 0xad, 0x84, 0x3c, 0xd8, 0xc7, 0x59, 0xc6, 0x7e, 0x8e, 0x92, 0x0a, 0x67,
	0xd1, 0xec, 0x81, 0xdb, 0xd3, 0xdb, 0x3d, 0xad, 0x7c, 0x5c, 0xe1, 0xec, 0xe2, 0x81, 0xf7, 0x9f,
	0x03, 0xb7, 0xaf, 0xbc, 0xb4, 0x28, 0x59, 0x21, 0x08, 0xfa, 0x16, 0x3a, 0xa2, 0x8a, 0x63, 0x22,
	0x84, 0x7e, 0xe2, 0xde, 0xfd, 0x33, 0xbf, 0x01, 0x51, 0xbf, 0xc1, 0xd5, 0x1f, 0x19, 0xbf, 0x27,
	0x37, 0xc2, 0x79, 0x08, 0x15, 0x6d, 0x82, 0x69, 0x56, 0x71, 0x83, 0xc2, 0x9b, 0x44, 0xfb, 0xd2,
	0xf8, 0xa9, 0x68, 0x36, 0x44, 0x7f, 0x17, 0x3a, 0xf6, 0x8c, 0xbe, 0x0f, 0x1d, 0x6b, 0xa0, 0x9e,
	0x8a, 0x70, 0xce, 0x78, 0x94, 0x13, 0x21, 0x70, 0x4a, 0x6c, 0x69, 0xec, 0x69, 0xe5, 0xd0, 0xe8,
	0x1e, 0x75, 0xa1, 0xcd, 0x89, 0xa8, 0x32, 0xe9, 0x7d, 0x70, 0xe5, 0xde, 0x43, 0x22, 0x71, 0x82,
	0x25, 0xf6, 0x5e, 0xc0, 0xe1, 0x48, 0xb2, 0xf2, 0x7d, 0xd4, 0xdd, 0xbc, 0x0a, 0xb6, 0x16, 0x55,
	0xe0, 0xfd, 0xeb, 0xa8, 0xc2, 0x5f, 0x9c, 0x6f, 0xd1, 0x78, 0xba, 0x8a, 0x46, 0x70, 0xcd, 0xfb,
	0xad, 0x7a, 0x36, 0x81, 0xf1, 0x74, 0x15, 0x8c, 0x8d, 0x83, 0xbd, 0x2b, 0x2c, 0xee, 0x2c, 0x5f,
	0xba, 0x86, 0xe2, 0x4f, 0x07, 0x6e, 0x0e, 0x2e, 0x49, 0x7c, 0x9e, 0xbf, 0x63, 0x20, 0x5c, 0xe8,
	0xc4, 0x2c, 0xcf, 0x71, 0x91, 0x58, 0x2c, 0xe6, 0xa2, 0x22, 0xa5, 0x90, 0x09, 0x2d, 0x34, 0xeb,
	0xf7, 0x42, 0x23, 0x78, 0x7f, 0xb4, 0xe0, 0x56, 0x9d, 0x98, 0x45, 0xe8, 0x1b, 0xd8, 0x25, 0x97,
	0x54, 0x46, 0xb4, 0x98, 0x30, 0x8b, 0xd1, 0x69, 0xe3, 0xb3, 0xae, 0x38, 0xfa, 0x83, 0x4b, 0x2a,
	0xbf, 0x2e, 0x26, 0x2c, 0xec, 0x12, 0xbb, 0x52, 0x7c, 0x16, 0x32, 0x61, 0x95, 0xd4, 0x19, 0xef,
	0x85, 0x56, 0xb2, 0x7a, 0xc2, 0xb9, 0x4e, 0xd3, 0xe8, 0x09, 0xe7, 0xfd, 0x17, 0xd0, 0x1d, 0x5c,
	0xf1, 0xc5, 0xb2, 0x32, 0x85, 0xb2, 0x13, 0x5a, 0x09, 0xf5, 0xa1, 0x2b, 0x68, 0x5a, 0xe0, 0x8c,
	0x24, 0x3a, 0x6a, 0x37, 0xac, 0x65, 0x75, 0x7f, 0xa1, 0xa8, 0x40, 0xcc, 0xfd, 0xbb, 0xe1, 0x5c,
	0x5c, 0xc7, 0x71, 0x7b, 0x1d, 0x47, 0xef, 0xb0, 0x7e, 0x8d, 0x1a, 0xba, 0x7f, 0x1c, 0x38, 0x3c,
	0xc7, 0x59, 0xf6, 0x3e, 0x68, 0x34, 0x80, 0x76, 0x4e, 0xe4, 0x94, 0x99, 0xe4, 0x6f, 0x5e, 0xf3,
	0xec, 0x6b, 0xd9, 0xf8, 0x43, 0xed, 0x14, 0x5a, 0x67, 0xc5, 0x46, 0xcc, 0x53, 0x61, 0x6f, 0xa8,
	0xd7, 0xde, 0x11, 0xb4, 0x8d, 0x15, 0xea, 0xc0, 0xd6, 0xe3, 0x67, 0xe7, 0x07, 0x37, 0xd4, 0xe2,
	0xab, 0xc1, 0xf3, 0x03, 0x47, 0x2d, 0x46, 0x83, 0xe7, 0x07, 0x2d, 0xef, 0xf7, 0x16, 0xa0, 0xe5,
	0xe8, 0x6f, 0x46, 0xd9, 0x75, 0xcf, 0xb7, 0xa0, 0x6c, 0x43, 0xb0, 0x06, 0xca, 0xde, 0xad, 0x29,
	0xab, 0xaa, 0xc5, 0x50, 0xd0, 0x02, 0x61, 0xa5, 0xb7, 0xa3, 0xf2, 0x22, 0x8b, 0x79, 0x3d, 0xdc,
	0xff, 0x6b, 0x0b, 0xf6, 0x8d, 0x6a, 0x64, 0xa6, 0x04, 0xf4, 0x9b, 0x03, 0xbd, 0xa5, 0xfe, 0x8b,
	0x8e, 0x5f, 0xff, 0x43, 0xd0, 0xb0, 0xf5, 0xef, 0x2e, 0x1b, 0x2e, 0x0d, 0x11, 0xfe, 0xb3, 0xf9,
	0x10, 0xe1, 0x9d, 0xbe, 0x7c, 0xf8, 0x69, 0xf3, 0x5f, 0xad, 0xa9, 0xe5, 0xa3, 0x5f, 0x1d, 0x80,
	0x45, 0xfb, 0x41, 0xf7, 0x5e, 0xdb, 0x0d, 0x37, 0x4e, 0xe4, 0xb3, 0x97, 0x0f, 0x4f, 0x1a, 0xfb,
	0x79, 0x43, 0xbb, 0x43, 0x17, 0xd0, 0xb1, 0x34, 0x42, 0x47, 0xaf, 0xee, 0x1c, 0xe6, 0xfc, 0x4f,
	0x36, 0x69, 0x2f, 0x67, 0x0e, 0x8a, 0x00, 0x16, 0x88, 0x5c, 0x73, 0xbb, 0x35, 0x76, 0xf4, 0x8f,
	0x37, 0x2c, 0xb0, 0x33, 0xe7, 0x51, 0xf0, 0xc3, 0x69, 0xca, 0x6a, 0x73, 0x9f, 0xf1, 0x34, 0x58,
	0x9a, 0xf3, 0xcc, 0x2c, 0x12, 0xa4, 0xac, 0x1e, 0x18, 0xc7, 0x6d, 0x3d, 0xe4, 0x7d, 0xf1, 0x7f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0xf5, 0x5d, 0x9c, 0x4e, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServodServiceClient is the client API for ServodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServodServiceClient interface {
	// StartServod runs a servod Docker container and starts the servod daemon
	// inside the container if servod is containerized. Otherwise, it simply
	// starts the servod daemon.
	StartServod(ctx context.Context, in *StartServodRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// StopServod stops the servod daemon inside the container and stops the
	// servod Docker container if servod is containerized. Otherwise, it simply
	// stops the servod daemon.
	StopServod(ctx context.Context, in *StopServodRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// ExecCmd executes a servod command inside the servod Docker container
	// if docker_servod_name parameter is provided. Otherwise, it executes the
	// command directly inside the servo host.
	// Example commands:
	// "dut-control -p $PORT power_state:off"
	ExecCmd(ctx context.Context, in *ExecCmdRequest, opts ...grpc.CallOption) (ServodService_ExecCmdClient, error)
	// CallServod runs a servod command through an XML-RPC call inside the
	// servod Docker container if docker_servod_name parameter is provided.
	// Otherwise, it runs the command directly inside the servo host.
	// Allowed methods: doc, get, and set.
	CallServod(ctx context.Context, in *CallServodRequest, opts ...grpc.CallOption) (ServodService_CallServodClient, error)
}

type servodServiceClient struct {
	cc *grpc.ClientConn
}

func NewServodServiceClient(cc *grpc.ClientConn) ServodServiceClient {
	return &servodServiceClient{cc}
}

func (c *servodServiceClient) StartServod(ctx context.Context, in *StartServodRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/chromiumos.test.api.ServodService/StartServod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servodServiceClient) StopServod(ctx context.Context, in *StopServodRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/chromiumos.test.api.ServodService/StopServod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servodServiceClient) ExecCmd(ctx context.Context, in *ExecCmdRequest, opts ...grpc.CallOption) (ServodService_ExecCmdClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ServodService_serviceDesc.Streams[0], "/chromiumos.test.api.ServodService/ExecCmd", opts...)
	if err != nil {
		return nil, err
	}
	x := &servodServiceExecCmdClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServodService_ExecCmdClient interface {
	Recv() (*ExecCmdResponse, error)
	grpc.ClientStream
}

type servodServiceExecCmdClient struct {
	grpc.ClientStream
}

func (x *servodServiceExecCmdClient) Recv() (*ExecCmdResponse, error) {
	m := new(ExecCmdResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *servodServiceClient) CallServod(ctx context.Context, in *CallServodRequest, opts ...grpc.CallOption) (ServodService_CallServodClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ServodService_serviceDesc.Streams[1], "/chromiumos.test.api.ServodService/CallServod", opts...)
	if err != nil {
		return nil, err
	}
	x := &servodServiceCallServodClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServodService_CallServodClient interface {
	Recv() (*CallServodResponse, error)
	grpc.ClientStream
}

type servodServiceCallServodClient struct {
	grpc.ClientStream
}

func (x *servodServiceCallServodClient) Recv() (*CallServodResponse, error) {
	m := new(CallServodResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServodServiceServer is the server API for ServodService service.
type ServodServiceServer interface {
	// StartServod runs a servod Docker container and starts the servod daemon
	// inside the container if servod is containerized. Otherwise, it simply
	// starts the servod daemon.
	StartServod(context.Context, *StartServodRequest) (*longrunning.Operation, error)
	// StopServod stops the servod daemon inside the container and stops the
	// servod Docker container if servod is containerized. Otherwise, it simply
	// stops the servod daemon.
	StopServod(context.Context, *StopServodRequest) (*longrunning.Operation, error)
	// ExecCmd executes a servod command inside the servod Docker container
	// if docker_servod_name parameter is provided. Otherwise, it executes the
	// command directly inside the servo host.
	// Example commands:
	// "dut-control -p $PORT power_state:off"
	ExecCmd(*ExecCmdRequest, ServodService_ExecCmdServer) error
	// CallServod runs a servod command through an XML-RPC call inside the
	// servod Docker container if docker_servod_name parameter is provided.
	// Otherwise, it runs the command directly inside the servo host.
	// Allowed methods: doc, get, and set.
	CallServod(*CallServodRequest, ServodService_CallServodServer) error
}

// UnimplementedServodServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServodServiceServer struct {
}

func (*UnimplementedServodServiceServer) StartServod(ctx context.Context, req *StartServodRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartServod not implemented")
}
func (*UnimplementedServodServiceServer) StopServod(ctx context.Context, req *StopServodRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopServod not implemented")
}
func (*UnimplementedServodServiceServer) ExecCmd(req *ExecCmdRequest, srv ServodService_ExecCmdServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecCmd not implemented")
}
func (*UnimplementedServodServiceServer) CallServod(req *CallServodRequest, srv ServodService_CallServodServer) error {
	return status.Errorf(codes.Unimplemented, "method CallServod not implemented")
}

func RegisterServodServiceServer(s *grpc.Server, srv ServodServiceServer) {
	s.RegisterService(&_ServodService_serviceDesc, srv)
}

func _ServodService_StartServod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartServodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServodServiceServer).StartServod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromiumos.test.api.ServodService/StartServod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServodServiceServer).StartServod(ctx, req.(*StartServodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServodService_StopServod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServodServiceServer).StopServod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromiumos.test.api.ServodService/StopServod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServodServiceServer).StopServod(ctx, req.(*StopServodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServodService_ExecCmd_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecCmdRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServodServiceServer).ExecCmd(m, &servodServiceExecCmdServer{stream})
}

type ServodService_ExecCmdServer interface {
	Send(*ExecCmdResponse) error
	grpc.ServerStream
}

type servodServiceExecCmdServer struct {
	grpc.ServerStream
}

func (x *servodServiceExecCmdServer) Send(m *ExecCmdResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ServodService_CallServod_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CallServodRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServodServiceServer).CallServod(m, &servodServiceCallServodServer{stream})
}

type ServodService_CallServodServer interface {
	Send(*CallServodResponse) error
	grpc.ServerStream
}

type servodServiceCallServodServer struct {
	grpc.ServerStream
}

func (x *servodServiceCallServodServer) Send(m *CallServodResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ServodService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chromiumos.test.api.ServodService",
	HandlerType: (*ServodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartServod",
			Handler:    _ServodService_StartServod_Handler,
		},
		{
			MethodName: "StopServod",
			Handler:    _ServodService_StopServod_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecCmd",
			Handler:       _ServodService_ExecCmd_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CallServod",
			Handler:       _ServodService_CallServod_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chromiumos/test/api/servod_service.proto",
}
