// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/test/api/test_service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_go "go.chromium.org/chromiumos/config/go"
	longrunning "go.chromium.org/chromiumos/config/go/longrunning"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// When the status code is other than OK, details in Status message should be
// parsed for ErrorInfo message with the following Reasons as the reason.
type ProvisionFailure_Reason int32

const (
	// status code: INVALID_ARGUMENT
	ProvisionFailure_REASON_INVALID_REQUEST ProvisionFailure_Reason = 0
	// status code: FAILED_PRECONDITION
	ProvisionFailure_REASON_DUT_UNREACHABLE_PRE_PROVISION ProvisionFailure_Reason = 1
	// status code: FAILED_PRECONDITION
	ProvisionFailure_REASON_DOWNLOADING_IMAGE_FAILED ProvisionFailure_Reason = 2
	// status code: DEADLINE_EXCEEDED
	ProvisionFailure_REASON_PROVISIONING_TIMEDOUT ProvisionFailure_Reason = 3
	// status code: ABORTED
	ProvisionFailure_REASON_PROVISIONING_FAILED ProvisionFailure_Reason = 4
	// status code: ABORTED
	ProvisionFailure_REASON_DUT_UNREACHABLE_POST_PROVISION ProvisionFailure_Reason = 5
)

var ProvisionFailure_Reason_name = map[int32]string{
	0: "REASON_INVALID_REQUEST",
	1: "REASON_DUT_UNREACHABLE_PRE_PROVISION",
	2: "REASON_DOWNLOADING_IMAGE_FAILED",
	3: "REASON_PROVISIONING_TIMEDOUT",
	4: "REASON_PROVISIONING_FAILED",
	5: "REASON_DUT_UNREACHABLE_POST_PROVISION",
}

var ProvisionFailure_Reason_value = map[string]int32{
	"REASON_INVALID_REQUEST":                0,
	"REASON_DUT_UNREACHABLE_PRE_PROVISION":  1,
	"REASON_DOWNLOADING_IMAGE_FAILED":       2,
	"REASON_PROVISIONING_TIMEDOUT":          3,
	"REASON_PROVISIONING_FAILED":            4,
	"REASON_DUT_UNREACHABLE_POST_PROVISION": 5,
}

func (x ProvisionFailure_Reason) String() string {
	return proto.EnumName(ProvisionFailure_Reason_name, int32(x))
}

func (ProvisionFailure_Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{4, 0}
}

// For RunTests, clients can specify both lists of suites and test cases.
// Both will be run as part of a single request.
type RunTestsRequest struct {
	// Test suites to run (by tag or explicit list of tests)
	TestSuites           []*TestSuite `protobuf:"bytes,1,rep,name=test_suites,json=testSuites,proto3" json:"test_suites,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RunTestsRequest) Reset()         { *m = RunTestsRequest{} }
func (m *RunTestsRequest) String() string { return proto.CompactTextString(m) }
func (*RunTestsRequest) ProtoMessage()    {}
func (*RunTestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{0}
}

func (m *RunTestsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTestsRequest.Unmarshal(m, b)
}
func (m *RunTestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTestsRequest.Marshal(b, m, deterministic)
}
func (m *RunTestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTestsRequest.Merge(m, src)
}
func (m *RunTestsRequest) XXX_Size() int {
	return xxx_messageInfo_RunTestsRequest.Size(m)
}
func (m *RunTestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunTestsRequest proto.InternalMessageInfo

func (m *RunTestsRequest) GetTestSuites() []*TestSuite {
	if m != nil {
		return m.TestSuites
	}
	return nil
}

type RunTestsResponse struct {
	TestCaseResults      []*TestCaseResult `protobuf:"bytes,1,rep,name=test_case_results,json=testCaseResults,proto3" json:"test_case_results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RunTestsResponse) Reset()         { *m = RunTestsResponse{} }
func (m *RunTestsResponse) String() string { return proto.CompactTextString(m) }
func (*RunTestsResponse) ProtoMessage()    {}
func (*RunTestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{1}
}

func (m *RunTestsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTestsResponse.Unmarshal(m, b)
}
func (m *RunTestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTestsResponse.Marshal(b, m, deterministic)
}
func (m *RunTestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTestsResponse.Merge(m, src)
}
func (m *RunTestsResponse) XXX_Size() int {
	return xxx_messageInfo_RunTestsResponse.Size(m)
}
func (m *RunTestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunTestsResponse proto.InternalMessageInfo

func (m *RunTestsResponse) GetTestCaseResults() []*TestCaseResult {
	if m != nil {
		return m.TestCaseResults
	}
	return nil
}

type RunTestsMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunTestsMetadata) Reset()         { *m = RunTestsMetadata{} }
func (m *RunTestsMetadata) String() string { return proto.CompactTextString(m) }
func (*RunTestsMetadata) ProtoMessage()    {}
func (*RunTestsMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{2}
}

func (m *RunTestsMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTestsMetadata.Unmarshal(m, b)
}
func (m *RunTestsMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTestsMetadata.Marshal(b, m, deterministic)
}
func (m *RunTestsMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTestsMetadata.Merge(m, src)
}
func (m *RunTestsMetadata) XXX_Size() int {
	return xxx_messageInfo_RunTestsMetadata.Size(m)
}
func (m *RunTestsMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTestsMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RunTestsMetadata proto.InternalMessageInfo

type ProvisionSuccess struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionSuccess) Reset()         { *m = ProvisionSuccess{} }
func (m *ProvisionSuccess) String() string { return proto.CompactTextString(m) }
func (*ProvisionSuccess) ProtoMessage()    {}
func (*ProvisionSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{3}
}

func (m *ProvisionSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionSuccess.Unmarshal(m, b)
}
func (m *ProvisionSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionSuccess.Marshal(b, m, deterministic)
}
func (m *ProvisionSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionSuccess.Merge(m, src)
}
func (m *ProvisionSuccess) XXX_Size() int {
	return xxx_messageInfo_ProvisionSuccess.Size(m)
}
func (m *ProvisionSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionSuccess proto.InternalMessageInfo

type ProvisionFailure struct {
	Reason               ProvisionFailure_Reason `protobuf:"varint,1,opt,name=reason,proto3,enum=chromiumos.test.api.ProvisionFailure_Reason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ProvisionFailure) Reset()         { *m = ProvisionFailure{} }
func (m *ProvisionFailure) String() string { return proto.CompactTextString(m) }
func (*ProvisionFailure) ProtoMessage()    {}
func (*ProvisionFailure) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{4}
}

func (m *ProvisionFailure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionFailure.Unmarshal(m, b)
}
func (m *ProvisionFailure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionFailure.Marshal(b, m, deterministic)
}
func (m *ProvisionFailure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionFailure.Merge(m, src)
}
func (m *ProvisionFailure) XXX_Size() int {
	return xxx_messageInfo_ProvisionFailure.Size(m)
}
func (m *ProvisionFailure) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionFailure.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionFailure proto.InternalMessageInfo

func (m *ProvisionFailure) GetReason() ProvisionFailure_Reason {
	if m != nil {
		return m.Reason
	}
	return ProvisionFailure_REASON_INVALID_REQUEST
}

type ProvisionDutRequest struct {
	CrosImagePath *_go.StoragePath `protobuf:"bytes,1,opt,name=cros_image_path,json=crosImagePath,proto3" json:"cros_image_path,omitempty"`
	// dlc_specs specifies which DLCs to install on the DUT after provisioning.
	DlcSpecs []*ProvisionDutRequest_DLCSpec `protobuf:"bytes,2,rep,name=dlc_specs,json=dlcSpecs,proto3" json:"dlc_specs,omitempty"`
	// preserve_stateful specifies whether the stateful partition should be preserved during
	// provisioning. If preserve_stateful is not set to true, the stateful partition is
	// block-level wiped and reset during provisioning.
	PreserveStateful     bool     `protobuf:"varint,3,opt,name=preserve_stateful,json=preserveStateful,proto3" json:"preserve_stateful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionDutRequest) Reset()         { *m = ProvisionDutRequest{} }
func (m *ProvisionDutRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionDutRequest) ProtoMessage()    {}
func (*ProvisionDutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{5}
}

func (m *ProvisionDutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionDutRequest.Unmarshal(m, b)
}
func (m *ProvisionDutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionDutRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionDutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionDutRequest.Merge(m, src)
}
func (m *ProvisionDutRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionDutRequest.Size(m)
}
func (m *ProvisionDutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionDutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionDutRequest proto.InternalMessageInfo

func (m *ProvisionDutRequest) GetCrosImagePath() *_go.StoragePath {
	if m != nil {
		return m.CrosImagePath
	}
	return nil
}

func (m *ProvisionDutRequest) GetDlcSpecs() []*ProvisionDutRequest_DLCSpec {
	if m != nil {
		return m.DlcSpecs
	}
	return nil
}

func (m *ProvisionDutRequest) GetPreserveStateful() bool {
	if m != nil {
		return m.PreserveStateful
	}
	return false
}

// Reference DLCs developer documentation:
// https://source.corp.google.com/chromeos_public/src/platform2/dlcservice/docs/developer.md
type ProvisionDutRequest_DLCSpec struct {
	// id is the DLC ID which is a unique identifier.
	// The DLC ID must follow a specific format that can be found in the DLC
	// developer doc below.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionDutRequest_DLCSpec) Reset()         { *m = ProvisionDutRequest_DLCSpec{} }
func (m *ProvisionDutRequest_DLCSpec) String() string { return proto.CompactTextString(m) }
func (*ProvisionDutRequest_DLCSpec) ProtoMessage()    {}
func (*ProvisionDutRequest_DLCSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{5, 0}
}

func (m *ProvisionDutRequest_DLCSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionDutRequest_DLCSpec.Unmarshal(m, b)
}
func (m *ProvisionDutRequest_DLCSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionDutRequest_DLCSpec.Marshal(b, m, deterministic)
}
func (m *ProvisionDutRequest_DLCSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionDutRequest_DLCSpec.Merge(m, src)
}
func (m *ProvisionDutRequest_DLCSpec) XXX_Size() int {
	return xxx_messageInfo_ProvisionDutRequest_DLCSpec.Size(m)
}
func (m *ProvisionDutRequest_DLCSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionDutRequest_DLCSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionDutRequest_DLCSpec proto.InternalMessageInfo

func (m *ProvisionDutRequest_DLCSpec) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProvisionDutResponse struct {
	// Types that are valid to be assigned to Outcome:
	//	*ProvisionDutResponse_Success
	//	*ProvisionDutResponse_Failure
	Outcome              isProvisionDutResponse_Outcome `protobuf_oneof:"outcome"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ProvisionDutResponse) Reset()         { *m = ProvisionDutResponse{} }
func (m *ProvisionDutResponse) String() string { return proto.CompactTextString(m) }
func (*ProvisionDutResponse) ProtoMessage()    {}
func (*ProvisionDutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{6}
}

func (m *ProvisionDutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionDutResponse.Unmarshal(m, b)
}
func (m *ProvisionDutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionDutResponse.Marshal(b, m, deterministic)
}
func (m *ProvisionDutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionDutResponse.Merge(m, src)
}
func (m *ProvisionDutResponse) XXX_Size() int {
	return xxx_messageInfo_ProvisionDutResponse.Size(m)
}
func (m *ProvisionDutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionDutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionDutResponse proto.InternalMessageInfo

type isProvisionDutResponse_Outcome interface {
	isProvisionDutResponse_Outcome()
}

type ProvisionDutResponse_Success struct {
	Success *ProvisionSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type ProvisionDutResponse_Failure struct {
	Failure *ProvisionFailure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*ProvisionDutResponse_Success) isProvisionDutResponse_Outcome() {}

func (*ProvisionDutResponse_Failure) isProvisionDutResponse_Outcome() {}

func (m *ProvisionDutResponse) GetOutcome() isProvisionDutResponse_Outcome {
	if m != nil {
		return m.Outcome
	}
	return nil
}

func (m *ProvisionDutResponse) GetSuccess() *ProvisionSuccess {
	if x, ok := m.GetOutcome().(*ProvisionDutResponse_Success); ok {
		return x.Success
	}
	return nil
}

func (m *ProvisionDutResponse) GetFailure() *ProvisionFailure {
	if x, ok := m.GetOutcome().(*ProvisionDutResponse_Failure); ok {
		return x.Failure
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProvisionDutResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProvisionDutResponse_Success)(nil),
		(*ProvisionDutResponse_Failure)(nil),
	}
}

type ProvisionDutMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionDutMetadata) Reset()         { *m = ProvisionDutMetadata{} }
func (m *ProvisionDutMetadata) String() string { return proto.CompactTextString(m) }
func (*ProvisionDutMetadata) ProtoMessage()    {}
func (*ProvisionDutMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{7}
}

func (m *ProvisionDutMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionDutMetadata.Unmarshal(m, b)
}
func (m *ProvisionDutMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionDutMetadata.Marshal(b, m, deterministic)
}
func (m *ProvisionDutMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionDutMetadata.Merge(m, src)
}
func (m *ProvisionDutMetadata) XXX_Size() int {
	return xxx_messageInfo_ProvisionDutMetadata.Size(m)
}
func (m *ProvisionDutMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionDutMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionDutMetadata proto.InternalMessageInfo

type ProvisionLacrosRequest struct {
	LacrosImagePath      *_go.StoragePath `protobuf:"bytes,1,opt,name=lacros_image_path,json=lacrosImagePath,proto3" json:"lacros_image_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProvisionLacrosRequest) Reset()         { *m = ProvisionLacrosRequest{} }
func (m *ProvisionLacrosRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionLacrosRequest) ProtoMessage()    {}
func (*ProvisionLacrosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{8}
}

func (m *ProvisionLacrosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionLacrosRequest.Unmarshal(m, b)
}
func (m *ProvisionLacrosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionLacrosRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionLacrosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionLacrosRequest.Merge(m, src)
}
func (m *ProvisionLacrosRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionLacrosRequest.Size(m)
}
func (m *ProvisionLacrosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionLacrosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionLacrosRequest proto.InternalMessageInfo

func (m *ProvisionLacrosRequest) GetLacrosImagePath() *_go.StoragePath {
	if m != nil {
		return m.LacrosImagePath
	}
	return nil
}

type ProvisionLacrosResponse struct {
	// Types that are valid to be assigned to Outcome:
	//	*ProvisionLacrosResponse_Success
	//	*ProvisionLacrosResponse_Failure
	Outcome              isProvisionLacrosResponse_Outcome `protobuf_oneof:"outcome"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ProvisionLacrosResponse) Reset()         { *m = ProvisionLacrosResponse{} }
func (m *ProvisionLacrosResponse) String() string { return proto.CompactTextString(m) }
func (*ProvisionLacrosResponse) ProtoMessage()    {}
func (*ProvisionLacrosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{9}
}

func (m *ProvisionLacrosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionLacrosResponse.Unmarshal(m, b)
}
func (m *ProvisionLacrosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionLacrosResponse.Marshal(b, m, deterministic)
}
func (m *ProvisionLacrosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionLacrosResponse.Merge(m, src)
}
func (m *ProvisionLacrosResponse) XXX_Size() int {
	return xxx_messageInfo_ProvisionLacrosResponse.Size(m)
}
func (m *ProvisionLacrosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionLacrosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionLacrosResponse proto.InternalMessageInfo

type isProvisionLacrosResponse_Outcome interface {
	isProvisionLacrosResponse_Outcome()
}

type ProvisionLacrosResponse_Success struct {
	Success *ProvisionSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type ProvisionLacrosResponse_Failure struct {
	Failure *ProvisionFailure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*ProvisionLacrosResponse_Success) isProvisionLacrosResponse_Outcome() {}

func (*ProvisionLacrosResponse_Failure) isProvisionLacrosResponse_Outcome() {}

func (m *ProvisionLacrosResponse) GetOutcome() isProvisionLacrosResponse_Outcome {
	if m != nil {
		return m.Outcome
	}
	return nil
}

func (m *ProvisionLacrosResponse) GetSuccess() *ProvisionSuccess {
	if x, ok := m.GetOutcome().(*ProvisionLacrosResponse_Success); ok {
		return x.Success
	}
	return nil
}

func (m *ProvisionLacrosResponse) GetFailure() *ProvisionFailure {
	if x, ok := m.GetOutcome().(*ProvisionLacrosResponse_Failure); ok {
		return x.Failure
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProvisionLacrosResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProvisionLacrosResponse_Success)(nil),
		(*ProvisionLacrosResponse_Failure)(nil),
	}
}

type ProvisionLacrosMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionLacrosMetadata) Reset()         { *m = ProvisionLacrosMetadata{} }
func (m *ProvisionLacrosMetadata) String() string { return proto.CompactTextString(m) }
func (*ProvisionLacrosMetadata) ProtoMessage()    {}
func (*ProvisionLacrosMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{10}
}

func (m *ProvisionLacrosMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionLacrosMetadata.Unmarshal(m, b)
}
func (m *ProvisionLacrosMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionLacrosMetadata.Marshal(b, m, deterministic)
}
func (m *ProvisionLacrosMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionLacrosMetadata.Merge(m, src)
}
func (m *ProvisionLacrosMetadata) XXX_Size() int {
	return xxx_messageInfo_ProvisionLacrosMetadata.Size(m)
}
func (m *ProvisionLacrosMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionLacrosMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionLacrosMetadata proto.InternalMessageInfo

type ProvisionAshRequest struct {
	AshImagePath         *_go.StoragePath `protobuf:"bytes,1,opt,name=ash_image_path,json=ashImagePath,proto3" json:"ash_image_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProvisionAshRequest) Reset()         { *m = ProvisionAshRequest{} }
func (m *ProvisionAshRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionAshRequest) ProtoMessage()    {}
func (*ProvisionAshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{11}
}

func (m *ProvisionAshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionAshRequest.Unmarshal(m, b)
}
func (m *ProvisionAshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionAshRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionAshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionAshRequest.Merge(m, src)
}
func (m *ProvisionAshRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionAshRequest.Size(m)
}
func (m *ProvisionAshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionAshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionAshRequest proto.InternalMessageInfo

func (m *ProvisionAshRequest) GetAshImagePath() *_go.StoragePath {
	if m != nil {
		return m.AshImagePath
	}
	return nil
}

type ProvisionAshResponse struct {
	// Types that are valid to be assigned to Outcome:
	//	*ProvisionAshResponse_Success
	//	*ProvisionAshResponse_Failure
	Outcome              isProvisionAshResponse_Outcome `protobuf_oneof:"outcome"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ProvisionAshResponse) Reset()         { *m = ProvisionAshResponse{} }
func (m *ProvisionAshResponse) String() string { return proto.CompactTextString(m) }
func (*ProvisionAshResponse) ProtoMessage()    {}
func (*ProvisionAshResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{12}
}

func (m *ProvisionAshResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionAshResponse.Unmarshal(m, b)
}
func (m *ProvisionAshResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionAshResponse.Marshal(b, m, deterministic)
}
func (m *ProvisionAshResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionAshResponse.Merge(m, src)
}
func (m *ProvisionAshResponse) XXX_Size() int {
	return xxx_messageInfo_ProvisionAshResponse.Size(m)
}
func (m *ProvisionAshResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionAshResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionAshResponse proto.InternalMessageInfo

type isProvisionAshResponse_Outcome interface {
	isProvisionAshResponse_Outcome()
}

type ProvisionAshResponse_Success struct {
	Success *ProvisionSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type ProvisionAshResponse_Failure struct {
	Failure *ProvisionFailure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*ProvisionAshResponse_Success) isProvisionAshResponse_Outcome() {}

func (*ProvisionAshResponse_Failure) isProvisionAshResponse_Outcome() {}

func (m *ProvisionAshResponse) GetOutcome() isProvisionAshResponse_Outcome {
	if m != nil {
		return m.Outcome
	}
	return nil
}

func (m *ProvisionAshResponse) GetSuccess() *ProvisionSuccess {
	if x, ok := m.GetOutcome().(*ProvisionAshResponse_Success); ok {
		return x.Success
	}
	return nil
}

func (m *ProvisionAshResponse) GetFailure() *ProvisionFailure {
	if x, ok := m.GetOutcome().(*ProvisionAshResponse_Failure); ok {
		return x.Failure
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProvisionAshResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProvisionAshResponse_Success)(nil),
		(*ProvisionAshResponse_Failure)(nil),
	}
}

type ProvisionAshMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionAshMetadata) Reset()         { *m = ProvisionAshMetadata{} }
func (m *ProvisionAshMetadata) String() string { return proto.CompactTextString(m) }
func (*ProvisionAshMetadata) ProtoMessage()    {}
func (*ProvisionAshMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{13}
}

func (m *ProvisionAshMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionAshMetadata.Unmarshal(m, b)
}
func (m *ProvisionAshMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionAshMetadata.Marshal(b, m, deterministic)
}
func (m *ProvisionAshMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionAshMetadata.Merge(m, src)
}
func (m *ProvisionAshMetadata) XXX_Size() int {
	return xxx_messageInfo_ProvisionAshMetadata.Size(m)
}
func (m *ProvisionAshMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionAshMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionAshMetadata proto.InternalMessageInfo

type ProvisionArcRequest struct {
	AshImagePath         *_go.StoragePath `protobuf:"bytes,1,opt,name=ash_image_path,json=ashImagePath,proto3" json:"ash_image_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProvisionArcRequest) Reset()         { *m = ProvisionArcRequest{} }
func (m *ProvisionArcRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionArcRequest) ProtoMessage()    {}
func (*ProvisionArcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{14}
}

func (m *ProvisionArcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionArcRequest.Unmarshal(m, b)
}
func (m *ProvisionArcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionArcRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionArcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionArcRequest.Merge(m, src)
}
func (m *ProvisionArcRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionArcRequest.Size(m)
}
func (m *ProvisionArcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionArcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionArcRequest proto.InternalMessageInfo

func (m *ProvisionArcRequest) GetAshImagePath() *_go.StoragePath {
	if m != nil {
		return m.AshImagePath
	}
	return nil
}

type ProvisionArcResponse struct {
	// Types that are valid to be assigned to Outcome:
	//	*ProvisionArcResponse_Success
	//	*ProvisionArcResponse_Failure
	Outcome              isProvisionArcResponse_Outcome `protobuf_oneof:"outcome"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ProvisionArcResponse) Reset()         { *m = ProvisionArcResponse{} }
func (m *ProvisionArcResponse) String() string { return proto.CompactTextString(m) }
func (*ProvisionArcResponse) ProtoMessage()    {}
func (*ProvisionArcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{15}
}

func (m *ProvisionArcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionArcResponse.Unmarshal(m, b)
}
func (m *ProvisionArcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionArcResponse.Marshal(b, m, deterministic)
}
func (m *ProvisionArcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionArcResponse.Merge(m, src)
}
func (m *ProvisionArcResponse) XXX_Size() int {
	return xxx_messageInfo_ProvisionArcResponse.Size(m)
}
func (m *ProvisionArcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionArcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionArcResponse proto.InternalMessageInfo

type isProvisionArcResponse_Outcome interface {
	isProvisionArcResponse_Outcome()
}

type ProvisionArcResponse_Success struct {
	Success *ProvisionSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type ProvisionArcResponse_Failure struct {
	Failure *ProvisionFailure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*ProvisionArcResponse_Success) isProvisionArcResponse_Outcome() {}

func (*ProvisionArcResponse_Failure) isProvisionArcResponse_Outcome() {}

func (m *ProvisionArcResponse) GetOutcome() isProvisionArcResponse_Outcome {
	if m != nil {
		return m.Outcome
	}
	return nil
}

func (m *ProvisionArcResponse) GetSuccess() *ProvisionSuccess {
	if x, ok := m.GetOutcome().(*ProvisionArcResponse_Success); ok {
		return x.Success
	}
	return nil
}

func (m *ProvisionArcResponse) GetFailure() *ProvisionFailure {
	if x, ok := m.GetOutcome().(*ProvisionArcResponse_Failure); ok {
		return x.Failure
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProvisionArcResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProvisionArcResponse_Success)(nil),
		(*ProvisionArcResponse_Failure)(nil),
	}
}

type ProvisionArcMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionArcMetadata) Reset()         { *m = ProvisionArcMetadata{} }
func (m *ProvisionArcMetadata) String() string { return proto.CompactTextString(m) }
func (*ProvisionArcMetadata) ProtoMessage()    {}
func (*ProvisionArcMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{16}
}

func (m *ProvisionArcMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionArcMetadata.Unmarshal(m, b)
}
func (m *ProvisionArcMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionArcMetadata.Marshal(b, m, deterministic)
}
func (m *ProvisionArcMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionArcMetadata.Merge(m, src)
}
func (m *ProvisionArcMetadata) XXX_Size() int {
	return xxx_messageInfo_ProvisionArcMetadata.Size(m)
}
func (m *ProvisionArcMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionArcMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionArcMetadata proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("chromiumos.test.api.ProvisionFailure_Reason", ProvisionFailure_Reason_name, ProvisionFailure_Reason_value)
	proto.RegisterType((*RunTestsRequest)(nil), "chromiumos.test.api.RunTestsRequest")
	proto.RegisterType((*RunTestsResponse)(nil), "chromiumos.test.api.RunTestsResponse")
	proto.RegisterType((*RunTestsMetadata)(nil), "chromiumos.test.api.RunTestsMetadata")
	proto.RegisterType((*ProvisionSuccess)(nil), "chromiumos.test.api.ProvisionSuccess")
	proto.RegisterType((*ProvisionFailure)(nil), "chromiumos.test.api.ProvisionFailure")
	proto.RegisterType((*ProvisionDutRequest)(nil), "chromiumos.test.api.ProvisionDutRequest")
	proto.RegisterType((*ProvisionDutRequest_DLCSpec)(nil), "chromiumos.test.api.ProvisionDutRequest.DLCSpec")
	proto.RegisterType((*ProvisionDutResponse)(nil), "chromiumos.test.api.ProvisionDutResponse")
	proto.RegisterType((*ProvisionDutMetadata)(nil), "chromiumos.test.api.ProvisionDutMetadata")
	proto.RegisterType((*ProvisionLacrosRequest)(nil), "chromiumos.test.api.ProvisionLacrosRequest")
	proto.RegisterType((*ProvisionLacrosResponse)(nil), "chromiumos.test.api.ProvisionLacrosResponse")
	proto.RegisterType((*ProvisionLacrosMetadata)(nil), "chromiumos.test.api.ProvisionLacrosMetadata")
	proto.RegisterType((*ProvisionAshRequest)(nil), "chromiumos.test.api.ProvisionAshRequest")
	proto.RegisterType((*ProvisionAshResponse)(nil), "chromiumos.test.api.ProvisionAshResponse")
	proto.RegisterType((*ProvisionAshMetadata)(nil), "chromiumos.test.api.ProvisionAshMetadata")
	proto.RegisterType((*ProvisionArcRequest)(nil), "chromiumos.test.api.ProvisionArcRequest")
	proto.RegisterType((*ProvisionArcResponse)(nil), "chromiumos.test.api.ProvisionArcResponse")
	proto.RegisterType((*ProvisionArcMetadata)(nil), "chromiumos.test.api.ProvisionArcMetadata")
}

func init() {
	proto.RegisterFile("chromiumos/test/api/test_service.proto", fileDescriptor_467512ed519718ce)
}

var fileDescriptor_467512ed519718ce = []byte{
	// 857 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x6d, 0x8e, 0xdb, 0x44,
	0x18, 0xae, 0xb3, 0xed, 0x7e, 0xcc, 0x96, 0x4d, 0x76, 0x8a, 0xb6, 0x69, 0x04, 0x65, 0x71, 0x53,
	0x1a, 0x68, 0x71, 0x50, 0x10, 0x3f, 0x11, 0xf2, 0xc6, 0x6e, 0x6b, 0x94, 0xc4, 0xcb, 0x38, 0x29,
	0x08, 0x09, 0x59, 0xc3, 0x64, 0x36, 0xb6, 0x94, 0x78, 0xcc, 0xcc, 0xb8, 0xbf, 0x38, 0x02, 0x07,
	0xe0, 0x06, 0x48, 0x5c, 0x81, 0x5b, 0x2c, 0x17, 0xe0, 0x02, 0xdc, 0x01, 0xd9, 0xf1, 0x57, 0xb2,
	0xce, 0x36, 0xad, 0x84, 0xd4, 0xfe, 0xb0, 0x34, 0x9e, 0x79, 0xde, 0x77, 0x1e, 0x3f, 0xf3, 0xbc,
	0xe3, 0x17, 0x7c, 0x42, 0x3c, 0xce, 0x16, 0x7e, 0xb4, 0x60, 0xa2, 0x2b, 0xa9, 0x90, 0x5d, 0x1c,
	0xfa, 0xc9, 0xc0, 0x15, 0x94, 0xbf, 0xf4, 0x09, 0xd5, 0x42, 0xce, 0x24, 0x83, 0x77, 0x0a, 0x9c,
	0x16, 0x2f, 0x6b, 0x38, 0xf4, 0x5b, 0x8f, 0x4a, 0xc1, 0x73, 0x16, 0xcc, 0x78, 0x14, 0x04, 0x7e,
	0x30, 0xeb, 0xb2, 0x90, 0x72, 0x2c, 0x7d, 0x16, 0x88, 0x65, 0x74, 0xeb, 0xc3, 0x12, 0x50, 0x48,
	0xc6, 0xf1, 0x8c, 0xba, 0x21, 0x96, 0x5e, 0xba, 0xfc, 0xd9, 0x46, 0x12, 0x04, 0x0b, 0xea, 0x72,
	0x2a, 0xa2, 0xb9, 0x4c, 0xb1, 0xed, 0xcd, 0x84, 0x23, 0x5f, 0xa6, 0x74, 0xd5, 0x1f, 0x40, 0x1d,
	0x45, 0xc1, 0x98, 0x0a, 0x29, 0x10, 0xfd, 0x25, 0xa2, 0x42, 0xc2, 0x6f, 0xc0, 0x61, 0x01, 0x13,
	0x4d, 0xe5, 0x74, 0xa7, 0x73, 0xd8, 0xbb, 0xaf, 0x55, 0x7c, 0x97, 0x16, 0xc7, 0x39, 0x31, 0x0c,
	0x01, 0x99, 0x0d, 0xc5, 0xb7, 0x37, 0xf7, 0x6b, 0x8d, 0x1d, 0x95, 0x80, 0x46, 0x91, 0x59, 0x84,
	0x2c, 0x10, 0x14, 0xda, 0xe0, 0x78, 0x9d, 0x6d, 0xb6, 0xc1, 0x83, 0x8d, 0x1b, 0xf4, 0xb1, 0xa0,
	0x28, 0xc1, 0xa2, 0xba, 0x5c, 0x79, 0x17, 0x2a, 0x2c, 0x36, 0x19, 0x52, 0x89, 0xa7, 0x58, 0xe2,
	0x78, 0xee, 0x9c, 0xb3, 0x97, 0xbe, 0xf0, 0x59, 0xe0, 0x44, 0x84, 0x50, 0x21, 0xd4, 0xbf, 0x6a,
	0xa5, 0xc9, 0xa7, 0xd8, 0x9f, 0x47, 0x9c, 0x42, 0x03, 0xec, 0x72, 0x8a, 0x05, 0x0b, 0x9a, 0xca,
	0xa9, 0xd2, 0x39, 0xea, 0x3d, 0xa9, 0xa4, 0xb0, 0x1e, 0xa6, 0xa1, 0x24, 0x06, 0xa5, 0xb1, 0xea,
	0x3f, 0x0a, 0xd8, 0x5d, 0x4e, 0xc1, 0x16, 0x38, 0x41, 0xa6, 0xee, 0xd8, 0x23, 0xd7, 0x1a, 0xbd,
	0xd0, 0x07, 0x96, 0xe1, 0x22, 0xf3, 0xbb, 0x89, 0xe9, 0x8c, 0x1b, 0x37, 0x60, 0x07, 0xb4, 0xd3,
	0x35, 0x63, 0x32, 0x76, 0x27, 0x23, 0x64, 0xea, 0xfd, 0xe7, 0xfa, 0xd9, 0xc0, 0x74, 0xcf, 0x51,
	0xfc, 0xd8, 0x2f, 0x2c, 0xc7, 0xb2, 0x47, 0x0d, 0x05, 0x3e, 0x00, 0x1f, 0x65, 0x48, 0xfb, 0xfb,
	0xd1, 0xc0, 0xd6, 0x0d, 0x6b, 0xf4, 0xcc, 0xb5, 0x86, 0xfa, 0x33, 0xd3, 0x7d, 0xaa, 0x5b, 0x03,
	0xd3, 0x68, 0xd4, 0xe0, 0x29, 0xf8, 0x20, 0x05, 0xe5, 0xa1, 0x31, 0x6a, 0x6c, 0x0d, 0x4d, 0xc3,
	0x9e, 0x8c, 0x1b, 0x3b, 0xf0, 0x3e, 0x68, 0x55, 0x21, 0xd2, 0x0c, 0x37, 0xe1, 0xa7, 0xe0, 0xe1,
	0x26, 0x42, 0xb6, 0x33, 0x2e, 0x31, 0xba, 0xa5, 0xfe, 0xab, 0x80, 0x3b, 0xb9, 0x0c, 0x46, 0x24,
	0x0b, 0xa7, 0xd4, 0x09, 0x67, 0xc2, 0xf5, 0x17, 0x99, 0x4f, 0x13, 0x25, 0x0f, 0x7b, 0x77, 0xcb,
	0x4a, 0x3a, 0x4b, 0x1f, 0x9f, 0x63, 0xe9, 0xa1, 0xf7, 0x62, 0xbc, 0xb5, 0x48, 0x5f, 0xe1, 0x10,
	0x1c, 0x4c, 0xe7, 0xc4, 0x15, 0x21, 0x25, 0xa2, 0x59, 0x4b, 0x7c, 0xf0, 0xc5, 0xf5, 0x87, 0x50,
	0xec, 0xae, 0x19, 0x83, 0xbe, 0x13, 0x52, 0x82, 0xf6, 0xa7, 0x73, 0x12, 0x0f, 0x04, 0x7c, 0x0c,
	0x8e, 0x43, 0x4e, 0xe3, 0x7a, 0xa4, 0xae, 0x90, 0x58, 0xd2, 0x8b, 0x68, 0xde, 0xdc, 0x39, 0x55,
	0x3a, 0xfb, 0xa8, 0x91, 0x2d, 0x38, 0xe9, 0x7c, 0xeb, 0x1e, 0xd8, 0x4b, 0x33, 0xc0, 0x23, 0x50,
	0xf3, 0xa7, 0x09, 0xf5, 0x03, 0x54, 0xf3, 0xa7, 0xea, 0x1f, 0x0a, 0x78, 0x7f, 0x75, 0xc7, 0xd4,
	0xbf, 0x3a, 0xd8, 0x13, 0x4b, 0x47, 0xa5, 0x1f, 0xfa, 0xf0, 0x7a, 0xb6, 0xa9, 0xfd, 0x9e, 0xdf,
	0x40, 0x59, 0x5c, 0x9c, 0xe2, 0x62, 0x69, 0xa4, 0x66, 0x6d, 0x9b, 0x14, 0xa9, 0xeb, 0xe2, 0x14,
	0x69, 0xdc, 0xd9, 0x01, 0xd8, 0x63, 0x91, 0x24, 0x6c, 0x41, 0xd5, 0x93, 0x55, 0xa2, 0x79, 0x0d,
	0xfc, 0x04, 0x4e, 0xf2, 0xf9, 0x01, 0x8e, 0x45, 0xcf, 0xce, 0xac, 0x0f, 0x8e, 0xe7, 0xf8, 0x35,
	0x4f, 0xad, 0xbe, 0x8c, 0xc8, 0xcf, 0x4d, 0xfd, 0x53, 0x01, 0x77, 0xaf, 0xe4, 0x7f, 0x5b, 0x35,
	0xba, 0x77, 0x85, 0x6b, 0x2e, 0xd3, 0xb8, 0xe4, 0x6b, 0x5d, 0x78, 0x99, 0x46, 0x5f, 0x83, 0x23,
	0x2c, 0xbc, 0xd7, 0x10, 0xe8, 0x36, 0x16, 0x5e, 0xa1, 0xce, 0x8a, 0x7d, 0x92, 0xb4, 0xef, 0x82,
	0x7d, 0x74, 0xe1, 0x55, 0xeb, 0xc2, 0xc9, 0xff, 0xa2, 0x4b, 0x9c, 0xf6, 0x9d, 0xd0, 0x85, 0x93,
	0x4c, 0x97, 0xde, 0xdf, 0xb7, 0xc0, 0x61, 0xf2, 0xcf, 0x5b, 0xfe, 0xf2, 0xe1, 0x6f, 0x0a, 0xb8,
	0x5d, 0xae, 0x3f, 0xd8, 0xd9, 0xf6, 0xf6, 0x6a, 0x7d, 0x5c, 0x46, 0x96, 0x7a, 0x02, 0xcd, 0xce,
	0x7a, 0x02, 0xb5, 0x7b, 0xa9, 0x3f, 0xd9, 0x70, 0x11, 0x55, 0x56, 0x3d, 0xfc, 0x5d, 0x01, 0xf5,
	0x35, 0xab, 0xc3, 0xc7, 0xd7, 0x33, 0x5a, 0xb9, 0x1c, 0xb6, 0x21, 0xf5, 0xd5, 0xa5, 0xde, 0xdb,
	0x5c, 0xfc, 0x9b, 0x2a, 0x6d, 0x55, 0x29, 0x5d, 0x78, 0xaf, 0x52, 0xaa, 0xa8, 0xc6, 0x37, 0x50,
	0xaa, 0x5c, 0x73, 0x95, 0x06, 0x5f, 0xa3, 0xc3, 0xc9, 0x2b, 0xe9, 0xe4, 0x45, 0xf0, 0x26, 0x74,
	0x4a, 0x56, 0xaf, 0xf4, 0x15, 0xfc, 0x15, 0xec, 0x67, 0x6d, 0x0c, 0x6c, 0x57, 0x32, 0x59, 0x6b,
	0xd2, 0xb6, 0x61, 0xf1, 0xe8, 0x52, 0x6f, 0x57, 0xf4, 0x60, 0x57, 0x1a, 0xa6, 0xb3, 0xee, 0x8f,
	0x9f, 0xcf, 0x58, 0x9e, 0x4f, 0x63, 0x7c, 0xd6, 0x2d, 0xf5, 0x8e, 0x84, 0x05, 0x17, 0xfe, 0xac,
	0x3b, 0x63, 0x79, 0x17, 0xf9, 0xf3, 0x6e, 0xd2, 0x3b, 0x7e, 0xf9, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x40, 0x45, 0x76, 0x97, 0x14, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestServiceClient interface {
	// ProvisionDut installs a specified version of Chrome OS on the DUT, along
	// with any specified DLCs.
	//
	// If the DUT is already on the specified version of Chrome OS, the OS will
	// not be provisioned.
	//
	// If the DUT already has the specified list of DLCs, only the missing DLCs
	// will be provisioned.
	ProvisionDut(ctx context.Context, in *ProvisionDutRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// ProvisionLacros installs a specified version of Lacros on the DUT.
	//
	// If the DUT already has the specified version of Lacros, Lacros will not be
	// provisioned.
	ProvisionLacros(ctx context.Context, in *ProvisionLacrosRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// ProvisionAsh installs a specified version of ash-chrome on the DUT.
	//
	// This directly overwrites the version of ash-chrome on the current root
	// disk partition.
	ProvisionAsh(ctx context.Context, in *ProvisionAshRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// ProvisionArc installs a specified version of ARC on the DUT.
	//
	// This directly overwrites the version of ARC on the current root
	// disk partition.
	ProvisionArc(ctx context.Context, in *ProvisionArcRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// RunTests runs the requested tests.
	RunTests(ctx context.Context, in *RunTestsRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
}

type testServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestServiceClient(cc *grpc.ClientConn) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) ProvisionDut(ctx context.Context, in *ProvisionDutRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/chromiumos.test.api.TestService/ProvisionDut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) ProvisionLacros(ctx context.Context, in *ProvisionLacrosRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/chromiumos.test.api.TestService/ProvisionLacros", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) ProvisionAsh(ctx context.Context, in *ProvisionAshRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/chromiumos.test.api.TestService/ProvisionAsh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) ProvisionArc(ctx context.Context, in *ProvisionArcRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/chromiumos.test.api.TestService/ProvisionArc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) RunTests(ctx context.Context, in *RunTestsRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/chromiumos.test.api.TestService/RunTests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
type TestServiceServer interface {
	// ProvisionDut installs a specified version of Chrome OS on the DUT, along
	// with any specified DLCs.
	//
	// If the DUT is already on the specified version of Chrome OS, the OS will
	// not be provisioned.
	//
	// If the DUT already has the specified list of DLCs, only the missing DLCs
	// will be provisioned.
	ProvisionDut(context.Context, *ProvisionDutRequest) (*longrunning.Operation, error)
	// ProvisionLacros installs a specified version of Lacros on the DUT.
	//
	// If the DUT already has the specified version of Lacros, Lacros will not be
	// provisioned.
	ProvisionLacros(context.Context, *ProvisionLacrosRequest) (*longrunning.Operation, error)
	// ProvisionAsh installs a specified version of ash-chrome on the DUT.
	//
	// This directly overwrites the version of ash-chrome on the current root
	// disk partition.
	ProvisionAsh(context.Context, *ProvisionAshRequest) (*longrunning.Operation, error)
	// ProvisionArc installs a specified version of ARC on the DUT.
	//
	// This directly overwrites the version of ARC on the current root
	// disk partition.
	ProvisionArc(context.Context, *ProvisionArcRequest) (*longrunning.Operation, error)
	// RunTests runs the requested tests.
	RunTests(context.Context, *RunTestsRequest) (*longrunning.Operation, error)
}

// UnimplementedTestServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (*UnimplementedTestServiceServer) ProvisionDut(ctx context.Context, req *ProvisionDutRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionDut not implemented")
}
func (*UnimplementedTestServiceServer) ProvisionLacros(ctx context.Context, req *ProvisionLacrosRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionLacros not implemented")
}
func (*UnimplementedTestServiceServer) ProvisionAsh(ctx context.Context, req *ProvisionAshRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionAsh not implemented")
}
func (*UnimplementedTestServiceServer) ProvisionArc(ctx context.Context, req *ProvisionArcRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionArc not implemented")
}
func (*UnimplementedTestServiceServer) RunTests(ctx context.Context, req *RunTestsRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunTests not implemented")
}

func RegisterTestServiceServer(s *grpc.Server, srv TestServiceServer) {
	s.RegisterService(&_TestService_serviceDesc, srv)
}

func _TestService_ProvisionDut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionDutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).ProvisionDut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromiumos.test.api.TestService/ProvisionDut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).ProvisionDut(ctx, req.(*ProvisionDutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_ProvisionLacros_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionLacrosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).ProvisionLacros(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromiumos.test.api.TestService/ProvisionLacros",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).ProvisionLacros(ctx, req.(*ProvisionLacrosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_ProvisionAsh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionAshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).ProvisionAsh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromiumos.test.api.TestService/ProvisionAsh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).ProvisionAsh(ctx, req.(*ProvisionAshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_ProvisionArc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionArcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).ProvisionArc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromiumos.test.api.TestService/ProvisionArc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).ProvisionArc(ctx, req.(*ProvisionArcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_RunTests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).RunTests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromiumos.test.api.TestService/RunTests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).RunTests(ctx, req.(*RunTestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chromiumos.test.api.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProvisionDut",
			Handler:    _TestService_ProvisionDut_Handler,
		},
		{
			MethodName: "ProvisionLacros",
			Handler:    _TestService_ProvisionLacros_Handler,
		},
		{
			MethodName: "ProvisionAsh",
			Handler:    _TestService_ProvisionAsh_Handler,
		},
		{
			MethodName: "ProvisionArc",
			Handler:    _TestService_ProvisionArc_Handler,
		},
		{
			MethodName: "RunTests",
			Handler:    _TestService_RunTests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chromiumos/test/api/test_service.proto",
}
