// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/test/api/test_case.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Defines an atomic unit of test work that's independently executable.
//
// Test cases are the atomic building blocks used to define/generate test plans
// and then ultimately scheduling units of work (batched or independent).
//
// Test case definitions can come from any execution workflow/environment.
// E.g. Automated test cases will generally be defined/reported by the
//      various test-drivers (e.g. Tast/Tauto/...) at build time.
//
//      Manual test cases will be defined/managed directly in starlark config
//      and then act as the building blocks for manual test planning/scheduling.
//
// Test cases also are the atom at which test results can be reported.
type TestCase struct {
	// Globally unique (for ChromeOS) string id for a given test case.
	Id *TestCase_Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human friendly name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Tags associated with a given test case, which drive scheduling logic
	// based on tag inclusion or exclusion criteria.
	Tags []*TestCase_Tag `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	// Dependencies for a given test cases, which drive scheduling logic for
	// dut matching.
	Dependencies         []*TestCase_Dependency `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TestCase) Reset()         { *m = TestCase{} }
func (m *TestCase) String() string { return proto.CompactTextString(m) }
func (*TestCase) ProtoMessage()    {}
func (*TestCase) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e8ddb20e5ff9038, []int{0}
}

func (m *TestCase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCase.Unmarshal(m, b)
}
func (m *TestCase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCase.Marshal(b, m, deterministic)
}
func (m *TestCase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCase.Merge(m, src)
}
func (m *TestCase) XXX_Size() int {
	return xxx_messageInfo_TestCase.Size(m)
}
func (m *TestCase) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCase.DiscardUnknown(m)
}

var xxx_messageInfo_TestCase proto.InternalMessageInfo

func (m *TestCase) GetId() *TestCase_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TestCase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestCase) GetTags() []*TestCase_Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *TestCase) GetDependencies() []*TestCase_Dependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type TestCase_Id struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestCase_Id) Reset()         { *m = TestCase_Id{} }
func (m *TestCase_Id) String() string { return proto.CompactTextString(m) }
func (*TestCase_Id) ProtoMessage()    {}
func (*TestCase_Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e8ddb20e5ff9038, []int{0, 0}
}

func (m *TestCase_Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCase_Id.Unmarshal(m, b)
}
func (m *TestCase_Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCase_Id.Marshal(b, m, deterministic)
}
func (m *TestCase_Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCase_Id.Merge(m, src)
}
func (m *TestCase_Id) XXX_Size() int {
	return xxx_messageInfo_TestCase_Id.Size(m)
}
func (m *TestCase_Id) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCase_Id.DiscardUnknown(m)
}

var xxx_messageInfo_TestCase_Id proto.InternalMessageInfo

func (m *TestCase_Id) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TestCase_Tag struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestCase_Tag) Reset()         { *m = TestCase_Tag{} }
func (m *TestCase_Tag) String() string { return proto.CompactTextString(m) }
func (*TestCase_Tag) ProtoMessage()    {}
func (*TestCase_Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e8ddb20e5ff9038, []int{0, 1}
}

func (m *TestCase_Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCase_Tag.Unmarshal(m, b)
}
func (m *TestCase_Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCase_Tag.Marshal(b, m, deterministic)
}
func (m *TestCase_Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCase_Tag.Merge(m, src)
}
func (m *TestCase_Tag) XXX_Size() int {
	return xxx_messageInfo_TestCase_Tag.Size(m)
}
func (m *TestCase_Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCase_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_TestCase_Tag proto.InternalMessageInfo

func (m *TestCase_Tag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TestCase_Dependency struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestCase_Dependency) Reset()         { *m = TestCase_Dependency{} }
func (m *TestCase_Dependency) String() string { return proto.CompactTextString(m) }
func (*TestCase_Dependency) ProtoMessage()    {}
func (*TestCase_Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e8ddb20e5ff9038, []int{0, 2}
}

func (m *TestCase_Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCase_Dependency.Unmarshal(m, b)
}
func (m *TestCase_Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCase_Dependency.Marshal(b, m, deterministic)
}
func (m *TestCase_Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCase_Dependency.Merge(m, src)
}
func (m *TestCase_Dependency) XXX_Size() int {
	return xxx_messageInfo_TestCase_Dependency.Size(m)
}
func (m *TestCase_Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCase_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_TestCase_Dependency proto.InternalMessageInfo

func (m *TestCase_Dependency) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// List of globally unique test case identifiers
type TestCaseIdList struct {
	TestCaseIds          []*TestCase_Id `protobuf:"bytes,1,rep,name=test_case_ids,json=testCaseIds,proto3" json:"test_case_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TestCaseIdList) Reset()         { *m = TestCaseIdList{} }
func (m *TestCaseIdList) String() string { return proto.CompactTextString(m) }
func (*TestCaseIdList) ProtoMessage()    {}
func (*TestCaseIdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e8ddb20e5ff9038, []int{1}
}

func (m *TestCaseIdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCaseIdList.Unmarshal(m, b)
}
func (m *TestCaseIdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCaseIdList.Marshal(b, m, deterministic)
}
func (m *TestCaseIdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCaseIdList.Merge(m, src)
}
func (m *TestCaseIdList) XXX_Size() int {
	return xxx_messageInfo_TestCaseIdList.Size(m)
}
func (m *TestCaseIdList) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCaseIdList.DiscardUnknown(m)
}

var xxx_messageInfo_TestCaseIdList proto.InternalMessageInfo

func (m *TestCaseIdList) GetTestCaseIds() []*TestCase_Id {
	if m != nil {
		return m.TestCaseIds
	}
	return nil
}

type TestCaseList struct {
	TestCases            []*TestCase `protobuf:"bytes,1,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TestCaseList) Reset()         { *m = TestCaseList{} }
func (m *TestCaseList) String() string { return proto.CompactTextString(m) }
func (*TestCaseList) ProtoMessage()    {}
func (*TestCaseList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e8ddb20e5ff9038, []int{2}
}

func (m *TestCaseList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCaseList.Unmarshal(m, b)
}
func (m *TestCaseList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCaseList.Marshal(b, m, deterministic)
}
func (m *TestCaseList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCaseList.Merge(m, src)
}
func (m *TestCaseList) XXX_Size() int {
	return xxx_messageInfo_TestCaseList.Size(m)
}
func (m *TestCaseList) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCaseList.DiscardUnknown(m)
}

var xxx_messageInfo_TestCaseList proto.InternalMessageInfo

func (m *TestCaseList) GetTestCases() []*TestCase {
	if m != nil {
		return m.TestCases
	}
	return nil
}

func init() {
	proto.RegisterType((*TestCase)(nil), "chromiumos.test.api.TestCase")
	proto.RegisterType((*TestCase_Id)(nil), "chromiumos.test.api.TestCase.Id")
	proto.RegisterType((*TestCase_Tag)(nil), "chromiumos.test.api.TestCase.Tag")
	proto.RegisterType((*TestCase_Dependency)(nil), "chromiumos.test.api.TestCase.Dependency")
	proto.RegisterType((*TestCaseIdList)(nil), "chromiumos.test.api.TestCaseIdList")
	proto.RegisterType((*TestCaseList)(nil), "chromiumos.test.api.TestCaseList")
}

func init() {
	proto.RegisterFile("chromiumos/test/api/test_case.proto", fileDescriptor_2e8ddb20e5ff9038)
}

var fileDescriptor_2e8ddb20e5ff9038 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0x87, 0xe9, 0x1f, 0xc5, 0x4e, 0x57, 0x0f, 0xd1, 0x43, 0xa9, 0x08, 0xb5, 0x5e, 0x7a, 0x31,
	0x95, 0x15, 0x6f, 0x9e, 0x74, 0x2f, 0x85, 0x9e, 0x42, 0xf1, 0xe0, 0x65, 0x89, 0x4d, 0x8c, 0x01,
	0xdb, 0x94, 0x26, 0x2b, 0xf8, 0x5a, 0x3e, 0xa1, 0x18, 0x49, 0x57, 0x61, 0xad, 0xb7, 0x09, 0xf3,
	0xfd, 0x3e, 0x26, 0xc3, 0xc0, 0x45, 0xfb, 0x32, 0xaa, 0x4e, 0x6e, 0x3a, 0xa5, 0x4b, 0xc3, 0xb5,
	0x29, 0xe9, 0x20, 0x6d, 0xb1, 0x6e, 0xa9, 0xe6, 0x78, 0x18, 0x95, 0x51, 0xe8, 0x78, 0x0b, 0xe1,
	0xaf, 0x1e, 0xa6, 0x83, 0xcc, 0x3f, 0x7c, 0x38, 0x68, 0xb8, 0x36, 0xf7, 0x54, 0x73, 0x74, 0x05,
	0xbe, 0x64, 0x89, 0x97, 0x79, 0x45, 0xbc, 0xcc, 0xf0, 0x0e, 0x1c, 0x3b, 0x14, 0x57, 0x8c, 0xf8,
	0x92, 0x21, 0x04, 0x61, 0x4f, 0x3b, 0x9e, 0xf8, 0x99, 0x57, 0x44, 0xc4, 0xd6, 0xe8, 0x06, 0x42,
	0x43, 0x85, 0x4e, 0x82, 0x2c, 0x28, 0xe2, 0xe5, 0xf9, 0xbc, 0xa7, 0xa1, 0x82, 0x58, 0x1c, 0xd5,
	0xb0, 0x60, 0x7c, 0xe0, 0x3d, 0xe3, 0x7d, 0x2b, 0xb9, 0x4e, 0x42, 0x1b, 0x2f, 0xe6, 0xe3, 0x2b,
	0x97, 0x78, 0x27, 0xbf, 0xd2, 0x69, 0x0a, 0x7e, 0xc5, 0xd0, 0x09, 0xec, 0xbd, 0xd1, 0xd7, 0x0d,
	0xb7, 0x7f, 0x8a, 0xc8, 0xf7, 0x23, 0x3d, 0x85, 0xa0, 0xa1, 0xe2, 0x8f, 0x66, 0x0e, 0xb0, 0x95,
	0xee, 0x66, 0xf2, 0x07, 0x38, 0x72, 0x13, 0x54, 0xac, 0x96, 0xda, 0xa0, 0x15, 0x1c, 0x4e, 0xeb,
	0x5e, 0x4b, 0xa6, 0x13, 0xcf, 0x4e, 0xff, 0xff, 0x12, 0x63, 0x33, 0x89, 0x74, 0x5e, 0xc3, 0xc2,
	0xf5, 0xac, 0xf5, 0x16, 0x60, 0xb2, 0x3a, 0xe5, 0xd9, 0xac, 0x92, 0x44, 0xce, 0xa7, 0xef, 0xca,
	0xc7, 0x4b, 0xa1, 0x26, 0x1a, 0xab, 0x51, 0x94, 0x3f, 0xce, 0xa4, 0x55, 0xfd, 0xb3, 0x14, 0xa5,
	0x50, 0xd3, 0xc1, 0x3c, 0xed, 0xdb, 0x3b, 0xb9, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x45,
	0x42, 0xd7, 0x4e, 0x02, 0x00, 0x00,
}
