// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/test/api/test_service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	tls "go.chromium.org/chromiumos/config/go/api/test/tls"
	longrunning "go.chromium.org/chromiumos/config/go/api/test/tls/dependencies/longrunning"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// For RunTests, clients can specify both lists of suites and test cases.
// Both will be run as part of a single request.
type RunTestsRequest struct {
	// Test suites to run (by tag or explicit list of tests)
	TestSuites           []*TestSuite `protobuf:"bytes,1,rep,name=test_suites,json=testSuites,proto3" json:"test_suites,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RunTestsRequest) Reset()         { *m = RunTestsRequest{} }
func (m *RunTestsRequest) String() string { return proto.CompactTextString(m) }
func (*RunTestsRequest) ProtoMessage()    {}
func (*RunTestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{0}
}

func (m *RunTestsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTestsRequest.Unmarshal(m, b)
}
func (m *RunTestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTestsRequest.Marshal(b, m, deterministic)
}
func (m *RunTestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTestsRequest.Merge(m, src)
}
func (m *RunTestsRequest) XXX_Size() int {
	return xxx_messageInfo_RunTestsRequest.Size(m)
}
func (m *RunTestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunTestsRequest proto.InternalMessageInfo

func (m *RunTestsRequest) GetTestSuites() []*TestSuite {
	if m != nil {
		return m.TestSuites
	}
	return nil
}

type RunTestsResponse struct {
	TestCaseResults      []*TestCaseResult `protobuf:"bytes,1,rep,name=test_case_results,json=testCaseResults,proto3" json:"test_case_results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RunTestsResponse) Reset()         { *m = RunTestsResponse{} }
func (m *RunTestsResponse) String() string { return proto.CompactTextString(m) }
func (*RunTestsResponse) ProtoMessage()    {}
func (*RunTestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{1}
}

func (m *RunTestsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTestsResponse.Unmarshal(m, b)
}
func (m *RunTestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTestsResponse.Marshal(b, m, deterministic)
}
func (m *RunTestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTestsResponse.Merge(m, src)
}
func (m *RunTestsResponse) XXX_Size() int {
	return xxx_messageInfo_RunTestsResponse.Size(m)
}
func (m *RunTestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunTestsResponse proto.InternalMessageInfo

func (m *RunTestsResponse) GetTestCaseResults() []*TestCaseResult {
	if m != nil {
		return m.TestCaseResults
	}
	return nil
}

type RunTestsMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunTestsMetadata) Reset()         { *m = RunTestsMetadata{} }
func (m *RunTestsMetadata) String() string { return proto.CompactTextString(m) }
func (*RunTestsMetadata) ProtoMessage()    {}
func (*RunTestsMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_467512ed519718ce, []int{2}
}

func (m *RunTestsMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTestsMetadata.Unmarshal(m, b)
}
func (m *RunTestsMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTestsMetadata.Marshal(b, m, deterministic)
}
func (m *RunTestsMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTestsMetadata.Merge(m, src)
}
func (m *RunTestsMetadata) XXX_Size() int {
	return xxx_messageInfo_RunTestsMetadata.Size(m)
}
func (m *RunTestsMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTestsMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RunTestsMetadata proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RunTestsRequest)(nil), "chromiumos.test.api.RunTestsRequest")
	proto.RegisterType((*RunTestsResponse)(nil), "chromiumos.test.api.RunTestsResponse")
	proto.RegisterType((*RunTestsMetadata)(nil), "chromiumos.test.api.RunTestsMetadata")
}

func init() {
	proto.RegisterFile("chromiumos/test/api/test_service.proto", fileDescriptor_467512ed519718ce)
}

var fileDescriptor_467512ed519718ce = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdd, 0xca, 0x13, 0x31,
	0x10, 0xa5, 0x56, 0xa4, 0xa4, 0x42, 0x6b, 0x14, 0x94, 0x82, 0x22, 0x6b, 0x51, 0x11, 0x4d, 0xa0,
	0x45, 0x6f, 0xa5, 0xea, 0x85, 0x88, 0x52, 0x59, 0xbd, 0x10, 0x6f, 0x4a, 0xdc, 0x8e, 0x31, 0xb0,
	0x9b, 0x59, 0x33, 0xd9, 0xe2, 0x7b, 0xf8, 0x00, 0x3e, 0x8a, 0xf7, 0x7d, 0xaa, 0x8f, 0xfd, 0xdf,
	0xfe, 0xd1, 0xde, 0x65, 0x93, 0x73, 0xe6, 0x9c, 0x99, 0x33, 0xcb, 0x1e, 0x47, 0xbf, 0x1c, 0x26,
	0x26, 0x4b, 0x90, 0xa4, 0x07, 0xf2, 0x52, 0xa5, 0xa6, 0x38, 0xac, 0x08, 0xdc, 0xc6, 0x44, 0x20,
	0x52, 0x87, 0x1e, 0xf9, 0xed, 0x16, 0x27, 0xf2, 0x67, 0xa1, 0x52, 0x33, 0x11, 0x1d, 0x72, 0x84,
	0xf6, 0xa7, 0xd1, 0x0d, 0x5d, 0xfa, 0x38, 0xbf, 0x4b, 0x12, 0xb4, 0x3e, 0xa6, 0xb2, 0xc8, 0xe4,
	0xfd, 0x19, 0xfc, 0x1a, 0x52, 0xb0, 0x6b, 0xb0, 0x91, 0x01, 0x92, 0x31, 0x5a, 0xed, 0x32, 0x6b,
	0x8d, 0xd5, 0x12, 0x53, 0x70, 0xca, 0x1b, 0xb4, 0x75, 0xa5, 0x67, 0x27, 0x6d, 0x47, 0x8a, 0x60,
	0xe5, 0x80, 0xb2, 0xd8, 0x57, 0xd8, 0xe9, 0xe9, 0x16, 0x33, 0xe3, 0xab, 0x06, 0x83, 0x6f, 0x6c,
	0x14, 0x66, 0xf6, 0x2b, 0x90, 0xa7, 0x10, 0x7e, 0x67, 0x40, 0x9e, 0xbf, 0x66, 0xc3, 0x16, 0x46,
	0xf7, 0x7a, 0x0f, 0xfb, 0x4f, 0x87, 0xb3, 0x07, 0xe2, 0xc8, 0x24, 0x44, 0xce, 0xfb, 0x92, 0xc3,
	0x42, 0xe6, 0xeb, 0x23, 0x7d, 0xb8, 0x3e, 0xb8, 0x36, 0xee, 0x07, 0x11, 0x1b, 0xb7, 0x95, 0x29,
	0x45, 0x4b, 0xc0, 0x97, 0xec, 0xd6, 0xbe, 0xdb, 0x5a, 0xe0, 0xd1, 0x49, 0x81, 0xb7, 0x8a, 0x20,
	0x2c, 0xb0, 0xe1, 0xc8, 0xef, 0x7c, 0x53, 0xc0, 0x5b, 0x91, 0x4f, 0xe0, 0xd5, 0x5a, 0x79, 0x35,
	0xfb, 0xdf, 0x67, 0xc3, 0xc2, 0x58, 0x99, 0x24, 0xff, 0xdb, 0x63, 0x37, 0x3f, 0x3b, 0xdc, 0x18,
	0x32, 0x68, 0xdf, 0x65, 0x9e, 0xcf, 0xbb, 0x52, 0x65, 0x20, 0x85, 0x58, 0xa1, 0x9a, 0xc7, 0xd6,
	0x45, 0x57, 0x53, 0x99, 0xdc, 0x17, 0x1a, 0x51, 0xc7, 0x20, 0x3a, 0x01, 0x89, 0x65, 0x1d, 0x50,
	0x20, 0xb7, 0x8b, 0xe7, 0xec, 0xce, 0x2e, 0xb1, 0x6a, 0x7a, 0xe7, 0xb6, 0x76, 0xc9, 0xff, 0xf5,
	0xd8, 0xa8, 0x79, 0xf8, 0xa8, 0x22, 0x87, 0xc4, 0x5f, 0x5d, 0x6c, 0xac, 0x24, 0x5c, 0xe8, 0xed,
	0xe5, 0x76, 0x31, 0x63, 0x77, 0x0f, 0xb8, 0x95, 0xbd, 0xfd, 0x87, 0xc6, 0xe1, 0x1f, 0x36, 0xa8,
	0x67, 0xcb, 0xa7, 0x47, 0xd3, 0xd9, 0xdb, 0x9c, 0x73, 0x3e, 0x9e, 0x6c, 0x17, 0xd3, 0x23, 0x4b,
	0x71, 0x90, 0xe0, 0x1b, 0xf9, 0xfd, 0x85, 0xc6, 0x46, 0x51, 0xa0, 0xd3, 0xf2, 0xf0, 0x17, 0xd2,
	0xd8, 0xac, 0xf5, 0x8f, 0x1b, 0xc5, 0x32, 0xcf, 0xaf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xc4,
	0x25, 0x1c, 0xd7, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestServiceClient interface {
	// ProvisionDut installs a specified version of Chrome OS on the DUT, along
	// with any specified DLCs.
	//
	// If the DUT is already on the specified version of Chrome OS, the OS will
	// not be provisioned.
	//
	// If the DUT already has the specified list of DLCs, only the missing DLCs
	// will be provisioned.
	ProvisionDut(ctx context.Context, in *tls.ProvisionDutRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// ProvisionLacros installs a specified version of Lacros on the DUT.
	//
	// If the DUT already has the specified version of Lacros, Lacros will not be
	// provisioned.
	ProvisionLacros(ctx context.Context, in *tls.ProvisionLacrosRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	// RunTests runs the requested tests.
	RunTests(ctx context.Context, in *RunTestsRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
}

type testServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestServiceClient(cc *grpc.ClientConn) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) ProvisionDut(ctx context.Context, in *tls.ProvisionDutRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/chromiumos.test.api.TestService/ProvisionDut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) ProvisionLacros(ctx context.Context, in *tls.ProvisionLacrosRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/chromiumos.test.api.TestService/ProvisionLacros", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) RunTests(ctx context.Context, in *RunTestsRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/chromiumos.test.api.TestService/RunTests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
type TestServiceServer interface {
	// ProvisionDut installs a specified version of Chrome OS on the DUT, along
	// with any specified DLCs.
	//
	// If the DUT is already on the specified version of Chrome OS, the OS will
	// not be provisioned.
	//
	// If the DUT already has the specified list of DLCs, only the missing DLCs
	// will be provisioned.
	ProvisionDut(context.Context, *tls.ProvisionDutRequest) (*longrunning.Operation, error)
	// ProvisionLacros installs a specified version of Lacros on the DUT.
	//
	// If the DUT already has the specified version of Lacros, Lacros will not be
	// provisioned.
	ProvisionLacros(context.Context, *tls.ProvisionLacrosRequest) (*longrunning.Operation, error)
	// RunTests runs the requested tests.
	RunTests(context.Context, *RunTestsRequest) (*longrunning.Operation, error)
}

// UnimplementedTestServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (*UnimplementedTestServiceServer) ProvisionDut(ctx context.Context, req *tls.ProvisionDutRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionDut not implemented")
}
func (*UnimplementedTestServiceServer) ProvisionLacros(ctx context.Context, req *tls.ProvisionLacrosRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionLacros not implemented")
}
func (*UnimplementedTestServiceServer) RunTests(ctx context.Context, req *RunTestsRequest) (*longrunning.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunTests not implemented")
}

func RegisterTestServiceServer(s *grpc.Server, srv TestServiceServer) {
	s.RegisterService(&_TestService_serviceDesc, srv)
}

func _TestService_ProvisionDut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(tls.ProvisionDutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).ProvisionDut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromiumos.test.api.TestService/ProvisionDut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).ProvisionDut(ctx, req.(*tls.ProvisionDutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_ProvisionLacros_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(tls.ProvisionLacrosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).ProvisionLacros(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromiumos.test.api.TestService/ProvisionLacros",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).ProvisionLacros(ctx, req.(*tls.ProvisionLacrosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_RunTests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).RunTests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chromiumos.test.api.TestService/RunTests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).RunTests(ctx, req.(*RunTestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chromiumos.test.api.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProvisionDut",
			Handler:    _TestService_ProvisionDut_Handler,
		},
		{
			MethodName: "ProvisionLacros",
			Handler:    _TestService_ProvisionLacros_Handler,
		},
		{
			MethodName: "RunTests",
			Handler:    _TestService_RunTests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chromiumos/test/api/test_service.proto",
}
