# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/ctp2_filters.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/test/api/ctp2_filters.proto',
  package='chromiumos.test.api',
  syntax='proto3',
  serialized_options=b'Z-go.chromium.org/chromiumos/config/go/test/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&chromiumos/test/api/ctp2_filters.proto\x12\x13\x63hromiumos.test.api\"\xc1\x01\n\x1aGenericFilterStreamRequest\x12S\n\x1ainternal_testplan_fragment\x18\x01 \x01(\x0b\x32-.chromiumos.test.api.InternalTestplanFragmentH\x00\x12\x43\n\rauth_fragment\x18\x02 \x01(\x0b\x32*.chromiumos.test.api.AuthorizationFragmentH\x00\x42\t\n\x07message\"\xfc\x01\n\x1bGenericFilterStreamResponse\x12S\n\x1ainternal_testplan_fragment\x18\x01 \x01(\x0b\x32-.chromiumos.test.api.InternalTestplanFragmentH\x00\x12\x38\n\x0clog_fragment\x18\x02 \x01(\x0b\x32 .chromiumos.test.api.LogFragmentH\x00\x12\x43\n\rauth_fragment\x18\x03 \x01(\x0b\x32*.chromiumos.test.api.AuthorizationFragmentH\x00\x42\t\n\x07message\"e\n\x10\x46ragmentMetadata\x12\x12\n\ntotal_size\x18\x01 \x01(\x03\x12\x17\n\x0ftotal_fragments\x18\x02 \x01(\x03\x12\r\n\x05index\x18\x03 \x01(\x03\x12\x15\n\rfragment_size\x18\x04 \x01(\x03\"e\n\x18InternalTestplanFragment\x12\x10\n\x08\x66ragment\x18\x01 \x01(\x0c\x12\x37\n\x08metadata\x18\x02 \x01(\x0b\x32%.chromiumos.test.api.FragmentMetadata\"X\n\x0bLogFragment\x12\x10\n\x08\x66ragment\x18\x01 \x01(\x0c\x12\x37\n\x08metadata\x18\x02 \x01(\x0b\x32%.chromiumos.test.api.FragmentMetadata\"@\n\x14\x41uthorizationRequest\x12\x18\n\x10\x63redential_paths\x18\x01 \x03(\t\x12\x0e\n\x06scopes\x18\x02 \x03(\t\"&\n\x15\x41uthorizationResponse\x12\r\n\x05token\x18\x01 \x01(\t\"b\n\x15\x41uthorizationFragment\x12\x10\n\x08\x66ragment\x18\x01 \x01(\x0c\x12\x37\n\x08metadata\x18\x02 \x01(\x0b\x32%.chromiumos.test.api.FragmentMetadataB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3'
)




_GENERICFILTERSTREAMREQUEST = _descriptor.Descriptor(
  name='GenericFilterStreamRequest',
  full_name='chromiumos.test.api.GenericFilterStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='internal_testplan_fragment', full_name='chromiumos.test.api.GenericFilterStreamRequest.internal_testplan_fragment', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auth_fragment', full_name='chromiumos.test.api.GenericFilterStreamRequest.auth_fragment', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='chromiumos.test.api.GenericFilterStreamRequest.message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=64,
  serialized_end=257,
)


_GENERICFILTERSTREAMRESPONSE = _descriptor.Descriptor(
  name='GenericFilterStreamResponse',
  full_name='chromiumos.test.api.GenericFilterStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='internal_testplan_fragment', full_name='chromiumos.test.api.GenericFilterStreamResponse.internal_testplan_fragment', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='log_fragment', full_name='chromiumos.test.api.GenericFilterStreamResponse.log_fragment', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auth_fragment', full_name='chromiumos.test.api.GenericFilterStreamResponse.auth_fragment', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='chromiumos.test.api.GenericFilterStreamResponse.message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=260,
  serialized_end=512,
)


_FRAGMENTMETADATA = _descriptor.Descriptor(
  name='FragmentMetadata',
  full_name='chromiumos.test.api.FragmentMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_size', full_name='chromiumos.test.api.FragmentMetadata.total_size', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_fragments', full_name='chromiumos.test.api.FragmentMetadata.total_fragments', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='chromiumos.test.api.FragmentMetadata.index', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fragment_size', full_name='chromiumos.test.api.FragmentMetadata.fragment_size', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=615,
)


_INTERNALTESTPLANFRAGMENT = _descriptor.Descriptor(
  name='InternalTestplanFragment',
  full_name='chromiumos.test.api.InternalTestplanFragment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fragment', full_name='chromiumos.test.api.InternalTestplanFragment.fragment', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='chromiumos.test.api.InternalTestplanFragment.metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=617,
  serialized_end=718,
)


_LOGFRAGMENT = _descriptor.Descriptor(
  name='LogFragment',
  full_name='chromiumos.test.api.LogFragment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fragment', full_name='chromiumos.test.api.LogFragment.fragment', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='chromiumos.test.api.LogFragment.metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=720,
  serialized_end=808,
)


_AUTHORIZATIONREQUEST = _descriptor.Descriptor(
  name='AuthorizationRequest',
  full_name='chromiumos.test.api.AuthorizationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='credential_paths', full_name='chromiumos.test.api.AuthorizationRequest.credential_paths', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scopes', full_name='chromiumos.test.api.AuthorizationRequest.scopes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=810,
  serialized_end=874,
)


_AUTHORIZATIONRESPONSE = _descriptor.Descriptor(
  name='AuthorizationResponse',
  full_name='chromiumos.test.api.AuthorizationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='chromiumos.test.api.AuthorizationResponse.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=876,
  serialized_end=914,
)


_AUTHORIZATIONFRAGMENT = _descriptor.Descriptor(
  name='AuthorizationFragment',
  full_name='chromiumos.test.api.AuthorizationFragment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fragment', full_name='chromiumos.test.api.AuthorizationFragment.fragment', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='chromiumos.test.api.AuthorizationFragment.metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=916,
  serialized_end=1014,
)

_GENERICFILTERSTREAMREQUEST.fields_by_name['internal_testplan_fragment'].message_type = _INTERNALTESTPLANFRAGMENT
_GENERICFILTERSTREAMREQUEST.fields_by_name['auth_fragment'].message_type = _AUTHORIZATIONFRAGMENT
_GENERICFILTERSTREAMREQUEST.oneofs_by_name['message'].fields.append(
  _GENERICFILTERSTREAMREQUEST.fields_by_name['internal_testplan_fragment'])
_GENERICFILTERSTREAMREQUEST.fields_by_name['internal_testplan_fragment'].containing_oneof = _GENERICFILTERSTREAMREQUEST.oneofs_by_name['message']
_GENERICFILTERSTREAMREQUEST.oneofs_by_name['message'].fields.append(
  _GENERICFILTERSTREAMREQUEST.fields_by_name['auth_fragment'])
_GENERICFILTERSTREAMREQUEST.fields_by_name['auth_fragment'].containing_oneof = _GENERICFILTERSTREAMREQUEST.oneofs_by_name['message']
_GENERICFILTERSTREAMRESPONSE.fields_by_name['internal_testplan_fragment'].message_type = _INTERNALTESTPLANFRAGMENT
_GENERICFILTERSTREAMRESPONSE.fields_by_name['log_fragment'].message_type = _LOGFRAGMENT
_GENERICFILTERSTREAMRESPONSE.fields_by_name['auth_fragment'].message_type = _AUTHORIZATIONFRAGMENT
_GENERICFILTERSTREAMRESPONSE.oneofs_by_name['message'].fields.append(
  _GENERICFILTERSTREAMRESPONSE.fields_by_name['internal_testplan_fragment'])
_GENERICFILTERSTREAMRESPONSE.fields_by_name['internal_testplan_fragment'].containing_oneof = _GENERICFILTERSTREAMRESPONSE.oneofs_by_name['message']
_GENERICFILTERSTREAMRESPONSE.oneofs_by_name['message'].fields.append(
  _GENERICFILTERSTREAMRESPONSE.fields_by_name['log_fragment'])
_GENERICFILTERSTREAMRESPONSE.fields_by_name['log_fragment'].containing_oneof = _GENERICFILTERSTREAMRESPONSE.oneofs_by_name['message']
_GENERICFILTERSTREAMRESPONSE.oneofs_by_name['message'].fields.append(
  _GENERICFILTERSTREAMRESPONSE.fields_by_name['auth_fragment'])
_GENERICFILTERSTREAMRESPONSE.fields_by_name['auth_fragment'].containing_oneof = _GENERICFILTERSTREAMRESPONSE.oneofs_by_name['message']
_INTERNALTESTPLANFRAGMENT.fields_by_name['metadata'].message_type = _FRAGMENTMETADATA
_LOGFRAGMENT.fields_by_name['metadata'].message_type = _FRAGMENTMETADATA
_AUTHORIZATIONFRAGMENT.fields_by_name['metadata'].message_type = _FRAGMENTMETADATA
DESCRIPTOR.message_types_by_name['GenericFilterStreamRequest'] = _GENERICFILTERSTREAMREQUEST
DESCRIPTOR.message_types_by_name['GenericFilterStreamResponse'] = _GENERICFILTERSTREAMRESPONSE
DESCRIPTOR.message_types_by_name['FragmentMetadata'] = _FRAGMENTMETADATA
DESCRIPTOR.message_types_by_name['InternalTestplanFragment'] = _INTERNALTESTPLANFRAGMENT
DESCRIPTOR.message_types_by_name['LogFragment'] = _LOGFRAGMENT
DESCRIPTOR.message_types_by_name['AuthorizationRequest'] = _AUTHORIZATIONREQUEST
DESCRIPTOR.message_types_by_name['AuthorizationResponse'] = _AUTHORIZATIONRESPONSE
DESCRIPTOR.message_types_by_name['AuthorizationFragment'] = _AUTHORIZATIONFRAGMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenericFilterStreamRequest = _reflection.GeneratedProtocolMessageType('GenericFilterStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERICFILTERSTREAMREQUEST,
  '__module__' : 'chromiumos.test.api.ctp2_filters_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.GenericFilterStreamRequest)
  })
_sym_db.RegisterMessage(GenericFilterStreamRequest)

GenericFilterStreamResponse = _reflection.GeneratedProtocolMessageType('GenericFilterStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERICFILTERSTREAMRESPONSE,
  '__module__' : 'chromiumos.test.api.ctp2_filters_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.GenericFilterStreamResponse)
  })
_sym_db.RegisterMessage(GenericFilterStreamResponse)

FragmentMetadata = _reflection.GeneratedProtocolMessageType('FragmentMetadata', (_message.Message,), {
  'DESCRIPTOR' : _FRAGMENTMETADATA,
  '__module__' : 'chromiumos.test.api.ctp2_filters_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.FragmentMetadata)
  })
_sym_db.RegisterMessage(FragmentMetadata)

InternalTestplanFragment = _reflection.GeneratedProtocolMessageType('InternalTestplanFragment', (_message.Message,), {
  'DESCRIPTOR' : _INTERNALTESTPLANFRAGMENT,
  '__module__' : 'chromiumos.test.api.ctp2_filters_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.InternalTestplanFragment)
  })
_sym_db.RegisterMessage(InternalTestplanFragment)

LogFragment = _reflection.GeneratedProtocolMessageType('LogFragment', (_message.Message,), {
  'DESCRIPTOR' : _LOGFRAGMENT,
  '__module__' : 'chromiumos.test.api.ctp2_filters_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.LogFragment)
  })
_sym_db.RegisterMessage(LogFragment)

AuthorizationRequest = _reflection.GeneratedProtocolMessageType('AuthorizationRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZATIONREQUEST,
  '__module__' : 'chromiumos.test.api.ctp2_filters_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.AuthorizationRequest)
  })
_sym_db.RegisterMessage(AuthorizationRequest)

AuthorizationResponse = _reflection.GeneratedProtocolMessageType('AuthorizationResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZATIONRESPONSE,
  '__module__' : 'chromiumos.test.api.ctp2_filters_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.AuthorizationResponse)
  })
_sym_db.RegisterMessage(AuthorizationResponse)

AuthorizationFragment = _reflection.GeneratedProtocolMessageType('AuthorizationFragment', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZATIONFRAGMENT,
  '__module__' : 'chromiumos.test.api.ctp2_filters_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.test.api.AuthorizationFragment)
  })
_sym_db.RegisterMessage(AuthorizationFragment)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
