// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.artifact;

option go_package = "go.chromium.org/chromiumos/config/go/test/artifact";

// Manifest for test result artifacts.
// NEXT TAG: 3
message Manifest {

  // Captures the manifest version.
  uint32 version = 1;

  // List of associated test result artifacts.
  repeated Artifact artifacts = 2;
}

// Artifact information.
// NEXT TAG: 3
message Artifact {

  // Capture the various artifact types.
  // NEXT TAG: 2
  enum ArtifactType {
    ARTIFACT_TYPE_UNSPECIFIED = 0;
    TEST_RESULT = 1;
  }

  // Type of the artifact.
  ArtifactType type = 1;

  // URL of Google Storage location containing the artifact
  // e.g. gs://foo/bar/baz.ext
  string gs_url = 2;
}
