// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.artifact;

option go_package = "go.chromium.org/chromiumos/config/go/test/artifact";

import "chromiumos/storage_path.proto";
import "chromiumos/test/api/provision_state.proto";
import "chromiumos/test/api/test_case.proto";
import "chromiumos/test/api/test_case_metadata.proto";
import "chromiumos/test/api/test_case_result.proto";
import "chromiumos/test/lab/api/dut.proto";

// Captures artifact for test result.
// NEXT TAG: 4
message TestResult {

  // Captures the test result artifact version.
  uint32 version = 1;

  // List of test runs.
  repeated TestRun test_runs = 2;

  // List of custom results.
  repeated CustomResult custom_results = 3;
}

// Captures information regarding a test run.
// NEXT TAG: 8
message TestRun {

  //  The executed test case.
  chromiumos.test.api.TestCase test_case = 1;

  //  Metadata related to test case and execution context.
  chromiumos.test.api.TestCaseMetadata test_case_metadata = 2;

  // Result of a single execution of a given test case.
  chromiumos.test.api.TestCaseResult test_case_result = 3;

  // Build ids associated with the test result.
  repeated uint64 build_ids = 4;

  // The topology of the connected devices under test.
  // If there are multiple duts (for multi DUTs tests), there should be
  // corresponding build info entry for each with the same ordering.
  chromiumos.test.lab.api.DutTopology dut_topology = 5;

  // Primary DUT info.
  DutInfo primary_dut = 6;

  // Companion DUT info.
  repeated DutInfo companion_duts = 7;
}

// Captures dut related info.
// NEXT TAG: 4
message DutInfo {

  // Id of the dut.
  chromiumos.test.lab.api.Dut.Id id = 1;

  // Id of the provision state corresponding to the dut.
  chromiumos.test.api.ProvisionState.Id provision_state_id = 3;

  // Additional DUT related info that could be specific to
  // a certain TLE e.g. moblab install id, etc.
  map<string, string> tags = 2;
}

// Represents custom results, as a way for tests to produce produce arbitrary
// artifacts.
// NEXT TAG: 3
message CustomResult {

  // Location of the custom result artifacts generated during execution.
  chromiumos.StoragePath result_dir_path = 1;

  // Type of the custom result.
  oneof type {
    Cts cts = 2;
  }

  // CTS related custom results
  message Cts {
    // TODO: Add fields as needed.
  }
}
