// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/software/audio_config.proto

package software

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Note that all files should be specified as paths relative to the root of a
// chromiumos checkout, e.g. "src/overlays/overlay-<target>/audio/HiFi.conf".
type AudioConfig struct {
	// The name of the audio card.
	CardName string `protobuf:"bytes,1,opt,name=card_name,json=cardName,proto3" json:"card_name,omitempty"`
	// Path to the CRAS card configuration file.
	// See
	// https://chromium.googlesource.com/chromiumos/third_party/adhd/+/master/cras/#card-configuration.
	CardConfigFile string `protobuf:"bytes,2,opt,name=card_config_file,json=cardConfigFile,proto3" json:"card_config_file,omitempty"`
	// Path to the dsp.ini configuration file.
	DspFile string `protobuf:"bytes,3,opt,name=dsp_file,json=dspFile,proto3" json:"dsp_file,omitempty"`
	// Path to the UCM file. Note that this is the UCM verb file (e.g.
	// "HiFi.conf"), NOT the UCM master file (e.g. <sound card name>.conf).
	UcmFile string `protobuf:"bytes,4,opt,name=ucm_file,json=ucmFile,proto3" json:"ucm_file,omitempty"`
	// Path to the UCM master file (e.g. <sound card name>.conf).
	UcmMasterFile string `protobuf:"bytes,5,opt,name=ucm_master_file,json=ucmMasterFile,proto3" json:"ucm_master_file,omitempty"`
	// UCM suffix, if any.
	UcmSuffix            string   `protobuf:"bytes,6,opt,name=ucm_suffix,json=ucmSuffix,proto3" json:"ucm_suffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioConfig) Reset()         { *m = AudioConfig{} }
func (m *AudioConfig) String() string { return proto.CompactTextString(m) }
func (*AudioConfig) ProtoMessage()    {}
func (*AudioConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b09d347f71d372, []int{0}
}

func (m *AudioConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioConfig.Unmarshal(m, b)
}
func (m *AudioConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioConfig.Marshal(b, m, deterministic)
}
func (m *AudioConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioConfig.Merge(m, src)
}
func (m *AudioConfig) XXX_Size() int {
	return xxx_messageInfo_AudioConfig.Size(m)
}
func (m *AudioConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AudioConfig proto.InternalMessageInfo

func (m *AudioConfig) GetCardName() string {
	if m != nil {
		return m.CardName
	}
	return ""
}

func (m *AudioConfig) GetCardConfigFile() string {
	if m != nil {
		return m.CardConfigFile
	}
	return ""
}

func (m *AudioConfig) GetDspFile() string {
	if m != nil {
		return m.DspFile
	}
	return ""
}

func (m *AudioConfig) GetUcmFile() string {
	if m != nil {
		return m.UcmFile
	}
	return ""
}

func (m *AudioConfig) GetUcmMasterFile() string {
	if m != nil {
		return m.UcmMasterFile
	}
	return ""
}

func (m *AudioConfig) GetUcmSuffix() string {
	if m != nil {
		return m.UcmSuffix
	}
	return ""
}

func init() {
	proto.RegisterType((*AudioConfig)(nil), "chromiumos.config.api.software.AudioConfig")
}

func init() { proto.RegisterFile("api/software/audio_config.proto", fileDescriptor_45b09d347f71d372) }

var fileDescriptor_45b09d347f71d372 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcb, 0x4a, 0xc4, 0x30,
	0x14, 0x86, 0xa9, 0x97, 0x71, 0x1a, 0xf1, 0x42, 0x57, 0x15, 0xf1, 0x82, 0x0b, 0x99, 0x55, 0x82,
	0xcc, 0x13, 0xa8, 0xe0, 0x4e, 0x17, 0xba, 0x73, 0x53, 0x62, 0x9a, 0xd4, 0x03, 0x73, 0x7a, 0x42,
	0xd2, 0xa0, 0xaf, 0xe9, 0x1b, 0x49, 0x4e, 0x2c, 0xce, 0xf6, 0xff, 0xbe, 0xf3, 0x93, 0xfc, 0xe2,
	0x4a, 0x7b, 0x50, 0x91, 0xdc, 0xf4, 0xa5, 0x83, 0x55, 0x3a, 0xf5, 0x40, 0x9d, 0xa1, 0xd1, 0xc1,
	0x20, 0x7d, 0xa0, 0x89, 0x9a, 0x4b, 0xf3, 0x19, 0x08, 0x21, 0x21, 0x45, 0xf9, 0x07, 0xb4, 0x07,
	0x39, 0x9f, 0xdc, 0xfc, 0x54, 0xe2, 0xf0, 0x3e, 0x9f, 0x3d, 0x32, 0x6c, 0xce, 0x45, 0x6d, 0x74,
	0xe8, 0xbb, 0x51, 0xa3, 0x6d, 0xab, 0xeb, 0x6a, 0x55, 0xbf, 0x2e, 0x73, 0xf0, 0xa2, 0xd1, 0x36,
	0x2b, 0x71, 0xca, 0xb0, 0x14, 0x75, 0x0e, 0x36, 0xb6, 0xdd, 0x61, 0xe7, 0x38, 0xe7, 0xa5, 0xe2,
	0x09, 0x36, 0xb6, 0x39, 0x13, 0xcb, 0x3e, 0xfa, 0x62, 0xec, 0xb2, 0x71, 0xd0, 0x47, 0x3f, 0xa3,
	0x64, 0xb0, 0xa0, 0xbd, 0x82, 0x92, 0x41, 0x46, 0xb7, 0xe2, 0x24, 0x23, 0xd4, 0x71, 0xb2, 0xa1,
	0x18, 0xfb, 0x6c, 0x1c, 0x25, 0x83, 0xcf, 0x9c, 0xb2, 0x77, 0x21, 0x44, 0xf6, 0x62, 0x72, 0x0e,
	0xbe, 0xdb, 0x05, 0x2b, 0x75, 0x32, 0xf8, 0xc6, 0xc1, 0xc3, 0xfa, 0xfd, 0x6e, 0x20, 0x39, 0x7f,
	0x5c, 0x52, 0x18, 0xd4, 0xff, 0x0a, 0xaa, 0x3c, 0x5e, 0x0d, 0xa4, 0xb6, 0xb7, 0xfb, 0x58, 0xf0,
	0x5e, 0xeb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x3c, 0x4a, 0xbd, 0x52, 0x01, 0x00, 0x00,
}
