// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/config/api/software/health_config.proto

package software

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The configuration of diagnostic and telemetry handled by cros_healthd.
// For more details, see:
// https://source.chromium.org/chromiumos/chromiumos/codesearch/+/HEAD:src/platform2/chromeos-config/README.md
type HealthConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthConfig) Reset()         { *m = HealthConfig{} }
func (m *HealthConfig) String() string { return proto.CompactTextString(m) }
func (*HealthConfig) ProtoMessage()    {}
func (*HealthConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_0be47934e389fcd8, []int{0}
}

func (m *HealthConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthConfig.Unmarshal(m, b)
}
func (m *HealthConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthConfig.Marshal(b, m, deterministic)
}
func (m *HealthConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthConfig.Merge(m, src)
}
func (m *HealthConfig) XXX_Size() int {
	return xxx_messageInfo_HealthConfig.Size(m)
}
func (m *HealthConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HealthConfig proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HealthConfig)(nil), "chromiumos.config.api.software.HealthConfig")
}

func init() {
	proto.RegisterFile("chromiumos/config/api/software/health_config.proto", fileDescriptor_0be47934e389fcd8)
}

var fileDescriptor_0be47934e389fcd8 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4a, 0xce, 0x28, 0xca,
	0xcf, 0xcd, 0x2c, 0xcd, 0xcd, 0x2f, 0xd6, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x4f, 0x2c,
	0xc8, 0xd4, 0x2f, 0xce, 0x4f, 0x2b, 0x29, 0x4f, 0x2c, 0x4a, 0xd5, 0xcf, 0x48, 0x4d, 0xcc, 0x29,
	0xc9, 0x88, 0x87, 0x48, 0xe9, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0xc9, 0x21, 0xf4, 0xe8, 0x41,
	0x25, 0x12, 0x0b, 0x32, 0xf5, 0x60, 0x7a, 0x94, 0xf8, 0xb8, 0x78, 0x3c, 0xc0, 0xda, 0x9c, 0xc1,
	0x92, 0x4e, 0xc6, 0x51, 0x86, 0xe9, 0xf9, 0x7a, 0x30, 0x4d, 0x7a, 0xf9, 0x45, 0xe9, 0xfa, 0x98,
	0xb6, 0xa6, 0xe7, 0xa3, 0x58, 0x9c, 0xc4, 0x06, 0xb6, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x88, 0x85, 0xdd, 0x23, 0xa1, 0x00, 0x00, 0x00,
}
