// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/config/api/software/nnpalm_config.proto

package software

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The configuration of neural network palm rejection.
// For more details, see:
// https://source.chromium.org/chromiumos/chromiumos/codesearch/+/HEAD:src/platform2/chromeos-config/README.md
type NnpalmConfig struct {
	Model                string   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	RadiusPolynomial     string   `protobuf:"bytes,2,opt,name=radius_polynomial,json=radiusPolynomial,proto3" json:"radius_polynomial,omitempty"`
	TouchCompatible      bool     `protobuf:"varint,3,opt,name=touch_compatible,json=touchCompatible,proto3" json:"touch_compatible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NnpalmConfig) Reset()         { *m = NnpalmConfig{} }
func (m *NnpalmConfig) String() string { return proto.CompactTextString(m) }
func (*NnpalmConfig) ProtoMessage()    {}
func (*NnpalmConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5151d0162cb031e0, []int{0}
}

func (m *NnpalmConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NnpalmConfig.Unmarshal(m, b)
}
func (m *NnpalmConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NnpalmConfig.Marshal(b, m, deterministic)
}
func (m *NnpalmConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NnpalmConfig.Merge(m, src)
}
func (m *NnpalmConfig) XXX_Size() int {
	return xxx_messageInfo_NnpalmConfig.Size(m)
}
func (m *NnpalmConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NnpalmConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NnpalmConfig proto.InternalMessageInfo

func (m *NnpalmConfig) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *NnpalmConfig) GetRadiusPolynomial() string {
	if m != nil {
		return m.RadiusPolynomial
	}
	return ""
}

func (m *NnpalmConfig) GetTouchCompatible() bool {
	if m != nil {
		return m.TouchCompatible
	}
	return false
}

func init() {
	proto.RegisterType((*NnpalmConfig)(nil), "chromiumos.config.api.software.NnpalmConfig")
}

func init() {
	proto.RegisterFile("chromiumos/config/api/software/nnpalm_config.proto", fileDescriptor_5151d0162cb031e0)
}

var fileDescriptor_5151d0162cb031e0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x41, 0x6b, 0x83, 0x30,
	0x1c, 0x47, 0x71, 0x63, 0x63, 0x0b, 0x83, 0xb9, 0xb0, 0x83, 0xa7, 0x21, 0x3b, 0x59, 0x0a, 0x09,
	0xad, 0xdf, 0xa0, 0xde, 0x4b, 0xf1, 0xd8, 0x8b, 0xc4, 0xa8, 0x31, 0x90, 0xe4, 0x1f, 0x62, 0xa4,
	0x14, 0xfa, 0xe1, 0x0b, 0xb1, 0x5a, 0x4a, 0x8f, 0xf9, 0xbd, 0x3c, 0xf8, 0x3f, 0xb4, 0xe5, 0xbd,
	0x03, 0x2d, 0x47, 0x0d, 0x03, 0xe5, 0x60, 0x3a, 0x29, 0x28, 0xb3, 0x92, 0x0e, 0xd0, 0xf9, 0x13,
	0x73, 0x2d, 0x35, 0xc6, 0x32, 0xa5, 0xab, 0x09, 0x11, 0xeb, 0xc0, 0x03, 0xfe, 0xbb, 0x3b, 0xe4,
	0x06, 0x98, 0x95, 0x64, 0x76, 0xfe, 0x2f, 0xe8, 0x6b, 0x1f, 0xb4, 0x22, 0x40, 0xfc, 0x8b, 0xde,
	0x34, 0x34, 0xad, 0x4a, 0xa2, 0x34, 0xca, 0x3e, 0xcb, 0xe9, 0x81, 0xd7, 0xe8, 0xc7, 0xb1, 0x46,
	0x8e, 0x43, 0x65, 0x41, 0x9d, 0x0d, 0x68, 0xc9, 0x54, 0xf2, 0x12, 0x7e, 0xc4, 0x13, 0x38, 0x2c,
	0x3b, 0x5e, 0xa1, 0xd8, 0xc3, 0xc8, 0xfb, 0x8a, 0x83, 0xb6, 0xcc, 0xcb, 0x5a, 0xb5, 0xc9, 0x6b,
	0x1a, 0x65, 0x1f, 0xe5, 0x77, 0xd8, 0x8b, 0x65, 0xde, 0xe5, 0xc7, 0x8d, 0x00, 0x32, 0x9f, 0x48,
	0xc0, 0x09, 0xfa, 0xdc, 0x28, 0xe0, 0x21, 0xb3, 0x7e, 0x0f, 0x65, 0xf9, 0x35, 0x00, 0x00, 0xff,
	0xff, 0xa7, 0xee, 0xcb, 0x97, 0x0f, 0x01, 0x00, 0x00,
}
