// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/config/api/software/portage.proto

package software

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Defines config used to generate portage builds.
type Portage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Portage) Reset()         { *m = Portage{} }
func (m *Portage) String() string { return proto.CompactTextString(m) }
func (*Portage) ProtoMessage()    {}
func (*Portage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7534b938c08acf58, []int{0}
}

func (m *Portage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Portage.Unmarshal(m, b)
}
func (m *Portage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Portage.Marshal(b, m, deterministic)
}
func (m *Portage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Portage.Merge(m, src)
}
func (m *Portage) XXX_Size() int {
	return xxx_messageInfo_Portage.Size(m)
}
func (m *Portage) XXX_DiscardUnknown() {
	xxx_messageInfo_Portage.DiscardUnknown(m)
}

var xxx_messageInfo_Portage proto.InternalMessageInfo

type Portage_BuildTarget struct {
	OverlayName string   `protobuf:"bytes,1,opt,name=overlay_name,json=overlayName,proto3" json:"overlay_name,omitempty"`
	ProfileName string   `protobuf:"bytes,2,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	UseFlags    []string `protobuf:"bytes,3,rep,name=use_flags,json=useFlags,proto3" json:"use_flags,omitempty"`
	// Features enabled for the given build
	// See: https://wiki.gentoo.org/wiki/FEATURES
	Features             []string `protobuf:"bytes,4,rep,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Portage_BuildTarget) Reset()         { *m = Portage_BuildTarget{} }
func (m *Portage_BuildTarget) String() string { return proto.CompactTextString(m) }
func (*Portage_BuildTarget) ProtoMessage()    {}
func (*Portage_BuildTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_7534b938c08acf58, []int{0, 0}
}

func (m *Portage_BuildTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Portage_BuildTarget.Unmarshal(m, b)
}
func (m *Portage_BuildTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Portage_BuildTarget.Marshal(b, m, deterministic)
}
func (m *Portage_BuildTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Portage_BuildTarget.Merge(m, src)
}
func (m *Portage_BuildTarget) XXX_Size() int {
	return xxx_messageInfo_Portage_BuildTarget.Size(m)
}
func (m *Portage_BuildTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_Portage_BuildTarget.DiscardUnknown(m)
}

var xxx_messageInfo_Portage_BuildTarget proto.InternalMessageInfo

func (m *Portage_BuildTarget) GetOverlayName() string {
	if m != nil {
		return m.OverlayName
	}
	return ""
}

func (m *Portage_BuildTarget) GetProfileName() string {
	if m != nil {
		return m.ProfileName
	}
	return ""
}

func (m *Portage_BuildTarget) GetUseFlags() []string {
	if m != nil {
		return m.UseFlags
	}
	return nil
}

func (m *Portage_BuildTarget) GetFeatures() []string {
	if m != nil {
		return m.Features
	}
	return nil
}

// Message describing a package, The corresponding variable names are from
// https://devmanual.gentoo.org/ebuild-writing/variables/index.html
type Portage_Package struct {
	// The package name (PN variable).
	PackageName string `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// The package category (CATEGORY variable).
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	// The package version and revision (PVR variable).
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Portage_Package) Reset()         { *m = Portage_Package{} }
func (m *Portage_Package) String() string { return proto.CompactTextString(m) }
func (*Portage_Package) ProtoMessage()    {}
func (*Portage_Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_7534b938c08acf58, []int{0, 1}
}

func (m *Portage_Package) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Portage_Package.Unmarshal(m, b)
}
func (m *Portage_Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Portage_Package.Marshal(b, m, deterministic)
}
func (m *Portage_Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Portage_Package.Merge(m, src)
}
func (m *Portage_Package) XXX_Size() int {
	return xxx_messageInfo_Portage_Package.Size(m)
}
func (m *Portage_Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Portage_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Portage_Package proto.InternalMessageInfo

func (m *Portage_Package) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *Portage_Package) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Portage_Package) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*Portage)(nil), "chromiumos.config.api.software.Portage")
	proto.RegisterType((*Portage_BuildTarget)(nil), "chromiumos.config.api.software.Portage.BuildTarget")
	proto.RegisterType((*Portage_Package)(nil), "chromiumos.config.api.software.Portage.Package")
}

func init() {
	proto.RegisterFile("chromiumos/config/api/software/portage.proto", fileDescriptor_7534b938c08acf58)
}

var fileDescriptor_7534b938c08acf58 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x15, 0x8a, 0x48, 0xe2, 0x32, 0x65, 0x8a, 0x82, 0x84, 0x0a, 0x53, 0x07, 0xe4, 0x08,
	0xf5, 0x0d, 0x3a, 0x30, 0xa2, 0xaa, 0x62, 0x62, 0xa9, 0xae, 0xe1, 0x6c, 0x2c, 0x92, 0x9c, 0x75,
	0xb6, 0x8b, 0xfa, 0x0e, 0x3c, 0x32, 0x03, 0x6a, 0x9c, 0x80, 0x2a, 0x36, 0xff, 0xff, 0x7d, 0xd6,
	0x9d, 0x3e, 0xf1, 0xd0, 0xbc, 0x33, 0x75, 0x26, 0x74, 0xe4, 0xea, 0x86, 0x7a, 0x65, 0x74, 0x0d,
	0xd6, 0xd4, 0x8e, 0x94, 0xff, 0x04, 0xc6, 0xda, 0x12, 0x7b, 0xd0, 0x28, 0x2d, 0x93, 0xa7, 0xe2,
	0xf6, 0x8f, 0x96, 0x91, 0x96, 0x60, 0x8d, 0x9c, 0xe8, 0xfb, 0xef, 0x44, 0xa4, 0x9b, 0xf8, 0xa3,
	0xfa, 0x4a, 0xc4, 0x7c, 0x1d, 0x4c, 0xfb, 0xf6, 0x02, 0xac, 0xd1, 0x17, 0x77, 0xe2, 0x9a, 0x0e,
	0xc8, 0x2d, 0x1c, 0x77, 0x3d, 0x74, 0x58, 0x26, 0x8b, 0x64, 0x99, 0x6f, 0xe7, 0x63, 0xf7, 0x0c,
	0x1d, 0x9e, 0x10, 0xcb, 0xa4, 0x4c, 0x8b, 0x11, 0xb9, 0x88, 0xc8, 0xd8, 0x0d, 0xc8, 0x8d, 0xc8,
	0x83, 0xc3, 0x9d, 0x6a, 0x41, 0xbb, 0x72, 0xb6, 0x98, 0x2d, 0xf3, 0x6d, 0x16, 0x1c, 0x3e, 0x9d,
	0x72, 0x51, 0x89, 0x4c, 0x21, 0xf8, 0xc0, 0xe8, 0xca, 0xcb, 0x38, 0x9b, 0x72, 0xb5, 0x17, 0xe9,
	0x06, 0x9a, 0x0f, 0xd0, 0x71, 0x4d, 0x7c, 0x9e, 0x5d, 0x32, 0x76, 0xc3, 0x9a, 0x4a, 0x64, 0x0d,
	0x78, 0xd4, 0xc4, 0xc7, 0xf1, 0x8a, 0xdf, 0x5c, 0x94, 0x22, 0x3d, 0x20, 0x3b, 0x43, 0x7d, 0x39,
	0x1b, 0x46, 0x53, 0x5c, 0xaf, 0x5e, 0x1f, 0x35, 0xc9, 0xc9, 0x91, 0x24, 0xd6, 0xf5, 0x7f, 0xbd,
	0x9a, 0xce, 0x0c, 0xef, 0xaf, 0x06, 0xb5, 0xab, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xad,
	0x25, 0xd5, 0x8a, 0x01, 0x00, 0x00,
}
