#!/usr/bin/env bash
#
# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Script creates partner program or project git repo, gerrit groups, apply ACLs
#
# Requirements :
# 1.  Script runner needs to be added to group mdb/chrome-git-admins
#     and gerrit group chromeos-partner-admins
# 2.  Install jq for json file parsing
#     $ sudo apt-get install jq
#
# The script can get re-run with out any problems.
#   The apis check if repo and gerrit groups exist.
#   ACLs can be re-applied and gets deduped.
#   Creating local_manifest step will be skipped if one already exist.
#   Update of Manifest-internal will be skipped if the project is already added.
#   Creating already existing project buckets is a noop.
#
# TODO(b/152909984): Script should check script runner's env for correct setup

readonly INTERNAL_GERRIT_HOST='https://chrome-internal-review.googlesource.com'
readonly INTERNAL_GITILES_HOST='https://chrome-internal.googlesource.com'
readonly CONTENT_TYPE_JSON='Content-Type: application/json'
readonly PROGRAM_CONFIG_FILE='gs://chromeos-device-lifecycle-manager/program_config.json'

# Name of the program
program=''
# Name of the project
project=''
# Command to run if provided, otherwise run through entire script.
run=''
# Path of the repo depending on program and project
repo_path=''
# Name used to create repo and gerrit groups
name=''
# Parsed project json object
global_project_obj=''

readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
readonly WORK_DIR=$(mktemp --tmpdir -d programrepoXXXXXX)
trap "rm -rf ${WORK_DIR}" EXIT

usage() {
  echo "usage: ./createpartnerrepo.sh --program <programName> --project <projectName> --run <command>"
  echo "--program is required"
  echo "--project is optional"
  echo "--run is optional. Supported commands:"
  echo "    acls - apply ACLs to project's committer and access groups"
  echo "    gerritgroups - create and apply default permissions to gerrit groups"
  echo "    localmanifest - create local_manifest.xml for the project repo"
  echo "    manifestinternal - update manifest_internal repo internal_full.xml"
  echo "    createprojectbuckets - create gs buckets for the project"
}

gob_post() {
  local body="$1"
  local url="$2"
  gob-curl -X POST -H "${CONTENT_TYPE_JSON}" -d "${body}" "${url}"
}

gob_put() {
  local body="$1"
  local url="$2"
  gob-curl -X PUT -H "${CONTENT_TYPE_JSON}" -d "${body}" "$url"
}

apply_acls_with_static_members() {
  if [[ -n "${project}" ]]; then
    local groups=(
      '"google/'"${project}"'-odm-external@google.com"'
      '"google/'"${project}"'-oem-external@google.com"'
      '"google/'"${project}"'-soc-external@google.com"')
    local url="$INTERNAL_GERRIT_HOST/a/groups/chromeos-partner-${project}-committers/groups"

    for group in "${groups[@]}"; do
      echo "## adding group ${group}"
      local body='{"groups": ['"${group}"']}'
      gob_post "${body}" "${url}"
    done
  fi

  apply_default_access
}

init_project_obj() {
  local json_file
  json_file=$(gsutil cat "${PROGRAM_CONFIG_FILE}")
  if [[ -z "${global_project_obj}" ]]; then
    global_project_obj=$(echo "$json_file" | jq '.[] \
      | select(.program=="'$program'") \
      | .projects[] \
      | select(.project=="'$project'")')
  fi
}
apply_acl_from_config() {
  if [[ -n "${project}" ]]; then
     init_project_obj

     if [[ -n "${global_project_obj}" ]]; then
    #Add groups
      local groups
      groups=$(echo "${global_project_obj}" \
        | jq '[.oemAcls + .odmAcls + .socAcls \
        | .[] | select(.groupEmail != null and .groupEmail != "") \
        | .groupEmail | "google/" + .]' )

      if [[ -n "${groups}" ]]; then
        local url="$INTERNAL_GERRIT_HOST/a/groups/chromeos-partner-${name}-committers/groups"
        local json='{"groups": '"$groups"'}'
        gob_post "$json" "$url"
      else
        echo "No groups found in project config, no groups added."
      fi

     #Add users
      local users
      users=$(echo "$global_project_obj" \
        | jq '[.oemAcls + .odmAcls + .socAcls \
        | .[] \
        | select(.userEmail != null and .userEmail != "") \
        | .userEmail | .]')
      if [[ -n "$users" ]]; then
       local url="$INTERNAL_GERRIT_HOST/a/groups/chromeos-partner-${name}-committers/members"
       local json='{"members": '"$users"'}'
       gob_post "$url" "$json"
      else
        echo "No users found in project config, no users added."
      fi
    fi
  fi

  apply_default_access
}

apply_default_access() {

  echo -e "\n## Add default required reader access  ${INTERNAL_GERRIT_HOST}/${repo_path//%2f/\/}"
  gob-ctl acl "${INTERNAL_GERRIT_HOST}/${repo_path//%2f/\/}" \
   -reader "email/chromeos-commit-bot@chromium.org"

  gob-ctl acl "${INTERNAL_GERRIT_HOST}/${repo_path//%2f/\/}" \
   -reader "mdbgroup/chromeos-ci-oncalls"

  gob-ctl acl "${INTERNAL_GERRIT_HOST}/${repo_path//%2f/\/}" \
   -reader "mdbgroup/chromeos-ci-server"

  echo -e "## Project's access group gets added to the program's access group"
  echo "If project is a reference-board, its committer groups gets added to chromeos-partner-${program}-committers"
  if [[ -n "$project" ]]; then
    gob-curl -X PUT "${INTERNAL_GERRIT_HOST}/a/groups/chromeos-partner-${program}-committers/groups/chromeos-partner-${project}-access"

    if [[ -n "$global_project_obj" ]]; then
       local reference_board
       reference_board=$(echo "$global_project_obj" | jq '.referenceBoard')
       if [[ "$reference_board" == "true" ]]; then
          gob-curl -X PUT "${INTERNAL_GERRIT_HOST}/a/groups/chromeos-partner-${program}-committers/groups/chromeos-partner-${project}-access"
       fi
    fi
  fi
}

create_gerrit_groups() {
  #Create an admin gerrit group"
  echo -e "## Create an admin gerrit group"
  gob_put \
   '{"owner": "chromeos-partner-admins"}' \
   "${INTERNAL_GERRIT_HOST}/a/groups/chromeos-partner-${name}-admin"

  gob_put \
   '{"owner": "chromeos-partner-admins"}' \
   "${INTERNAL_GERRIT_HOST}/a/groups/chromeos-partner-${name}-admin/owner"

  #Create committers gerrit group"
  echo -e "\n## Create committers gerrit group"
  gob_put \
   '{"owner": "chromeos-partner-'"${name}"'-admin", "visible_to_all": "true"}' \
   "${INTERNAL_GERRIT_HOST}/a/groups/chromeos-partner-${name}-committers"

  gob_put \
   '{"owner": "chromeos-partner-'"${name}"'-admin"}' \
   "${INTERNAL_GERRIT_HOST}/a/groups/chromeos-partner-${name}-committers/owner"


  #Create access gerrit group"
  echo -e "\n## Create access gerrit group"
  gob_put \
   '{"owner": "chromeos-partner-'"${name}"'-admin", "visible_to_all": "true"}' \
   "${INTERNAL_GERRIT_HOST}/a/groups/chromeos-partner-${name}-access"

  gob_put \
   '{"owner": "chromeos-partner-'"${name}"'-admin"}' \
   "${INTERNAL_GERRIT_HOST}/a/groups/chromeos-partner-${name}-access/owner"

  echo -e "\n## Add committer to access group"
  gob-curl -X PUT "${INTERNAL_GERRIT_HOST}/a/groups/chromeos-partner-${name}-access/groups/chromeos-partner-${name}-committers"
  if [[ -n "$project" ]]; then
    echo -e "\n## Add "chromeos-partner-"$name"-access" as an included group in the program's access group"
    gob-curl -X PUT "${INTERNAL_GERRIT_HOST}/a/groups/chromeos-partner-${program}-access/groups/chromeos-partner-${project}-access"
  fi

  #Add chromeos-partner-${name}-access group to chromeos-allpartners"
  gob-curl -X PUT "${INTERNAL_GERRIT_HOST}/a/groups/chromeos-allpartners/groups/chromeos-partner-${name}-access"

  #Add the chromeos-partner-${name}-access group as an included group of chromeos-partner-project-cheets-access"
  gob-curl -X PUT "${INTERNAL_GERRIT_HOST}/a/groups/chromeos-partner-project-cheets-access/groups/chromeos-partner-${name}-access"

  # Permissions at /google3/third_party/java_src/gerritcodereview/gerrit/java/com/google/gerrit/common/data/Permission.java
  #Step 9:
  echo -e "\n## Set up access permission"
  refs_acls=(
  '{"add": {"refs/*": {"permissions": {"forgeAuthor": {"rules": {"chromeos-partner-'"$name"'-committers": {"action": "ALLOW"}}}}}}}'
  '{"add": {"refs/*": {"permissions": {"label-Commit-Queue": {"rules": {"chromeos-partner-'"$name"'-committers": {"action": "ALLOW", "min": 0, "max": 1}}}}}}}'
  '{"add": {"refs/*": {"permissions": {"label-Verified": {"rules": {"chromeos-partner-'"$name"'-committers": {"action": "ALLOW", "min": -1, "max": 1}}}}}}}'
  '{"add": {"refs/*": {"permissions": {"submit": {"rules": {"chromeos-partner-'"$name"'-committers": {"action": "ALLOW"}}}}}}}'
  '{"add": {"refs/*": {"permissions": {"read": {"rules": {"chromeos-partner-'"$name"'-access": {"action": "ALLOW"}}}}}}}'
  '{"add": {"refs/for/*": {"permissions": {"create": {"rules": {"chromeos-partner-'"$name"'-committers": {"action": "ALLOW"}}}}}}}'
  '{"add": {"refs/for/*": {"permissions": {"push": {"rules": {"chromeos-partner-'"$name"'-committers": {"action": "ALLOW"}}}}}}}'
  '{"add": {"refs/for/refs/*": {"permissions": {"pushMerge": {"rules": {"chromeos-partner-'"$name"'-committers": {"action": "ALLOW"}}}}}}}'
  '{"add": {"refs/for/refs/*": {"permissions": {"push": {"rules": {"chromeos-partner-'"$name"'-committers": {"action": "ALLOW"}}}}}}}')

  for ref_acl in "${refs_acls[@]}"; do
    echo "## adding ${ref_acl}"
    gob_post "${ref_acl}" "${INTERNAL_GERRIT_HOST}/a/projects/${repo_path}/access"
  done

  # TODO(b/153167090): Remove once projects don't need to access each other
  if [[ -n "$project" ]]; then
    gob_post '{"add": {"refs/*": {"permissions": {"read": {"rules": {"chromeos-partner-'"$program"'-access": {"action": "ALLOW"}}}}}}}' \
      "${INTERNAL_GERRIT_HOST}/a/projects/${repo_path}/access"
  fi
}

# Update manifest once when all the projects have been created
# TODO(b/153167560): Determine how to update_manifest once for all projects.
update_manifest_internal() {
  echo -e "\n## Add ${program}-${name} to manifest-internal/internal_full.xml"
  cd "$WORK_DIR"
  git clone "https://chrome-internal.googlesource.com/chromeos/manifest-internal"
  cd manifest-internal

  #Read internal_full, add only if project is not already there
  if [[ -z "${project}" ]]; then
    if [[ -n $(grep 'name="chromeos/program/'"$program"'"' internal_full.xml) ]]; then
      echo "Program already exist in internal_full.xml. Do nothing."
      return 0
    fi
  else
    if [[ -n $(grep 'name="chromeos/project/'"$program"'/'"$name"'"' internal_full.xml) ]]; then
      echo "Project already exist in internal_full.xml. Do nothing."
      return 0
    fi
  fi

  if [[ -z "$project" ]]; then
    local project_xml='  <project remote="cros-internal"\n '
    project_xml+='          path="src\/program\/'"$name"'"\n '
    project_xml+='          name="chromeos\/program\/'"$name"'"\n '
    project_xml+='          groups="'"$program"'-'"$name"'" \/>\n'
    project_xml+='<\/manifest>'
  else
    local project_xml='  <project remote="cros-internal"\n '
    project_xml+='          path="src\/project\/'"$program"'\/'"$name"'"\n '
    project_xml+='          name="chromeos\/project\/'"$program"'\/'"$name"'" \/>\n'
    project_xml+='<\/manifest>'
  fi

  sed -i "s/<\/manifest>/$project_xml/" internal_full.xml
  git add internal_full.xml
  git commit -m "Add to the internal manifest. ${program}/${name}"
  git cl upload -r "chromeos-continuous-integration-team@google.com" --force
}

create_local_manifest() {
  if [[ -n "$project" ]]; then
    local source_manifest="${SCRIPT_DIR}/manifests/${program}_local_manifest.xml"
    if [[ ! -f "${source_manifest}" ]]; then
      echo "Source manifest ${source_manifest} does not exist."
      echo "Skipping local manifest creation."
      return
    fi

    echo -e "\n## Add local_manifest.xml at  ${INTERNAL_GITILES_HOST}/${repo_path//%2f/\/}"
    cd "$WORK_DIR"
    git clone "${INTERNAL_GITILES_HOST}/${repo_path//%2f/\/}"
    cd "${name}"
    if [[ -e local_manifest.xml ]]; then
      echo "local_manifest.xml already exist in repo. Do nothing."
      return 0
    fi

    git checkout -b "${program}"-"${name}"
    cp "${source_manifest}" local_manifest.xml
    git add local_manifest.xml
    git commit -m "Add local_manifest.xml for project. ${program}/${project}"
    git cl upload -r "chromeos-continuous-integration-team@google.com" --force
  fi
}

create_git_repo() {
  echo -e "\n## Create internal repo at ${INTERNAL_GERRIT_HOST}/a/projects/${repo_path}"
  repo_description='{"description": "Partner Chromeos internal project repo",
    "submit_type":"INHERIT",
    "owners": ["mdb/chrome-git-admins"],
    "create_empty_commit": "true",
    "parent": "chromeos"}'
  gob_put "$repo_description" "${INTERNAL_GERRIT_HOST}/a/projects/${repo_path}"
}

try_set_viewer() {
  local group="${1}"
  local bucket="${2}"
  if ! gsutil iam ch "group:${group}:objectViewer" "${bucket}"; then
    echo "Skipping setting objectViewer for ${group} on ${bucket}." >&2
  fi
}

create_project_buckets() {
  # setup() guaranteed that we have a $program.
  # The invoker needs to have Storage Object Admin, Storage Object Creator
  # permissions in the chromeos-bot project.
  gcloud config set project chromeos-bot
  if [[ -n "$project" ]]; then
    local bucket="gs://chromeos-${program}-${project}"
    echo "Creating bucket ${bucket}."
    gsutil mb "${bucket}"
    gsutil iam ch serviceAccount:chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com:objectAdmin "${bucket}"
    for id in odm oem soc; do
      try_set_viewer "${project}-${id}-external@google.com" "${bucket}"
    done
  else
    echo "No project specified, skipping creation of project bucket."
  fi
}

setup() {
  # Setup checks for program and project defined
  if [[ -z "$program" ]]; then
    usage
    exit 1
  elif [[ -z "$project" ]]; then
    name=${program}
    repo_path="chromeos/program/${program}"
  else
    name=${project}
    repo_path="chromeos/project/${program}/${project}"
  fi
  repo_path=${repo_path//\//%2f}

  #set -x
}

run_command() {
  # Script will run commands
  if [[ -n "$run" ]]; then
    if [[ "$run" == "acls" ]]; then
      apply_acls_with_static_members
    elif [[ "$run" == "gerritgroups" ]]; then
      create_gerrit_groups
    elif [[ "$run" == "localmanifest" ]]; then
      create_local_manifest
    elif [[ "$run" == "manifestinternal" ]]; then
      update_manifest_internal
    elif [[ "$run" == "createprojectbuckets" ]]; then
      create_project_buckets
    else
      echo 'Unknown --run command'
      usage
    fi
    exit 0
  fi
}


if ! prodcertstatus; then
  # Some of the commands require LOAS credentials. For example, without LOAS
  # credentials, the gob-ctl to set readers on repos will fail.
  echo "LOAS credentials missing. Please log in with prodaccess." >&2
  exit 1
fi

while [[ "$1" != "" ]]; do
  case $1 in
    --program)
      shift
      program=$1
      ;;
    --project)
      shift
      project=$1
      ;;
    --run)
      shift
      run=$1
      ;;
    -h | --help)
      usage
      exit
      ;;
    *)
       echo "Unknown option $1"
       usage
       exit
      ;;
  esac
  shift
done

setup
run_command

# If fall through, run script from AtoZ
#Step 1:
create_git_repo

#Step 2:
create_gerrit_groups

#Step 3:
echo -e "\n\n. For a project, add oem, odem, soc google groups as members of chromeos-partner-${name}-committers"
# TODO(b/152065714): applyAclsFromConfig once config is ready with export
apply_acls_with_static_members

#Step 4:
create_local_manifest

#Step 5:
create_project_buckets

echo '## Script completed'
