// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/build_config.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_go "go.chromium.org/chromiumos/config/go"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Specifies all configuration for a build.
type BuildConfig struct {
	// Base build target.
	BuildTargetId *_go.BuildTargetId `protobuf:"bytes,1,opt,name=build_target_id,json=buildTargetId,proto3" json:"build_target_id,omitempty"`
	// Config for all unique hw design configs supported by the build.
	//
	// For a "fan-in" build, many design configs can be supported by the same
	// build, e.g. the config for each design config doesn't contain confidential
	// information, so it is acceptable for owners of different variants to see
	// each others' configs.
	//
	// For a "fan-out" build, each config will get a different build, e.g. to
	// allow owners of variants to keep config private.
	//
	// Builds between these two extremes are also possible, e.g. configs A and
	// B share a build, while configs C gets a different build.
	BuildPayloads []*_go.DesignConfigBuildPayload `protobuf:"bytes,2,rep,name=build_payloads,json=buildPayloads,proto3" json:"build_payloads,omitempty"`
	// Branding config for all devices supported by the build.
	//
	// This list is not necessarily the same length as <build_payloads>.
	// At runtime, a device will search this list for its payload, and configure
	// itself based on the payload.
	BrandConfigs         []*_go.BrandConfig `protobuf:"bytes,3,rep,name=brand_configs,json=brandConfigs,proto3" json:"brand_configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BuildConfig) Reset()         { *m = BuildConfig{} }
func (m *BuildConfig) String() string { return proto.CompactTextString(m) }
func (*BuildConfig) ProtoMessage()    {}
func (*BuildConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bca5278769d73cc, []int{0}
}

func (m *BuildConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildConfig.Unmarshal(m, b)
}
func (m *BuildConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildConfig.Marshal(b, m, deterministic)
}
func (m *BuildConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildConfig.Merge(m, src)
}
func (m *BuildConfig) XXX_Size() int {
	return xxx_messageInfo_BuildConfig.Size(m)
}
func (m *BuildConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BuildConfig proto.InternalMessageInfo

func (m *BuildConfig) GetBuildTargetId() *_go.BuildTargetId {
	if m != nil {
		return m.BuildTargetId
	}
	return nil
}

func (m *BuildConfig) GetBuildPayloads() []*_go.DesignConfigBuildPayload {
	if m != nil {
		return m.BuildPayloads
	}
	return nil
}

func (m *BuildConfig) GetBrandConfigs() []*_go.BrandConfig {
	if m != nil {
		return m.BrandConfigs
	}
	return nil
}

type BuildConfigList struct {
	Value                []*BuildConfig `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BuildConfigList) Reset()         { *m = BuildConfigList{} }
func (m *BuildConfigList) String() string { return proto.CompactTextString(m) }
func (*BuildConfigList) ProtoMessage()    {}
func (*BuildConfigList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bca5278769d73cc, []int{1}
}

func (m *BuildConfigList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildConfigList.Unmarshal(m, b)
}
func (m *BuildConfigList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildConfigList.Marshal(b, m, deterministic)
}
func (m *BuildConfigList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildConfigList.Merge(m, src)
}
func (m *BuildConfigList) XXX_Size() int {
	return xxx_messageInfo_BuildConfigList.Size(m)
}
func (m *BuildConfigList) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildConfigList.DiscardUnknown(m)
}

var xxx_messageInfo_BuildConfigList proto.InternalMessageInfo

func (m *BuildConfigList) GetValue() []*BuildConfig {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*BuildConfig)(nil), "chromiumos.config.api.BuildConfig")
	proto.RegisterType((*BuildConfigList)(nil), "chromiumos.config.api.BuildConfigList")
}

func init() { proto.RegisterFile("api/build_config.proto", fileDescriptor_4bca5278769d73cc) }

var fileDescriptor_4bca5278769d73cc = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4b, 0xfb, 0x30,
	0x14, 0xc7, 0xe9, 0x6f, 0xfc, 0x3c, 0xa4, 0xce, 0x41, 0x60, 0x52, 0x76, 0x90, 0xda, 0x53, 0x51,
	0x48, 0x60, 0x5e, 0x3c, 0x6f, 0x1e, 0x14, 0x3d, 0x48, 0xf1, 0xe4, 0xa5, 0x24, 0x6b, 0x8d, 0x0f,
	0xba, 0xbe, 0x90, 0xb4, 0x82, 0xff, 0xb5, 0x7f, 0x82, 0x2c, 0x89, 0xb6, 0x93, 0x1e, 0x5f, 0xf2,
	0xf9, 0x7e, 0xf2, 0xcd, 0x23, 0xe7, 0x42, 0x03, 0x97, 0x3d, 0x34, 0x55, 0xb9, 0xc3, 0xf6, 0x0d,
	0x14, 0xd3, 0x06, 0x3b, 0xa4, 0xcb, 0xdd, 0xbb, 0xc1, 0x3d, 0xf4, 0x7b, 0xb4, 0x2c, 0x5c, 0x08,
	0x0d, 0x2b, 0x2a, 0x8d, 0x68, 0x8f, 0xd1, 0xd5, 0xd2, 0xc7, 0x3b, 0x61, 0x54, 0xdd, 0x95, 0x50,
	0x85, 0xe3, 0xcb, 0xaa, 0xb6, 0xa0, 0xda, 0xc0, 0x96, 0x1e, 0xd2, 0xe2, 0xb3, 0x41, 0x11, 0x90,
	0xec, 0x2b, 0x22, 0xf1, 0xe6, 0x70, 0xbe, 0x75, 0x0c, 0xbd, 0x27, 0x8b, 0x3f, 0xae, 0x24, 0x4a,
	0xa3, 0x3c, 0x5e, 0xa7, 0x6c, 0xa8, 0xf3, 0xf3, 0xb8, 0x0b, 0xbe, 0x38, 0xf0, 0xa1, 0x2a, 0xe6,
	0x72, 0x3c, 0xd2, 0x82, 0x9c, 0x1d, 0x3d, 0x68, 0x93, 0x7f, 0xe9, 0x2c, 0x8f, 0xd7, 0xd7, 0x13,
	0xa2, 0x3b, 0xd7, 0xd3, 0x57, 0x70, 0xd2, 0x67, 0x9f, 0x09, 0xce, 0x30, 0x59, 0xba, 0x25, 0xf3,
	0xf1, 0xef, 0x6d, 0x32, 0x73, 0xca, 0x8b, 0xa9, 0x6e, 0x07, 0xce, 0x1b, 0x8b, 0x53, 0x39, 0x0c,
	0x36, 0x7b, 0x24, 0x8b, 0xd1, 0x8f, 0x9f, 0xc0, 0x76, 0xf4, 0x96, 0xfc, 0xff, 0x10, 0x4d, 0x5f,
	0x27, 0x91, 0xf3, 0x65, 0x6c, 0x72, 0xf5, 0x6c, 0x14, 0x2b, 0x7c, 0x60, 0x73, 0xf5, 0x9a, 0x2b,
	0xfc, 0xc5, 0x19, 0x1a, 0xc5, 0x87, 0x2c, 0xf7, 0x59, 0xae, 0x90, 0x0b, 0x0d, 0xf2, 0xc4, 0xad,
	0xfc, 0xe6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x98, 0x0a, 0x83, 0xf1, 0x01, 0x00, 0x00,
}
