// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/config/api/design.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	public_replication "go.chromium.org/chromiumos/config/go/public_replication"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Design_Config_Constraint_Level int32

const (
	Design_Config_Constraint_TYPE_UNKNOWN Design_Config_Constraint_Level = 0
	Design_Config_Constraint_REQUIRED     Design_Config_Constraint_Level = 1
	Design_Config_Constraint_PREFERRED    Design_Config_Constraint_Level = 2
	Design_Config_Constraint_OPTIONAL     Design_Config_Constraint_Level = 3
)

var Design_Config_Constraint_Level_name = map[int32]string{
	0: "TYPE_UNKNOWN",
	1: "REQUIRED",
	2: "PREFERRED",
	3: "OPTIONAL",
}

var Design_Config_Constraint_Level_value = map[string]int32{
	"TYPE_UNKNOWN": 0,
	"REQUIRED":     1,
	"PREFERRED":    2,
	"OPTIONAL":     3,
}

func (x Design_Config_Constraint_Level) String() string {
	return proto.EnumName(Design_Config_Constraint_Level_name, int32(x))
}

func (Design_Config_Constraint_Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0949ab302cb28294, []int{0, 1, 0, 0}
}

// Next ID: 8
type Design struct {
	// Fields replicated to public configs.
	PublicReplication *public_replication.PublicReplication `protobuf:"bytes,7,opt,name=public_replication,json=publicReplication,proto3" json:"public_replication,omitempty"`
	// Globally unique design identifier.
	Id *DesignId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Program that defines the constraints for this design.
	ProgramId *ProgramId `protobuf:"bytes,2,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	// ODM for the given hardware design.
	OdmId *PartnerId `protobuf:"bytes,3,opt,name=odm_id,json=odmId,proto3" json:"odm_id,omitempty"`
	// Design codename (human friendly).
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Board version assignment for each build phase.
	// Example:
	//  1 --> proto
	//  2 --> proto2 ...
	BoardIdPhase map[uint32]string `protobuf:"bytes,5,rep,name=board_id_phase,json=boardIdPhase,proto3" json:"board_id_phase,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Supported hardware configurations for a given design.
	Configs              []*Design_Config `protobuf:"bytes,6,rep,name=configs,proto3" json:"configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Design) Reset()         { *m = Design{} }
func (m *Design) String() string { return proto.CompactTextString(m) }
func (*Design) ProtoMessage()    {}
func (*Design) Descriptor() ([]byte, []int) {
	return fileDescriptor_0949ab302cb28294, []int{0}
}

func (m *Design) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Design.Unmarshal(m, b)
}
func (m *Design) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Design.Marshal(b, m, deterministic)
}
func (m *Design) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Design.Merge(m, src)
}
func (m *Design) XXX_Size() int {
	return xxx_messageInfo_Design.Size(m)
}
func (m *Design) XXX_DiscardUnknown() {
	xxx_messageInfo_Design.DiscardUnknown(m)
}

var xxx_messageInfo_Design proto.InternalMessageInfo

func (m *Design) GetPublicReplication() *public_replication.PublicReplication {
	if m != nil {
		return m.PublicReplication
	}
	return nil
}

func (m *Design) GetId() *DesignId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Design) GetProgramId() *ProgramId {
	if m != nil {
		return m.ProgramId
	}
	return nil
}

func (m *Design) GetOdmId() *PartnerId {
	if m != nil {
		return m.OdmId
	}
	return nil
}

func (m *Design) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Design) GetBoardIdPhase() map[uint32]string {
	if m != nil {
		return m.BoardIdPhase
	}
	return nil
}

func (m *Design) GetConfigs() []*Design_Config {
	if m != nil {
		return m.Configs
	}
	return nil
}

// Defines a unique hardware configuration for a given hardware design
// and the corresponding hardware features that will be supported.
// Next ID: 6
type Design_Config struct {
	// Fields replicated to public configs.
	PublicReplication *public_replication.PublicReplication `protobuf:"bytes,5,opt,name=public_replication,json=publicReplication,proto3" json:"public_replication,omitempty"`
	// The ID encoded in hardware on a device, typically in CBI.
	Id *DesignConfigId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Each unique value of hardware_topology requires a unique DesignConfigId
	HardwareTopology *HardwareTopology `protobuf:"bytes,2,opt,name=hardware_topology,json=hardwareTopology,proto3" json:"hardware_topology,omitempty"`
	// This field is generated from hardware_topology by combining all of the
	// partial HardwareFeatures definitions from each selected hardware topology
	HardwareFeatures     *HardwareFeatures `protobuf:"bytes,3,opt,name=hardware_features,json=hardwareFeatures,proto3" json:"hardware_features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Design_Config) Reset()         { *m = Design_Config{} }
func (m *Design_Config) String() string { return proto.CompactTextString(m) }
func (*Design_Config) ProtoMessage()    {}
func (*Design_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_0949ab302cb28294, []int{0, 1}
}

func (m *Design_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Design_Config.Unmarshal(m, b)
}
func (m *Design_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Design_Config.Marshal(b, m, deterministic)
}
func (m *Design_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Design_Config.Merge(m, src)
}
func (m *Design_Config) XXX_Size() int {
	return xxx_messageInfo_Design_Config.Size(m)
}
func (m *Design_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Design_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Design_Config proto.InternalMessageInfo

func (m *Design_Config) GetPublicReplication() *public_replication.PublicReplication {
	if m != nil {
		return m.PublicReplication
	}
	return nil
}

func (m *Design_Config) GetId() *DesignConfigId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Design_Config) GetHardwareTopology() *HardwareTopology {
	if m != nil {
		return m.HardwareTopology
	}
	return nil
}

func (m *Design_Config) GetHardwareFeatures() *HardwareFeatures {
	if m != nil {
		return m.HardwareFeatures
	}
	return nil
}

// Constraints on HardwareFeatures.
//
// Each Constraint should specify exactly one HardwareFeature to constrain.
// Constraints are OR'd across the same type of HardwareFeatures, and AND'd
// across different types of HardwareFeatures. For example, the following
// specifies CLAMSHELL or CONVERTIBLE form factors are allowed, and the
// screen must have touch support:
//
//   design_config_constraints: <
//     level: REQUIRED
//     features: <
//       form_factor: <
//         form_factor: CLAMSHELL
//       >
//     >
//   >
//   design_config_constraints: <
//     level: REQUIRED
//     features: <
//       form_factor: <
//         form_factor: CONVERTIBLE
//       >
//     >
//   >
//   design_config_constraints: <
//     level: REQUIRED
//     features: <
//       screen: <
//         touch_support: PRESENT
//       >
//     >
//   >
//
// TODO: Formalize constraint definitions further, e.g. what are the
// semantics of level?
// TODO: should this be moved into Design or Program? This isn't used here
type Design_Config_Constraint struct {
	Level                Design_Config_Constraint_Level `protobuf:"varint,1,opt,name=level,proto3,enum=chromiumos.config.api.Design_Config_Constraint_Level" json:"level,omitempty"`
	Features             *HardwareFeatures              `protobuf:"bytes,2,opt,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Design_Config_Constraint) Reset()         { *m = Design_Config_Constraint{} }
func (m *Design_Config_Constraint) String() string { return proto.CompactTextString(m) }
func (*Design_Config_Constraint) ProtoMessage()    {}
func (*Design_Config_Constraint) Descriptor() ([]byte, []int) {
	return fileDescriptor_0949ab302cb28294, []int{0, 1, 0}
}

func (m *Design_Config_Constraint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Design_Config_Constraint.Unmarshal(m, b)
}
func (m *Design_Config_Constraint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Design_Config_Constraint.Marshal(b, m, deterministic)
}
func (m *Design_Config_Constraint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Design_Config_Constraint.Merge(m, src)
}
func (m *Design_Config_Constraint) XXX_Size() int {
	return xxx_messageInfo_Design_Config_Constraint.Size(m)
}
func (m *Design_Config_Constraint) XXX_DiscardUnknown() {
	xxx_messageInfo_Design_Config_Constraint.DiscardUnknown(m)
}

var xxx_messageInfo_Design_Config_Constraint proto.InternalMessageInfo

func (m *Design_Config_Constraint) GetLevel() Design_Config_Constraint_Level {
	if m != nil {
		return m.Level
	}
	return Design_Config_Constraint_TYPE_UNKNOWN
}

func (m *Design_Config_Constraint) GetFeatures() *HardwareFeatures {
	if m != nil {
		return m.Features
	}
	return nil
}

func init() {
	proto.RegisterEnum("chromiumos.config.api.Design_Config_Constraint_Level", Design_Config_Constraint_Level_name, Design_Config_Constraint_Level_value)
	proto.RegisterType((*Design)(nil), "chromiumos.config.api.Design")
	proto.RegisterMapType((map[uint32]string)(nil), "chromiumos.config.api.Design.BoardIdPhaseEntry")
	proto.RegisterType((*Design_Config)(nil), "chromiumos.config.api.Design.Config")
	proto.RegisterType((*Design_Config_Constraint)(nil), "chromiumos.config.api.Design.Config.Constraint")
}

func init() { proto.RegisterFile("chromiumos/config/api/design.proto", fileDescriptor_0949ab302cb28294) }

var fileDescriptor_0949ab302cb28294 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xdd, 0x6e, 0xd3, 0x3e,
	0x18, 0xc6, 0xff, 0xfd, 0x48, 0x97, 0x7a, 0x1f, 0xca, 0xac, 0x3f, 0x52, 0xd4, 0x13, 0xaa, 0x69,
	0x83, 0x0a, 0x41, 0x22, 0x0d, 0x4d, 0x43, 0x48, 0x30, 0xb1, 0x2d, 0x13, 0xd9, 0xa6, 0x2e, 0x58,
	0x9d, 0x10, 0x9c, 0x44, 0x6e, 0xed, 0xa5, 0x16, 0x69, 0x1c, 0x39, 0xe9, 0xd0, 0x6e, 0x90, 0x63,
	0x2e, 0x82, 0x0b, 0x41, 0xb1, 0xb3, 0x66, 0x34, 0x69, 0x00, 0x89, 0x33, 0xe7, 0xe9, 0xef, 0x79,
	0xfc, 0xfa, 0xf5, 0x5b, 0x83, 0x9d, 0xc9, 0x54, 0xf0, 0x19, 0x9b, 0xcf, 0x78, 0x62, 0x4f, 0x78,
	0x74, 0xc3, 0x02, 0x1b, 0xc7, 0xcc, 0x26, 0x34, 0x61, 0x41, 0x64, 0xc5, 0x82, 0xa7, 0x1c, 0x3e,
	0x2a, 0x18, 0x4b, 0x31, 0x16, 0x8e, 0x59, 0xef, 0x79, 0x9d, 0xd5, 0x57, 0x8a, 0xcf, 0x88, 0x0a,
	0xe9, 0xed, 0xd5, 0xd2, 0x0b, 0xec, 0x45, 0x35, 0x36, 0xc5, 0x82, 0x7c, 0xc5, 0x82, 0xfa, 0x29,
	0x8f, 0x79, 0xc8, 0x83, 0xbb, 0x1c, 0x7f, 0x52, 0x8d, 0xc7, 0x58, 0xa4, 0x11, 0x15, 0x45, 0xec,
	0x2a, 0x4e, 0xf0, 0x40, 0xe0, 0x59, 0xc1, 0xed, 0x56, 0x73, 0x4b, 0xbb, 0xbe, 0x29, 0x53, 0xf1,
	0x7c, 0x1c, 0xb2, 0x89, 0x2f, 0x68, 0x1c, 0xb2, 0x09, 0x4e, 0x19, 0x8f, 0x2a, 0x24, 0x65, 0xdf,
	0xf9, 0xae, 0x83, 0xce, 0xa9, 0x3c, 0x37, 0xbc, 0x01, 0xb0, 0x8c, 0x99, 0x6b, 0xfd, 0xc6, 0x60,
	0x7d, 0xff, 0xd0, 0x2a, 0xf7, 0xbd, 0x22, 0xd3, 0x93, 0x12, 0x2a, 0x14, 0xb4, 0x1d, 0x2f, 0x4b,
	0xd0, 0x06, 0x4d, 0x46, 0xcc, 0x86, 0xcc, 0x7d, 0x6c, 0x55, 0xde, 0xa7, 0xa5, 0x4a, 0x72, 0x09,
	0x6a, 0x32, 0x02, 0x8f, 0x00, 0x28, 0x9a, 0x63, 0x36, 0xa5, 0xb1, 0xbf, 0xc2, 0xe8, 0x29, 0xd0,
	0x25, 0xa8, 0x1b, 0xdf, 0x2f, 0xe1, 0x21, 0xe8, 0x70, 0x22, 0xcd, 0xad, 0x7a, 0xb3, 0xba, 0x2a,
	0x97, 0x20, 0x8d, 0x93, 0xcc, 0x08, 0x41, 0x3b, 0xc2, 0x33, 0x6a, 0xb6, 0xfb, 0x8d, 0x41, 0x17,
	0xc9, 0x35, 0xbc, 0x06, 0x5b, 0x63, 0x8e, 0x05, 0xf1, 0x19, 0xf1, 0xe3, 0x29, 0x4e, 0xa8, 0xa9,
	0xf5, 0x5b, 0x83, 0xf5, 0x7d, 0xbb, 0xf6, 0x28, 0xd6, 0x71, 0xe6, 0x71, 0x89, 0x97, 0x39, 0x9c,
	0x28, 0x15, 0x77, 0x68, 0x63, 0xfc, 0x40, 0x82, 0x6f, 0xc1, 0x9a, 0x32, 0x25, 0x66, 0x47, 0xe6,
	0xed, 0xd6, 0xe7, 0x9d, 0x48, 0x05, 0xdd, 0x9b, 0x7a, 0x47, 0x60, 0xbb, 0xb4, 0x05, 0x34, 0x40,
	0xeb, 0x0b, 0xbd, 0x93, 0xbd, 0xde, 0x44, 0xd9, 0x12, 0xfe, 0x0f, 0xb4, 0x5b, 0x1c, 0xce, 0xa9,
	0x6c, 0x63, 0x17, 0xa9, 0x8f, 0xd7, 0xcd, 0x57, 0x8d, 0xde, 0xb7, 0x36, 0xe8, 0xa8, 0xd0, 0x15,
	0x93, 0xa0, 0xfd, 0xf3, 0x49, 0x38, 0x78, 0x30, 0x09, 0x7b, 0xb5, 0xc7, 0x55, 0x85, 0xe5, 0xf3,
	0x30, 0x02, 0xdb, 0xa5, 0xff, 0x60, 0x3e, 0x16, 0x4f, 0x57, 0xa4, 0xbc, 0xcf, 0xf9, 0x51, 0x8e,
	0x23, 0x63, 0xba, 0xa4, 0xfc, 0x92, 0x7a, 0x43, 0x71, 0x3a, 0x17, 0x34, 0xc9, 0xe7, 0xe5, 0x77,
	0xa9, 0x67, 0x39, 0x5e, 0xa4, 0xde, 0x2b, 0xbd, 0x1f, 0x0d, 0x00, 0x4e, 0x78, 0x94, 0xa4, 0x02,
	0xb3, 0x28, 0x85, 0x17, 0x40, 0x0b, 0xe9, 0x2d, 0x0d, 0xe5, 0xa1, 0xb7, 0xf6, 0x0f, 0xfe, 0xe4,
	0x8e, 0xad, 0xc2, 0x6f, 0x5d, 0x66, 0x66, 0xa4, 0x32, 0xe0, 0x09, 0xd0, 0x17, 0x85, 0x36, 0xff,
	0xae, 0xd0, 0x85, 0x71, 0xe7, 0x14, 0x68, 0x32, 0x14, 0x1a, 0x60, 0x63, 0xf4, 0xc9, 0x73, 0xfc,
	0xeb, 0xe1, 0xc5, 0xf0, 0xea, 0xe3, 0xd0, 0xf8, 0x0f, 0x6e, 0x00, 0x1d, 0x39, 0x1f, 0xae, 0x5d,
	0xe4, 0x9c, 0x1a, 0x0d, 0xb8, 0x09, 0xba, 0x1e, 0x72, 0xce, 0x1c, 0x94, 0x7d, 0x36, 0xb3, 0x1f,
	0xaf, 0xbc, 0x91, 0x7b, 0x35, 0x7c, 0x77, 0x69, 0xb4, 0xce, 0xdb, 0x7a, 0xdb, 0xd0, 0xce, 0xdb,
	0xfa, 0x9a, 0xa1, 0x1f, 0x3f, 0xfb, 0x3c, 0x08, 0xf8, 0xa2, 0x10, 0x8b, 0x8b, 0xc0, 0x2e, 0xbf,
	0x51, 0x01, 0xcf, 0x1e, 0xb3, 0x71, 0x47, 0xbe, 0x42, 0x2f, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x7f, 0x81, 0x2e, 0x22, 0xfb, 0x05, 0x00, 0x00,
}
