// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/config/api/partner.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Defines contributing partners participating in the design, execution,
// and support of chromiumos projects.
type Partner struct {
	// Globally unique partner identifier.
	Id *PartnerId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Descriptive name (for humans) of the partner.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Email alias used for coordinating project execution.
	EmailGroup string `protobuf:"bytes,3,opt,name=email_group,json=emailGroup,proto3" json:"email_group,omitempty"`
	// Optional config for touch vendors.
	TouchVendor *Partner_TouchVendor `protobuf:"bytes,4,opt,name=touch_vendor,json=touchVendor,proto3" json:"touch_vendor,omitempty"`
	// Optional config for display panel vendors.
	DisplayPanelVendor *Partner_DisplayPanelVendor `protobuf:"bytes,5,opt,name=display_panel_vendor,json=displayPanelVendor,proto3" json:"display_panel_vendor,omitempty"`
	// Optional config for battery vendors.
	BatteryVendor        *Partner_BatteryVendor `protobuf:"bytes,6,opt,name=battery_vendor,json=batteryVendor,proto3" json:"battery_vendor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Partner) Reset()         { *m = Partner{} }
func (m *Partner) String() string { return proto.CompactTextString(m) }
func (*Partner) ProtoMessage()    {}
func (*Partner) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee55753238000786, []int{0}
}

func (m *Partner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partner.Unmarshal(m, b)
}
func (m *Partner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partner.Marshal(b, m, deterministic)
}
func (m *Partner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partner.Merge(m, src)
}
func (m *Partner) XXX_Size() int {
	return xxx_messageInfo_Partner.Size(m)
}
func (m *Partner) XXX_DiscardUnknown() {
	xxx_messageInfo_Partner.DiscardUnknown(m)
}

var xxx_messageInfo_Partner proto.InternalMessageInfo

func (m *Partner) GetId() *PartnerId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Partner) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Partner) GetEmailGroup() string {
	if m != nil {
		return m.EmailGroup
	}
	return ""
}

func (m *Partner) GetTouchVendor() *Partner_TouchVendor {
	if m != nil {
		return m.TouchVendor
	}
	return nil
}

func (m *Partner) GetDisplayPanelVendor() *Partner_DisplayPanelVendor {
	if m != nil {
		return m.DisplayPanelVendor
	}
	return nil
}

func (m *Partner) GetBatteryVendor() *Partner_BatteryVendor {
	if m != nil {
		return m.BatteryVendor
	}
	return nil
}

// Defines partner config unique to touch manufacturers.
type Partner_TouchVendor struct {
	// 4-digit hex vendor id assigned
	VendorId string `protobuf:"bytes,4,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	// This formatting (via python format) will be applied to the symlinks
	// that will be present in /lib/firmware
	// E.g.
	// "{vendor_name}_{product_id}.bin"
	// "{vendor_name}_{vendor_id}_{product_id}_{fw_version}.bin"
	// "{vendor_name}_{product_series}_{product_id}.hex"
	SymlinkFileFormat string `protobuf:"bytes,5,opt,name=symlink_file_format,json=symlinkFileFormat,proto3" json:"symlink_file_format,omitempty"`
	// Same formatting as symlink_file_format, except this controls
	// the actual destination file that will be written to
	// /opt/google/touch/firmware, which the symlink references.
	DestinationFileFormat string   `protobuf:"bytes,6,opt,name=destination_file_format,json=destinationFileFormat,proto3" json:"destination_file_format,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Partner_TouchVendor) Reset()         { *m = Partner_TouchVendor{} }
func (m *Partner_TouchVendor) String() string { return proto.CompactTextString(m) }
func (*Partner_TouchVendor) ProtoMessage()    {}
func (*Partner_TouchVendor) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee55753238000786, []int{0, 0}
}

func (m *Partner_TouchVendor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partner_TouchVendor.Unmarshal(m, b)
}
func (m *Partner_TouchVendor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partner_TouchVendor.Marshal(b, m, deterministic)
}
func (m *Partner_TouchVendor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partner_TouchVendor.Merge(m, src)
}
func (m *Partner_TouchVendor) XXX_Size() int {
	return xxx_messageInfo_Partner_TouchVendor.Size(m)
}
func (m *Partner_TouchVendor) XXX_DiscardUnknown() {
	xxx_messageInfo_Partner_TouchVendor.DiscardUnknown(m)
}

var xxx_messageInfo_Partner_TouchVendor proto.InternalMessageInfo

func (m *Partner_TouchVendor) GetVendorId() string {
	if m != nil {
		return m.VendorId
	}
	return ""
}

func (m *Partner_TouchVendor) GetSymlinkFileFormat() string {
	if m != nil {
		return m.SymlinkFileFormat
	}
	return ""
}

func (m *Partner_TouchVendor) GetDestinationFileFormat() string {
	if m != nil {
		return m.DestinationFileFormat
	}
	return ""
}

// Defines partner config unique to display panel manufacturers.
type Partner_DisplayPanelVendor struct {
	// Vendor code assigned (generally 3 char [A-Z])
	VendorCode           string   `protobuf:"bytes,1,opt,name=vendor_code,json=vendorCode,proto3" json:"vendor_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partner_DisplayPanelVendor) Reset()         { *m = Partner_DisplayPanelVendor{} }
func (m *Partner_DisplayPanelVendor) String() string { return proto.CompactTextString(m) }
func (*Partner_DisplayPanelVendor) ProtoMessage()    {}
func (*Partner_DisplayPanelVendor) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee55753238000786, []int{0, 1}
}

func (m *Partner_DisplayPanelVendor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partner_DisplayPanelVendor.Unmarshal(m, b)
}
func (m *Partner_DisplayPanelVendor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partner_DisplayPanelVendor.Marshal(b, m, deterministic)
}
func (m *Partner_DisplayPanelVendor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partner_DisplayPanelVendor.Merge(m, src)
}
func (m *Partner_DisplayPanelVendor) XXX_Size() int {
	return xxx_messageInfo_Partner_DisplayPanelVendor.Size(m)
}
func (m *Partner_DisplayPanelVendor) XXX_DiscardUnknown() {
	xxx_messageInfo_Partner_DisplayPanelVendor.DiscardUnknown(m)
}

var xxx_messageInfo_Partner_DisplayPanelVendor proto.InternalMessageInfo

func (m *Partner_DisplayPanelVendor) GetVendorCode() string {
	if m != nil {
		return m.VendorCode
	}
	return ""
}

// Defines partner config unique to battery manufacturers.
type Partner_BatteryVendor struct {
	// Vendor name assigned (generally 16 char)
	VendorName           string   `protobuf:"bytes,4,opt,name=vendor_name,json=vendorName,proto3" json:"vendor_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partner_BatteryVendor) Reset()         { *m = Partner_BatteryVendor{} }
func (m *Partner_BatteryVendor) String() string { return proto.CompactTextString(m) }
func (*Partner_BatteryVendor) ProtoMessage()    {}
func (*Partner_BatteryVendor) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee55753238000786, []int{0, 2}
}

func (m *Partner_BatteryVendor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partner_BatteryVendor.Unmarshal(m, b)
}
func (m *Partner_BatteryVendor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partner_BatteryVendor.Marshal(b, m, deterministic)
}
func (m *Partner_BatteryVendor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partner_BatteryVendor.Merge(m, src)
}
func (m *Partner_BatteryVendor) XXX_Size() int {
	return xxx_messageInfo_Partner_BatteryVendor.Size(m)
}
func (m *Partner_BatteryVendor) XXX_DiscardUnknown() {
	xxx_messageInfo_Partner_BatteryVendor.DiscardUnknown(m)
}

var xxx_messageInfo_Partner_BatteryVendor proto.InternalMessageInfo

func (m *Partner_BatteryVendor) GetVendorName() string {
	if m != nil {
		return m.VendorName
	}
	return ""
}

func init() {
	proto.RegisterType((*Partner)(nil), "chromiumos.config.api.Partner")
	proto.RegisterType((*Partner_TouchVendor)(nil), "chromiumos.config.api.Partner.TouchVendor")
	proto.RegisterType((*Partner_DisplayPanelVendor)(nil), "chromiumos.config.api.Partner.DisplayPanelVendor")
	proto.RegisterType((*Partner_BatteryVendor)(nil), "chromiumos.config.api.Partner.BatteryVendor")
}

func init() {
	proto.RegisterFile("chromiumos/config/api/partner.proto", fileDescriptor_ee55753238000786)
}

var fileDescriptor_ee55753238000786 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xd1, 0x6a, 0xdb, 0x30,
	0x14, 0x86, 0x71, 0xe6, 0x65, 0xf3, 0xf1, 0x32, 0x98, 0xb6, 0x30, 0xe3, 0x5d, 0x2c, 0x6c, 0x30,
	0x42, 0x18, 0x72, 0xb6, 0xb1, 0x3d, 0x40, 0x56, 0x52, 0x72, 0xd1, 0x12, 0xdc, 0xd2, 0x8b, 0xde,
	0x18, 0xc5, 0x52, 0x1c, 0x51, 0x5b, 0x32, 0xb2, 0x52, 0xc8, 0x6b, 0xf4, 0x65, 0x7b, 0x5b, 0x2c,
	0x39, 0x8d, 0x43, 0x4a, 0x72, 0x67, 0xfd, 0xe7, 0x7c, 0xbf, 0x7c, 0x8e, 0x7e, 0xf8, 0x9e, 0xae,
	0x94, 0x2c, 0xf8, 0xba, 0x90, 0x55, 0x94, 0x4a, 0xb1, 0xe4, 0x59, 0x44, 0x4a, 0x1e, 0x95, 0x44,
	0x69, 0xc1, 0x14, 0x2e, 0x95, 0xd4, 0x12, 0xf5, 0x77, 0x4d, 0xd8, 0x36, 0x61, 0x52, 0xf2, 0xf0,
	0xc7, 0x51, 0x36, 0xe1, 0xd4, 0xe2, 0xdf, 0x1e, 0x5d, 0x78, 0x33, 0xb7, 0x22, 0x1a, 0x43, 0x87,
	0xd3, 0xc0, 0x19, 0x38, 0x43, 0xff, 0xf7, 0x00, 0xbf, 0xe8, 0x8b, 0x9b, 0xde, 0x19, 0x8d, 0x3b,
	0x9c, 0x22, 0x04, 0xae, 0x20, 0x05, 0x0b, 0x3a, 0x03, 0x67, 0xe8, 0xc5, 0xe6, 0x1b, 0x7d, 0x05,
	0x9f, 0x15, 0x84, 0xe7, 0x49, 0xa6, 0xe4, 0xba, 0x0c, 0x5e, 0x99, 0x12, 0x18, 0xe9, 0xbc, 0x56,
	0xd0, 0x05, 0xbc, 0xd3, 0x72, 0x9d, 0xae, 0x92, 0x7b, 0x26, 0xa8, 0x54, 0x81, 0x6b, 0x2e, 0x1c,
	0x1d, 0xbf, 0x10, 0x5f, 0xd7, 0xc8, 0x8d, 0x21, 0x62, 0x5f, 0xef, 0x0e, 0x28, 0x85, 0x4f, 0x94,
	0x57, 0x65, 0x4e, 0x36, 0x49, 0x49, 0x04, 0xcb, 0xb7, 0xb6, 0xaf, 0x8d, 0xed, 0xaf, 0x13, 0xb6,
	0x67, 0x16, 0x9d, 0xd7, 0x64, 0xe3, 0x8e, 0xe8, 0x81, 0x86, 0xae, 0xe0, 0xfd, 0x82, 0x68, 0xcd,
	0xd4, 0x66, 0x6b, 0xdf, 0x35, 0xf6, 0x3f, 0x4f, 0xd8, 0x4f, 0x2c, 0xd4, 0x38, 0xf7, 0x16, 0xed,
	0x63, 0xf8, 0xe0, 0x80, 0xdf, 0x1a, 0x0b, 0x7d, 0x01, 0xcf, 0x9a, 0x27, 0x9c, 0x9a, 0xad, 0x78,
	0xf1, 0x5b, 0x2b, 0xcc, 0x28, 0xc2, 0xf0, 0xb1, 0xda, 0x14, 0x39, 0x17, 0x77, 0xc9, 0x92, 0xe7,
	0x2c, 0x59, 0x4a, 0x55, 0x10, 0x6d, 0xa6, 0xf4, 0xe2, 0x0f, 0x4d, 0x69, 0xca, 0x73, 0x36, 0x35,
	0x05, 0xf4, 0x0f, 0x3e, 0x53, 0x56, 0x69, 0x2e, 0x88, 0xe6, 0x52, 0xec, 0x31, 0x5d, 0xc3, 0xf4,
	0x5b, 0xe5, 0x1d, 0x17, 0xfe, 0x05, 0x74, 0xb8, 0x93, 0xfa, 0x51, 0x9b, 0x5f, 0x4b, 0x25, 0x65,
	0x26, 0x23, 0x5e, 0x0c, 0x56, 0xfa, 0x2f, 0x29, 0x0b, 0xc7, 0xd0, 0xdb, 0x9b, 0xb5, 0x45, 0x98,
	0x84, 0xb8, 0x6d, 0xe2, 0x92, 0x14, 0x6c, 0x32, 0xba, 0x1d, 0x66, 0xf2, 0x79, 0x7d, 0x58, 0xaa,
	0x2c, 0x3a, 0xcc, 0x6c, 0x26, 0xeb, 0xd8, 0x2e, 0xba, 0x26, 0xac, 0x7f, 0x9e, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x31, 0xf2, 0x25, 0xd3, 0x12, 0x03, 0x00, 0x00,
}
