// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/config/api/program.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Defines how space in firmware configuration is allocated.
//
// Every FirmwareConfiguration must specify a mask that aligns with a segment.
// No segments in a program can overlap.
type FirmwareConfigurationSegment struct {
	// Human-readable name describing the segment, e.g. "Daughter board".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The mask of valid bits that could be used by this type of Topology.
	Mask                 uint32   `protobuf:"varint,2,opt,name=mask,proto3" json:"mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirmwareConfigurationSegment) Reset()         { *m = FirmwareConfigurationSegment{} }
func (m *FirmwareConfigurationSegment) String() string { return proto.CompactTextString(m) }
func (*FirmwareConfigurationSegment) ProtoMessage()    {}
func (*FirmwareConfigurationSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce3b73f3bd54421, []int{0}
}

func (m *FirmwareConfigurationSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirmwareConfigurationSegment.Unmarshal(m, b)
}
func (m *FirmwareConfigurationSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirmwareConfigurationSegment.Marshal(b, m, deterministic)
}
func (m *FirmwareConfigurationSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirmwareConfigurationSegment.Merge(m, src)
}
func (m *FirmwareConfigurationSegment) XXX_Size() int {
	return xxx_messageInfo_FirmwareConfigurationSegment.Size(m)
}
func (m *FirmwareConfigurationSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_FirmwareConfigurationSegment.DiscardUnknown(m)
}

var xxx_messageInfo_FirmwareConfigurationSegment proto.InternalMessageInfo

func (m *FirmwareConfigurationSegment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FirmwareConfigurationSegment) GetMask() uint32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

// A segment of DesignConfigIds allocated to a given Design.
//
// To ensure that DesignConfigIds are unique within a Program, a segment can be
// allocated to each Design. For example, Design "A" gets ids [11, 20], Design
// "B" gets ids [21, 30], etc.
//
// No segments in a program can overlap.
type DesignConfigIdSegment struct {
	// Design the segment applies to.
	DesignId *DesignId `protobuf:"bytes,1,opt,name=design_id,json=designId,proto3" json:"design_id,omitempty"`
	// Min and max DesignConfigIds the Design can use. Both are inclusive.
	MinId                uint32   `protobuf:"varint,2,opt,name=min_id,json=minId,proto3" json:"min_id,omitempty"`
	MaxId                uint32   `protobuf:"varint,3,opt,name=max_id,json=maxId,proto3" json:"max_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DesignConfigIdSegment) Reset()         { *m = DesignConfigIdSegment{} }
func (m *DesignConfigIdSegment) String() string { return proto.CompactTextString(m) }
func (*DesignConfigIdSegment) ProtoMessage()    {}
func (*DesignConfigIdSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce3b73f3bd54421, []int{1}
}

func (m *DesignConfigIdSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesignConfigIdSegment.Unmarshal(m, b)
}
func (m *DesignConfigIdSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesignConfigIdSegment.Marshal(b, m, deterministic)
}
func (m *DesignConfigIdSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesignConfigIdSegment.Merge(m, src)
}
func (m *DesignConfigIdSegment) XXX_Size() int {
	return xxx_messageInfo_DesignConfigIdSegment.Size(m)
}
func (m *DesignConfigIdSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_DesignConfigIdSegment.DiscardUnknown(m)
}

var xxx_messageInfo_DesignConfigIdSegment proto.InternalMessageInfo

func (m *DesignConfigIdSegment) GetDesignId() *DesignId {
	if m != nil {
		return m.DesignId
	}
	return nil
}

func (m *DesignConfigIdSegment) GetMinId() uint32 {
	if m != nil {
		return m.MinId
	}
	return 0
}

func (m *DesignConfigIdSegment) GetMaxId() uint32 {
	if m != nil {
		return m.MaxId
	}
	return 0
}

// Defines the signing key that will be used for a given device brand.
type DeviceSignerConfig struct {
	BrandId              *DeviceBrandId `protobuf:"bytes,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	KeyId                string         `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeviceSignerConfig) Reset()         { *m = DeviceSignerConfig{} }
func (m *DeviceSignerConfig) String() string { return proto.CompactTextString(m) }
func (*DeviceSignerConfig) ProtoMessage()    {}
func (*DeviceSignerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce3b73f3bd54421, []int{2}
}

func (m *DeviceSignerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceSignerConfig.Unmarshal(m, b)
}
func (m *DeviceSignerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceSignerConfig.Marshal(b, m, deterministic)
}
func (m *DeviceSignerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceSignerConfig.Merge(m, src)
}
func (m *DeviceSignerConfig) XXX_Size() int {
	return xxx_messageInfo_DeviceSignerConfig.Size(m)
}
func (m *DeviceSignerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceSignerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceSignerConfig proto.InternalMessageInfo

func (m *DeviceSignerConfig) GetBrandId() *DeviceBrandId {
	if m != nil {
		return m.BrandId
	}
	return nil
}

func (m *DeviceSignerConfig) GetKeyId() string {
	if m != nil {
		return m.KeyId
	}
	return ""
}

// Defines a Chromium OS program, which establishes the set of constraints and
// guidelines for all hardware design projects developed under the given
// program.
//
// Reference designs developed for a given program will be treated like any
// other hardware design project.  They will either fully comply with the
// prescribed program constraints or provide waivers that highlight any
// constraint violations.
type Program struct {
	// Globally unique program identifier.
	Id *ProgramId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Program codename (human friendly).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Defines program constraints for all proposed design configs.
	DesignConfigConstraints []*Design_Config_Constraint `protobuf:"bytes,3,rep,name=design_config_constraints,json=designConfigConstraints,proto3" json:"design_config_constraints,omitempty"`
	// Components for the given program and their corresponding qualification
	// status.
	ComponentQuals []*Component_Qualification `protobuf:"bytes,4,rep,name=component_quals,json=componentQuals,proto3" json:"component_quals,omitempty"`
	// Firmware segment allocations for the given program.
	FirmwareConfigurationSegments []*FirmwareConfigurationSegment `protobuf:"bytes,5,rep,name=firmware_configuration_segments,json=firmwareConfigurationSegments,proto3" json:"firmware_configuration_segments,omitempty"`
	// DesignConfigId segment allocations for the given program.
	DesignConfigIdSegments []*DesignConfigIdSegment `protobuf:"bytes,7,rep,name=design_config_id_segments,json=designConfigIdSegments,proto3" json:"design_config_id_segments,omitempty"`
	DeviceSignerConfigs    []*DeviceSignerConfig    `protobuf:"bytes,6,rep,name=device_signer_configs,json=deviceSignerConfigs,proto3" json:"device_signer_configs,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                 `json:"-"`
	XXX_unrecognized       []byte                   `json:"-"`
	XXX_sizecache          int32                    `json:"-"`
}

func (m *Program) Reset()         { *m = Program{} }
func (m *Program) String() string { return proto.CompactTextString(m) }
func (*Program) ProtoMessage()    {}
func (*Program) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce3b73f3bd54421, []int{3}
}

func (m *Program) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Program.Unmarshal(m, b)
}
func (m *Program) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Program.Marshal(b, m, deterministic)
}
func (m *Program) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Program.Merge(m, src)
}
func (m *Program) XXX_Size() int {
	return xxx_messageInfo_Program.Size(m)
}
func (m *Program) XXX_DiscardUnknown() {
	xxx_messageInfo_Program.DiscardUnknown(m)
}

var xxx_messageInfo_Program proto.InternalMessageInfo

func (m *Program) GetId() *ProgramId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Program) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Program) GetDesignConfigConstraints() []*Design_Config_Constraint {
	if m != nil {
		return m.DesignConfigConstraints
	}
	return nil
}

func (m *Program) GetComponentQuals() []*Component_Qualification {
	if m != nil {
		return m.ComponentQuals
	}
	return nil
}

func (m *Program) GetFirmwareConfigurationSegments() []*FirmwareConfigurationSegment {
	if m != nil {
		return m.FirmwareConfigurationSegments
	}
	return nil
}

func (m *Program) GetDesignConfigIdSegments() []*DesignConfigIdSegment {
	if m != nil {
		return m.DesignConfigIdSegments
	}
	return nil
}

func (m *Program) GetDeviceSignerConfigs() []*DeviceSignerConfig {
	if m != nil {
		return m.DeviceSignerConfigs
	}
	return nil
}

type ProgramList struct {
	Value                []*Program `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProgramList) Reset()         { *m = ProgramList{} }
func (m *ProgramList) String() string { return proto.CompactTextString(m) }
func (*ProgramList) ProtoMessage()    {}
func (*ProgramList) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce3b73f3bd54421, []int{4}
}

func (m *ProgramList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProgramList.Unmarshal(m, b)
}
func (m *ProgramList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProgramList.Marshal(b, m, deterministic)
}
func (m *ProgramList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProgramList.Merge(m, src)
}
func (m *ProgramList) XXX_Size() int {
	return xxx_messageInfo_ProgramList.Size(m)
}
func (m *ProgramList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProgramList.DiscardUnknown(m)
}

var xxx_messageInfo_ProgramList proto.InternalMessageInfo

func (m *ProgramList) GetValue() []*Program {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*FirmwareConfigurationSegment)(nil), "chromiumos.config.api.FirmwareConfigurationSegment")
	proto.RegisterType((*DesignConfigIdSegment)(nil), "chromiumos.config.api.DesignConfigIdSegment")
	proto.RegisterType((*DeviceSignerConfig)(nil), "chromiumos.config.api.DeviceSignerConfig")
	proto.RegisterType((*Program)(nil), "chromiumos.config.api.Program")
	proto.RegisterType((*ProgramList)(nil), "chromiumos.config.api.ProgramList")
}

func init() {
	proto.RegisterFile("chromiumos/config/api/program.proto", fileDescriptor_dce3b73f3bd54421)
}

var fileDescriptor_dce3b73f3bd54421 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x5d, 0x8b, 0x13, 0x31,
	0x14, 0xa5, 0xdf, 0xdb, 0x14, 0x15, 0x22, 0xd5, 0x71, 0x51, 0xb7, 0x8c, 0xae, 0xd4, 0x0f, 0x66,
	0x64, 0xd7, 0x47, 0x41, 0xd8, 0x2e, 0x0b, 0x03, 0x3e, 0x68, 0xf6, 0x41, 0x10, 0xa4, 0xa4, 0x93,
	0x74, 0x0c, 0x6d, 0x92, 0x31, 0x99, 0x59, 0x77, 0xf1, 0xd1, 0x7f, 0xe9, 0xaf, 0x91, 0x7c, 0x74,
	0x5a, 0x76, 0x3b, 0xf3, 0x34, 0xe1, 0xf6, 0xdc, 0x73, 0xee, 0x3d, 0x3d, 0x09, 0x78, 0x91, 0xfe,
	0x54, 0x92, 0xb3, 0x92, 0x4b, 0x1d, 0xa7, 0x52, 0x2c, 0x59, 0x16, 0xe3, 0x9c, 0xc5, 0xb9, 0x92,
	0x99, 0xc2, 0x3c, 0xca, 0x95, 0x2c, 0x24, 0x1c, 0x6f, 0x41, 0x91, 0x03, 0x45, 0x38, 0x67, 0x87,
	0xc7, 0xfb, 0x7b, 0x53, 0xc9, 0x73, 0x29, 0xa8, 0x28, 0x5c, 0xf7, 0x61, 0xb8, 0x1f, 0x46, 0xa8,
	0x66, 0x99, 0xf0, 0x98, 0xe3, 0x26, 0xcc, 0x9c, 0x11, 0x0f, 0x7b, 0x5b, 0x07, 0xbb, 0x62, 0x29,
	0x9d, 0x2f, 0x14, 0x16, 0x64, 0x0b, 0x7e, 0xd5, 0xb8, 0x5a, 0x85, 0x0b, 0x2f, 0xc0, 0xd3, 0x0b,
	0xa6, 0xf8, 0x6f, 0xac, 0xe8, 0xcc, 0xc2, 0x4a, 0x85, 0x0b, 0x26, 0xc5, 0x25, 0xcd, 0x38, 0x15,
	0x05, 0x84, 0xa0, 0x2b, 0x30, 0xa7, 0x41, 0x6b, 0xd2, 0x9a, 0x0e, 0x91, 0x3d, 0x9b, 0x1a, 0xc7,
	0x7a, 0x15, 0xb4, 0x27, 0xad, 0xe9, 0x3d, 0x64, 0xcf, 0xe1, 0xdf, 0x16, 0x18, 0x9f, 0xdb, 0x81,
	0x1d, 0x4d, 0x42, 0x36, 0x0c, 0x1f, 0xc1, 0xb0, 0xda, 0xc4, 0xd2, 0x8c, 0x4e, 0x8e, 0xa2, 0xbd,
	0x9e, 0x46, 0x8e, 0x20, 0x21, 0xe8, 0x80, 0xf8, 0x13, 0x1c, 0x83, 0x3e, 0x67, 0xb6, 0xd5, 0xa9,
	0xf5, 0x38, 0xdb, 0x94, 0xf1, 0xb5, 0x29, 0x77, 0x7c, 0x19, 0x5f, 0x27, 0x24, 0x5c, 0x03, 0x78,
	0x6e, 0xed, 0xb8, 0x64, 0x99, 0xa0, 0xca, 0x8d, 0x02, 0x3f, 0x81, 0x83, 0x8d, 0x3b, 0x7e, 0x80,
	0x97, 0xb5, 0x03, 0x98, 0xe6, 0x33, 0x03, 0x4e, 0x08, 0x1a, 0x2c, 0xdc, 0xc1, 0xa8, 0xad, 0xe8,
	0xcd, 0x66, 0x88, 0x21, 0xea, 0xad, 0xe8, 0x4d, 0x42, 0xc2, 0x7f, 0x5d, 0x30, 0xf8, 0xe2, 0x0c,
	0x85, 0xef, 0x41, 0xbb, 0x62, 0x9f, 0xd4, 0xb0, 0x7b, 0x6c, 0x42, 0x50, 0x9b, 0x91, 0xca, 0xd9,
	0xf6, 0x8e, 0xb3, 0x2b, 0xf0, 0xc4, 0x7b, 0xe5, 0xda, 0xcc, 0x47, 0x17, 0x0a, 0x33, 0x51, 0xe8,
	0xa0, 0x33, 0xe9, 0x4c, 0x47, 0x27, 0x71, 0xa3, 0x77, 0x91, 0x5b, 0xd9, 0x7c, 0x7c, 0x1f, 0x7a,
	0x4c, 0x76, 0xfe, 0x96, 0x6d, 0x5d, 0xc3, 0x6f, 0xe0, 0x41, 0x95, 0xd6, 0xf9, 0xaf, 0x12, 0xaf,
	0x75, 0xd0, 0xb5, 0x12, 0x51, 0x8d, 0xc4, 0xac, 0xca, 0xf6, 0xd7, 0x12, 0xaf, 0xd9, 0x92, 0xa5,
	0x36, 0x2a, 0xe8, 0x7e, 0x45, 0x63, 0xea, 0x1a, 0xfe, 0x01, 0x47, 0x4b, 0x9f, 0x29, 0xbf, 0x87,
	0x0f, 0xd5, 0x5c, 0xbb, 0x4c, 0xe8, 0xa0, 0x67, 0x85, 0x4e, 0x6b, 0x84, 0x9a, 0x12, 0x89, 0x9e,
	0x2d, 0x1b, 0x7e, 0xd5, 0x30, 0xbb, 0x6d, 0x21, 0x23, 0x5b, 0xd9, 0x81, 0x95, 0x7d, 0xd7, 0x68,
	0xe1, 0xad, 0xfc, 0xa2, 0x47, 0x64, 0x5f, 0x59, 0xc3, 0x1f, 0x60, 0xec, 0xaf, 0x9e, 0xb6, 0x61,
	0xf3, 0x7a, 0x3a, 0xe8, 0x5b, 0x91, 0xd7, 0x8d, 0x11, 0xdb, 0xcd, 0x27, 0x7a, 0x48, 0xee, 0xd4,
	0x74, 0x38, 0x03, 0x23, 0x9f, 0x97, 0xcf, 0x4c, 0x17, 0xf0, 0x03, 0xe8, 0x5d, 0xe1, 0x75, 0x69,
	0x2e, 0xa2, 0x61, 0x7f, 0xde, 0x1c, 0x31, 0xe4, 0xc0, 0x67, 0x6f, 0xbe, 0x4f, 0x33, 0x59, 0x41,
	0x23, 0xa9, 0xb2, 0xf8, 0xee, 0xbb, 0x90, 0x49, 0xf3, 0x34, 0x2c, 0xfa, 0xf6, 0x41, 0x38, 0xfd,
	0x1f, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x83, 0xc3, 0xaf, 0x15, 0x05, 0x00, 0x00,
}
