// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/config/prototype/build_target.proto

package prototype

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Defines different build targets and corresponding parameters that will be
// provided for a given build invocation.
type BuildTarget struct {
	Id *BuildTargetId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to TargetConfig:
	//	*BuildTarget_Firmware_
	//	*BuildTarget_System_
	//	*BuildTarget_Factory_
	TargetConfig         isBuildTarget_TargetConfig `protobuf_oneof:"target_config"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BuildTarget) Reset()         { *m = BuildTarget{} }
func (m *BuildTarget) String() string { return proto.CompactTextString(m) }
func (*BuildTarget) ProtoMessage()    {}
func (*BuildTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5ee88c325d6d75, []int{0}
}

func (m *BuildTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTarget.Unmarshal(m, b)
}
func (m *BuildTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTarget.Marshal(b, m, deterministic)
}
func (m *BuildTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTarget.Merge(m, src)
}
func (m *BuildTarget) XXX_Size() int {
	return xxx_messageInfo_BuildTarget.Size(m)
}
func (m *BuildTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTarget.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTarget proto.InternalMessageInfo

func (m *BuildTarget) GetId() *BuildTargetId {
	if m != nil {
		return m.Id
	}
	return nil
}

type isBuildTarget_TargetConfig interface {
	isBuildTarget_TargetConfig()
}

type BuildTarget_Firmware_ struct {
	Firmware *BuildTarget_Firmware `protobuf:"bytes,2,opt,name=firmware,proto3,oneof"`
}

type BuildTarget_System_ struct {
	System *BuildTarget_System `protobuf:"bytes,3,opt,name=system,proto3,oneof"`
}

type BuildTarget_Factory_ struct {
	Factory *BuildTarget_Factory `protobuf:"bytes,4,opt,name=factory,proto3,oneof"`
}

func (*BuildTarget_Firmware_) isBuildTarget_TargetConfig() {}

func (*BuildTarget_System_) isBuildTarget_TargetConfig() {}

func (*BuildTarget_Factory_) isBuildTarget_TargetConfig() {}

func (m *BuildTarget) GetTargetConfig() isBuildTarget_TargetConfig {
	if m != nil {
		return m.TargetConfig
	}
	return nil
}

func (m *BuildTarget) GetFirmware() *BuildTarget_Firmware {
	if x, ok := m.GetTargetConfig().(*BuildTarget_Firmware_); ok {
		return x.Firmware
	}
	return nil
}

func (m *BuildTarget) GetSystem() *BuildTarget_System {
	if x, ok := m.GetTargetConfig().(*BuildTarget_System_); ok {
		return x.System
	}
	return nil
}

func (m *BuildTarget) GetFactory() *BuildTarget_Factory {
	if x, ok := m.GetTargetConfig().(*BuildTarget_Factory_); ok {
		return x.Factory
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BuildTarget) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BuildTarget_Firmware_)(nil),
		(*BuildTarget_System_)(nil),
		(*BuildTarget_Factory_)(nil),
	}
}

// Firmware build target config and parameters for a given firmware build
// invocation.
type BuildTarget_Firmware struct {
	Ec *BuildTarget_Firmware_Ec `protobuf:"bytes,1,opt,name=ec,proto3" json:"ec,omitempty"`
	Ap *BuildTarget_Firmware_Ap `protobuf:"bytes,2,opt,name=ap,proto3" json:"ap,omitempty"`
	// Currently firmware uses portage, but this could be changed if the fw
	// build archticture changed (decoupled from portage).
	PortageConfig        *BuildTarget_PortageConfig `protobuf:"bytes,3,opt,name=portage_config,json=portageConfig,proto3" json:"portage_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BuildTarget_Firmware) Reset()         { *m = BuildTarget_Firmware{} }
func (m *BuildTarget_Firmware) String() string { return proto.CompactTextString(m) }
func (*BuildTarget_Firmware) ProtoMessage()    {}
func (*BuildTarget_Firmware) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5ee88c325d6d75, []int{0, 0}
}

func (m *BuildTarget_Firmware) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTarget_Firmware.Unmarshal(m, b)
}
func (m *BuildTarget_Firmware) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTarget_Firmware.Marshal(b, m, deterministic)
}
func (m *BuildTarget_Firmware) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTarget_Firmware.Merge(m, src)
}
func (m *BuildTarget_Firmware) XXX_Size() int {
	return xxx_messageInfo_BuildTarget_Firmware.Size(m)
}
func (m *BuildTarget_Firmware) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTarget_Firmware.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTarget_Firmware proto.InternalMessageInfo

func (m *BuildTarget_Firmware) GetEc() *BuildTarget_Firmware_Ec {
	if m != nil {
		return m.Ec
	}
	return nil
}

func (m *BuildTarget_Firmware) GetAp() *BuildTarget_Firmware_Ap {
	if m != nil {
		return m.Ap
	}
	return nil
}

func (m *BuildTarget_Firmware) GetPortageConfig() *BuildTarget_PortageConfig {
	if m != nil {
		return m.PortageConfig
	}
	return nil
}

type BuildTarget_Firmware_Ec struct {
	// Build target of the base EC firmware for a detachable device
	Base string `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Main ec build target
	Ec string `protobuf:"bytes,2,opt,name=ec,proto3" json:"ec,omitempty"`
	// List of optional components to include in the EC build
	Extras               []string `protobuf:"bytes,3,rep,name=extras,proto3" json:"extras,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildTarget_Firmware_Ec) Reset()         { *m = BuildTarget_Firmware_Ec{} }
func (m *BuildTarget_Firmware_Ec) String() string { return proto.CompactTextString(m) }
func (*BuildTarget_Firmware_Ec) ProtoMessage()    {}
func (*BuildTarget_Firmware_Ec) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5ee88c325d6d75, []int{0, 0, 0}
}

func (m *BuildTarget_Firmware_Ec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTarget_Firmware_Ec.Unmarshal(m, b)
}
func (m *BuildTarget_Firmware_Ec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTarget_Firmware_Ec.Marshal(b, m, deterministic)
}
func (m *BuildTarget_Firmware_Ec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTarget_Firmware_Ec.Merge(m, src)
}
func (m *BuildTarget_Firmware_Ec) XXX_Size() int {
	return xxx_messageInfo_BuildTarget_Firmware_Ec.Size(m)
}
func (m *BuildTarget_Firmware_Ec) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTarget_Firmware_Ec.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTarget_Firmware_Ec proto.InternalMessageInfo

func (m *BuildTarget_Firmware_Ec) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *BuildTarget_Firmware_Ec) GetEc() string {
	if m != nil {
		return m.Ec
	}
	return ""
}

func (m *BuildTarget_Firmware_Ec) GetExtras() []string {
	if m != nil {
		return m.Extras
	}
	return nil
}

type BuildTarget_Firmware_Ap struct {
	Coreboot             string   `protobuf:"bytes,1,opt,name=coreboot,proto3" json:"coreboot,omitempty"`
	Gsc                  string   `protobuf:"bytes,2,opt,name=gsc,proto3" json:"gsc,omitempty"`
	Depthcharge          string   `protobuf:"bytes,3,opt,name=depthcharge,proto3" json:"depthcharge,omitempty"`
	Ish                  string   `protobuf:"bytes,4,opt,name=ish,proto3" json:"ish,omitempty"`
	Libpayload           string   `protobuf:"bytes,5,opt,name=libpayload,proto3" json:"libpayload,omitempty"`
	UBoot                string   `protobuf:"bytes,6,opt,name=u_boot,json=uBoot,proto3" json:"u_boot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildTarget_Firmware_Ap) Reset()         { *m = BuildTarget_Firmware_Ap{} }
func (m *BuildTarget_Firmware_Ap) String() string { return proto.CompactTextString(m) }
func (*BuildTarget_Firmware_Ap) ProtoMessage()    {}
func (*BuildTarget_Firmware_Ap) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5ee88c325d6d75, []int{0, 0, 1}
}

func (m *BuildTarget_Firmware_Ap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTarget_Firmware_Ap.Unmarshal(m, b)
}
func (m *BuildTarget_Firmware_Ap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTarget_Firmware_Ap.Marshal(b, m, deterministic)
}
func (m *BuildTarget_Firmware_Ap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTarget_Firmware_Ap.Merge(m, src)
}
func (m *BuildTarget_Firmware_Ap) XXX_Size() int {
	return xxx_messageInfo_BuildTarget_Firmware_Ap.Size(m)
}
func (m *BuildTarget_Firmware_Ap) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTarget_Firmware_Ap.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTarget_Firmware_Ap proto.InternalMessageInfo

func (m *BuildTarget_Firmware_Ap) GetCoreboot() string {
	if m != nil {
		return m.Coreboot
	}
	return ""
}

func (m *BuildTarget_Firmware_Ap) GetGsc() string {
	if m != nil {
		return m.Gsc
	}
	return ""
}

func (m *BuildTarget_Firmware_Ap) GetDepthcharge() string {
	if m != nil {
		return m.Depthcharge
	}
	return ""
}

func (m *BuildTarget_Firmware_Ap) GetIsh() string {
	if m != nil {
		return m.Ish
	}
	return ""
}

func (m *BuildTarget_Firmware_Ap) GetLibpayload() string {
	if m != nil {
		return m.Libpayload
	}
	return ""
}

func (m *BuildTarget_Firmware_Ap) GetUBoot() string {
	if m != nil {
		return m.UBoot
	}
	return ""
}

type BuildTarget_System struct {
	PortageConfig        *BuildTarget_PortageConfig `protobuf:"bytes,1,opt,name=portage_config,json=portageConfig,proto3" json:"portage_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BuildTarget_System) Reset()         { *m = BuildTarget_System{} }
func (m *BuildTarget_System) String() string { return proto.CompactTextString(m) }
func (*BuildTarget_System) ProtoMessage()    {}
func (*BuildTarget_System) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5ee88c325d6d75, []int{0, 1}
}

func (m *BuildTarget_System) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTarget_System.Unmarshal(m, b)
}
func (m *BuildTarget_System) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTarget_System.Marshal(b, m, deterministic)
}
func (m *BuildTarget_System) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTarget_System.Merge(m, src)
}
func (m *BuildTarget_System) XXX_Size() int {
	return xxx_messageInfo_BuildTarget_System.Size(m)
}
func (m *BuildTarget_System) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTarget_System.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTarget_System proto.InternalMessageInfo

func (m *BuildTarget_System) GetPortageConfig() *BuildTarget_PortageConfig {
	if m != nil {
		return m.PortageConfig
	}
	return nil
}

type BuildTarget_Factory struct {
	PortageConfig        *BuildTarget_PortageConfig `protobuf:"bytes,1,opt,name=portage_config,json=portageConfig,proto3" json:"portage_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BuildTarget_Factory) Reset()         { *m = BuildTarget_Factory{} }
func (m *BuildTarget_Factory) String() string { return proto.CompactTextString(m) }
func (*BuildTarget_Factory) ProtoMessage()    {}
func (*BuildTarget_Factory) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5ee88c325d6d75, []int{0, 2}
}

func (m *BuildTarget_Factory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTarget_Factory.Unmarshal(m, b)
}
func (m *BuildTarget_Factory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTarget_Factory.Marshal(b, m, deterministic)
}
func (m *BuildTarget_Factory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTarget_Factory.Merge(m, src)
}
func (m *BuildTarget_Factory) XXX_Size() int {
	return xxx_messageInfo_BuildTarget_Factory.Size(m)
}
func (m *BuildTarget_Factory) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTarget_Factory.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTarget_Factory proto.InternalMessageInfo

func (m *BuildTarget_Factory) GetPortageConfig() *BuildTarget_PortageConfig {
	if m != nil {
		return m.PortageConfig
	}
	return nil
}

// Defines the portage specific configuration for a given build target.
type BuildTarget_PortageConfig struct {
	OverlayName          string   `protobuf:"bytes,1,opt,name=overlay_name,json=overlayName,proto3" json:"overlay_name,omitempty"`
	ProfileName          string   `protobuf:"bytes,2,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	UseFlags             []string `protobuf:"bytes,3,rep,name=use_flags,json=useFlags,proto3" json:"use_flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildTarget_PortageConfig) Reset()         { *m = BuildTarget_PortageConfig{} }
func (m *BuildTarget_PortageConfig) String() string { return proto.CompactTextString(m) }
func (*BuildTarget_PortageConfig) ProtoMessage()    {}
func (*BuildTarget_PortageConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd5ee88c325d6d75, []int{0, 3}
}

func (m *BuildTarget_PortageConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTarget_PortageConfig.Unmarshal(m, b)
}
func (m *BuildTarget_PortageConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTarget_PortageConfig.Marshal(b, m, deterministic)
}
func (m *BuildTarget_PortageConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTarget_PortageConfig.Merge(m, src)
}
func (m *BuildTarget_PortageConfig) XXX_Size() int {
	return xxx_messageInfo_BuildTarget_PortageConfig.Size(m)
}
func (m *BuildTarget_PortageConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTarget_PortageConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTarget_PortageConfig proto.InternalMessageInfo

func (m *BuildTarget_PortageConfig) GetOverlayName() string {
	if m != nil {
		return m.OverlayName
	}
	return ""
}

func (m *BuildTarget_PortageConfig) GetProfileName() string {
	if m != nil {
		return m.ProfileName
	}
	return ""
}

func (m *BuildTarget_PortageConfig) GetUseFlags() []string {
	if m != nil {
		return m.UseFlags
	}
	return nil
}

func init() {
	proto.RegisterType((*BuildTarget)(nil), "chromiumos.config.prototype.BuildTarget")
	proto.RegisterType((*BuildTarget_Firmware)(nil), "chromiumos.config.prototype.BuildTarget.Firmware")
	proto.RegisterType((*BuildTarget_Firmware_Ec)(nil), "chromiumos.config.prototype.BuildTarget.Firmware.Ec")
	proto.RegisterType((*BuildTarget_Firmware_Ap)(nil), "chromiumos.config.prototype.BuildTarget.Firmware.Ap")
	proto.RegisterType((*BuildTarget_System)(nil), "chromiumos.config.prototype.BuildTarget.System")
	proto.RegisterType((*BuildTarget_Factory)(nil), "chromiumos.config.prototype.BuildTarget.Factory")
	proto.RegisterType((*BuildTarget_PortageConfig)(nil), "chromiumos.config.prototype.BuildTarget.PortageConfig")
}

func init() {
	proto.RegisterFile("chromiumos/config/prototype/build_target.proto", fileDescriptor_dd5ee88c325d6d75)
}

var fileDescriptor_dd5ee88c325d6d75 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xdd, 0x8a, 0xd4, 0x30,
	0x14, 0xc7, 0x67, 0x3a, 0xbb, 0xdd, 0x99, 0x53, 0x67, 0x95, 0x80, 0x52, 0xba, 0x20, 0xa3, 0x57,
	0x8b, 0x17, 0xe9, 0xae, 0x8a, 0x17, 0x5e, 0xb9, 0xa3, 0xbb, 0xcc, 0x82, 0xa8, 0x44, 0xaf, 0x04,
	0x29, 0x69, 0x9b, 0xb6, 0x81, 0x76, 0x13, 0xd2, 0x54, 0xed, 0xc3, 0xf8, 0x5c, 0x3e, 0x81, 0xef,
	0x21, 0x4d, 0xd3, 0xd9, 0x11, 0x45, 0xaa, 0xe8, 0x5d, 0xce, 0xc7, 0xff, 0x97, 0xf3, 0x11, 0x02,
	0x38, 0x29, 0x94, 0xa8, 0x78, 0x53, 0x89, 0x3a, 0x4c, 0xc4, 0x55, 0xc6, 0xf3, 0x50, 0x2a, 0xa1,
	0x85, 0x6e, 0x25, 0x0b, 0xe3, 0x86, 0x97, 0x69, 0xa4, 0xa9, 0xca, 0x99, 0xc6, 0xc6, 0x8d, 0x8e,
	0xae, 0xf3, 0x71, 0x9f, 0x8f, 0xb7, 0xf9, 0xc1, 0xe9, 0x58, 0x58, 0xc4, 0xd3, 0x5e, 0x76, 0xff,
	0xdb, 0x1c, 0xbc, 0x75, 0x17, 0x79, 0x67, 0x02, 0xe8, 0x29, 0x38, 0x3c, 0xf5, 0xa7, 0xab, 0xe9,
	0xb1, 0xf7, 0xf0, 0x01, 0xfe, 0xcd, 0x65, 0x78, 0x47, 0x75, 0x99, 0x12, 0x87, 0xa7, 0xe8, 0x35,
	0xcc, 0x33, 0xae, 0xaa, 0x4f, 0x54, 0x31, 0xdf, 0x31, 0x84, 0xd3, 0xb1, 0x04, 0x7c, 0x61, 0x85,
	0x9b, 0x09, 0xd9, 0x42, 0xd0, 0x25, 0xb8, 0x75, 0x5b, 0x6b, 0x56, 0xf9, 0x33, 0x83, 0x0b, 0x47,
	0xe3, 0xde, 0x1a, 0xd9, 0x66, 0x42, 0x2c, 0x00, 0xbd, 0x84, 0x83, 0x8c, 0x26, 0x5a, 0xa8, 0xd6,
	0xdf, 0x33, 0xac, 0x93, 0xf1, 0xa5, 0xf5, 0xba, 0xcd, 0x84, 0x0c, 0x88, 0xe0, 0xeb, 0x0c, 0xe6,
	0x43, 0xc5, 0xe8, 0x05, 0x38, 0x2c, 0xb1, 0x23, 0x7b, 0xfc, 0xc7, 0x0d, 0xe3, 0xf3, 0x84, 0x38,
	0x2c, 0xe9, 0x28, 0x54, 0xda, 0xb1, 0xfd, 0x05, 0xe5, 0x4c, 0x12, 0x87, 0x4a, 0xf4, 0x01, 0x0e,
	0xa5, 0x50, 0x9a, 0xe6, 0x2c, 0xea, 0x75, 0x76, 0x72, 0x4f, 0x46, 0x13, 0xdf, 0xf4, 0xf2, 0xe7,
	0x26, 0x87, 0x2c, 0xe5, 0xae, 0x19, 0x3c, 0x03, 0xe7, 0x3c, 0x41, 0x08, 0xf6, 0x62, 0x5a, 0x33,
	0xd3, 0xf2, 0x82, 0x98, 0x33, 0x3a, 0x34, 0x43, 0x70, 0x8c, 0xa7, 0x6b, 0xe7, 0x0e, 0xb8, 0xec,
	0xb3, 0x56, 0xb4, 0xf6, 0x67, 0xab, 0xd9, 0xf1, 0x82, 0x58, 0x2b, 0xf8, 0x32, 0x05, 0xe7, 0x4c,
	0xa2, 0x00, 0xe6, 0x89, 0x50, 0x2c, 0x16, 0x42, 0x5b, 0xcc, 0xd6, 0x46, 0xb7, 0x60, 0x96, 0xd7,
	0x03, 0xab, 0x3b, 0xa2, 0x15, 0x78, 0x29, 0x93, 0xba, 0x48, 0x8a, 0xae, 0x46, 0xd3, 0xd2, 0x82,
	0xec, 0xba, 0x3a, 0x0d, 0xaf, 0x0b, 0xb3, 0xda, 0x05, 0xe9, 0x8e, 0xe8, 0x2e, 0x40, 0xc9, 0x63,
	0x49, 0xdb, 0x52, 0xd0, 0xd4, 0xdf, 0x37, 0x81, 0x1d, 0x0f, 0xba, 0x0d, 0x6e, 0x13, 0x99, 0xfb,
	0x5d, 0x13, 0xdb, 0x6f, 0xd6, 0x42, 0xe8, 0x20, 0x07, 0xb7, 0x7f, 0x3b, 0xbf, 0x18, 0xe5, 0xf4,
	0x5f, 0x8e, 0xb2, 0x80, 0x03, 0xfb, 0xb0, 0xfe, 0xf7, 0x4d, 0x0a, 0x96, 0x3f, 0xc4, 0xd1, 0x3d,
	0xb8, 0x21, 0x3e, 0x32, 0x55, 0xd2, 0x36, 0xba, 0xa2, 0xd5, 0xb0, 0x47, 0xcf, 0xfa, 0x5e, 0xd1,
	0x8a, 0x75, 0x29, 0x52, 0x89, 0x8c, 0x97, 0xac, 0x4f, 0xe9, 0x97, 0xe1, 0x59, 0x9f, 0x49, 0x39,
	0x82, 0x45, 0x53, 0xb3, 0x28, 0x2b, 0x69, 0x3e, 0x2c, 0x79, 0xde, 0xd4, 0xec, 0xa2, 0xb3, 0xd7,
	0x37, 0x61, 0x69, 0x7f, 0x9a, 0xbe, 0xee, 0xf5, 0xc9, 0x7b, 0x9c, 0x8b, 0x6d, 0x3f, 0x58, 0xa8,
	0x3c, 0xfc, 0xf9, 0xb3, 0xca, 0xc5, 0xf5, 0x7f, 0x15, 0xbb, 0xe6, 0xf8, 0xe8, 0x7b, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x9c, 0x68, 0x27, 0xce, 0x22, 0x05, 0x00, 0x00,
}
