syntax = "proto3";

package chromiumos.config.api;

import "src/config/proto/brand_config.proto";
import "src/config/proto/build_target_id.proto";
import "src/config/proto/design_config_build_payload.proto";

// Specifies all configuration for a build.
message BuildConfig {
  // Base build target.
  chromiumos_config.BuildTargetId build_target_id = 1;

  // Config for all unique hw design configs supported by the build.
  //
  // For a "fan-in" build, many design configs can be supported by the same
  // build, e.g. the config for each design config doesn't contain confidential
  // information, so it is acceptable for owners of different variants to see
  // each others' configs.
  //
  // For a "fan-out" build, each config will get a different build, e.g. to
  // allow owners of variants to keep config private.
  //
  // Builds between these two extremes are also possible, e.g. configs A and
  // B share a build, while configs C gets a different build.
  repeated chromiumos_config.DesignConfigBuildPayload build_payloads = 2;

  // Branding config for all devices supported by the build.
  //
  // This list is not necessarily the same length as <build_payloads>.
  // At runtime, a device will search this list for its payload, and configure
  // itself based on the payload.
  repeated chromiumos_config.BrandConfig brand_configs = 3;
}

message BuildConfigList {
  repeated BuildConfig value = 1;
}
