syntax = "proto3";

package chromiumos_config;

option go_package = "go.chromium.org/chromiumos/config/go";

import "audio_config.proto";
import "firmware_config.proto";
import "bluetooth/config.proto";
import "chromeos_config/identity_scan_config.proto";
import "power_manager/config.proto";

// TODO(shapiroc): Delete after config is migrated.
message DesignConfigBuildPayload {
  chromeos_config.IdentityScanConfig.DesignConfigId scan_config = 1;

  firmware.FirmwareConfig firmware = 2;

  bluetooth.BluetoothConfig bluetooth_config = 3;

  power_manager.PowerManagerConfig power_manager_config = 4;

  AudioConfig audio_config = 5;
}
