// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/test/plan/source_test_plan.proto

package plan

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Different environments ChromeOS tests run in.
type SourceTestPlan_TestEnvironment int32

const (
	SourceTestPlan_TEST_TYPE_UNSPECIFIED SourceTestPlan_TestEnvironment = 0
	SourceTestPlan_HARDWWARE             SourceTestPlan_TestEnvironment = 1
	SourceTestPlan_VIRTUAL               SourceTestPlan_TestEnvironment = 2
)

var SourceTestPlan_TestEnvironment_name = map[int32]string{
	0: "TEST_TYPE_UNSPECIFIED",
	1: "HARDWWARE",
	2: "VIRTUAL",
}

var SourceTestPlan_TestEnvironment_value = map[string]int32{
	"TEST_TYPE_UNSPECIFIED": 0,
	"HARDWWARE":             1,
	"VIRTUAL":               2,
}

func (x SourceTestPlan_TestEnvironment) String() string {
	return proto.EnumName(SourceTestPlan_TestEnvironment_name, int32(x))
}

func (SourceTestPlan_TestEnvironment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28090e75a41618a0, []int{0, 0}
}

// Describes the test cases, software requirements, and hardware requirements
// that run when a given set of files are changed.
//
// This message contains high-level rules for test planning, e.g. "test on all
// kernel versions". This is then evaluated into a Specification message which
// contains attributes that must be tested; in the above example, this would be
// a list of kernel versions used by ChromeOS.
//
// This message is intended to be specified as a text proto in the source tree,
// and should be concise enough Starlark, or another config generation tool, is
// not needed.
type SourceTestPlan struct {
	// Test environments enabled for the test plan. Must contain at least one
	// test type.
	EnabledTestEnvironments []SourceTestPlan_TestEnvironment `protobuf:"varint,1,rep,packed,name=enabled_test_environments,json=enabledTestEnvironments,proto3,enum=chromiumos.test.plan.SourceTestPlan_TestEnvironment" json:"enabled_test_environments,omitempty"`
	// Paths that will trigger the SourceTestPlan.
	//
	// Must be a source-absolute ChromeOS path. For example,
	// “//src/platform2/arc/.*” for
	// https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/arc/,
	// based on the manifest’s repo to source path mapping.
	//
	// Paths can only match files in the subtree of the DIR_METADATA file.
	//
	// Patterns use Google Re2 syntax. The comparison is a full match. The pattern
	// is implicitly anchored with ^ and $, so there is no need to add them.
	//
	// If path_regexp is not specified, it is implied to be all files in
	// the directory of the DIR_METADATA file and all files in subdirectories.
	//
	// If a file is matched by both path_regexp and path_regexp_exclude, it is
	// excluded.
	PathRegexps        []string `protobuf:"bytes,2,rep,name=path_regexps,json=pathRegexps,proto3" json:"path_regexps,omitempty"`
	PathRegexpExcludes []string `protobuf:"bytes,3,rep,name=path_regexp_excludes,json=pathRegexpExcludes,proto3" json:"path_regexp_excludes,omitempty"`
	// Only run tests that have at least one of test_tags (if specified) and do
	// not have any of test_tag_excludes.
	//
	// Tags must match exactly (i.e. no regexp, wildcard, etc. allowed).
	TestTags             []string                       `protobuf:"bytes,4,rep,name=test_tags,json=testTags,proto3" json:"test_tags,omitempty"`
	TestTagExcludes      []string                       `protobuf:"bytes,5,rep,name=test_tag_excludes,json=testTagExcludes,proto3" json:"test_tag_excludes,omitempty"`
	KernelVersions       *SourceTestPlan_KernelVersions `protobuf:"bytes,6,opt,name=kernel_versions,json=kernelVersions,proto3" json:"kernel_versions,omitempty"`
	SocFamilies          *SourceTestPlan_SocFamilies    `protobuf:"bytes,7,opt,name=soc_families,json=socFamilies,proto3" json:"soc_families,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SourceTestPlan) Reset()         { *m = SourceTestPlan{} }
func (m *SourceTestPlan) String() string { return proto.CompactTextString(m) }
func (*SourceTestPlan) ProtoMessage()    {}
func (*SourceTestPlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_28090e75a41618a0, []int{0}
}

func (m *SourceTestPlan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceTestPlan.Unmarshal(m, b)
}
func (m *SourceTestPlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceTestPlan.Marshal(b, m, deterministic)
}
func (m *SourceTestPlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceTestPlan.Merge(m, src)
}
func (m *SourceTestPlan) XXX_Size() int {
	return xxx_messageInfo_SourceTestPlan.Size(m)
}
func (m *SourceTestPlan) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceTestPlan.DiscardUnknown(m)
}

var xxx_messageInfo_SourceTestPlan proto.InternalMessageInfo

func (m *SourceTestPlan) GetEnabledTestEnvironments() []SourceTestPlan_TestEnvironment {
	if m != nil {
		return m.EnabledTestEnvironments
	}
	return nil
}

func (m *SourceTestPlan) GetPathRegexps() []string {
	if m != nil {
		return m.PathRegexps
	}
	return nil
}

func (m *SourceTestPlan) GetPathRegexpExcludes() []string {
	if m != nil {
		return m.PathRegexpExcludes
	}
	return nil
}

func (m *SourceTestPlan) GetTestTags() []string {
	if m != nil {
		return m.TestTags
	}
	return nil
}

func (m *SourceTestPlan) GetTestTagExcludes() []string {
	if m != nil {
		return m.TestTagExcludes
	}
	return nil
}

func (m *SourceTestPlan) GetKernelVersions() *SourceTestPlan_KernelVersions {
	if m != nil {
		return m.KernelVersions
	}
	return nil
}

func (m *SourceTestPlan) GetSocFamilies() *SourceTestPlan_SocFamilies {
	if m != nil {
		return m.SocFamilies
	}
	return nil
}

// Run tests at least once on each kernel version.
type SourceTestPlan_KernelVersions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceTestPlan_KernelVersions) Reset()         { *m = SourceTestPlan_KernelVersions{} }
func (m *SourceTestPlan_KernelVersions) String() string { return proto.CompactTextString(m) }
func (*SourceTestPlan_KernelVersions) ProtoMessage()    {}
func (*SourceTestPlan_KernelVersions) Descriptor() ([]byte, []int) {
	return fileDescriptor_28090e75a41618a0, []int{0, 0}
}

func (m *SourceTestPlan_KernelVersions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceTestPlan_KernelVersions.Unmarshal(m, b)
}
func (m *SourceTestPlan_KernelVersions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceTestPlan_KernelVersions.Marshal(b, m, deterministic)
}
func (m *SourceTestPlan_KernelVersions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceTestPlan_KernelVersions.Merge(m, src)
}
func (m *SourceTestPlan_KernelVersions) XXX_Size() int {
	return xxx_messageInfo_SourceTestPlan_KernelVersions.Size(m)
}
func (m *SourceTestPlan_KernelVersions) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceTestPlan_KernelVersions.DiscardUnknown(m)
}

var xxx_messageInfo_SourceTestPlan_KernelVersions proto.InternalMessageInfo

// Run tests at least once on each SoC family.
type SourceTestPlan_SocFamilies struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceTestPlan_SocFamilies) Reset()         { *m = SourceTestPlan_SocFamilies{} }
func (m *SourceTestPlan_SocFamilies) String() string { return proto.CompactTextString(m) }
func (*SourceTestPlan_SocFamilies) ProtoMessage()    {}
func (*SourceTestPlan_SocFamilies) Descriptor() ([]byte, []int) {
	return fileDescriptor_28090e75a41618a0, []int{0, 1}
}

func (m *SourceTestPlan_SocFamilies) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceTestPlan_SocFamilies.Unmarshal(m, b)
}
func (m *SourceTestPlan_SocFamilies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceTestPlan_SocFamilies.Marshal(b, m, deterministic)
}
func (m *SourceTestPlan_SocFamilies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceTestPlan_SocFamilies.Merge(m, src)
}
func (m *SourceTestPlan_SocFamilies) XXX_Size() int {
	return xxx_messageInfo_SourceTestPlan_SocFamilies.Size(m)
}
func (m *SourceTestPlan_SocFamilies) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceTestPlan_SocFamilies.DiscardUnknown(m)
}

var xxx_messageInfo_SourceTestPlan_SocFamilies proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("chromiumos.test.plan.SourceTestPlan_TestEnvironment", SourceTestPlan_TestEnvironment_name, SourceTestPlan_TestEnvironment_value)
	proto.RegisterType((*SourceTestPlan)(nil), "chromiumos.test.plan.SourceTestPlan")
	proto.RegisterType((*SourceTestPlan_KernelVersions)(nil), "chromiumos.test.plan.SourceTestPlan.KernelVersions")
	proto.RegisterType((*SourceTestPlan_SocFamilies)(nil), "chromiumos.test.plan.SourceTestPlan.SocFamilies")
}

func init() {
	proto.RegisterFile("chromiumos/test/plan/source_test_plan.proto", fileDescriptor_28090e75a41618a0)
}

var fileDescriptor_28090e75a41618a0 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x51, 0xaf, 0x9a, 0x30,
	0x18, 0x86, 0xe7, 0xf1, 0xec, 0x9c, 0x59, 0x14, 0x59, 0xe3, 0x32, 0x74, 0x37, 0xce, 0x2b, 0xb3,
	0x25, 0xc5, 0xe8, 0xfe, 0x80, 0x9b, 0x18, 0xcd, 0x96, 0xc5, 0x14, 0xd4, 0x6c, 0x59, 0xd2, 0x20,
	0x56, 0x24, 0x42, 0x4b, 0x5a, 0x34, 0xfe, 0xba, 0xfd, 0xb6, 0x85, 0xca, 0x44, 0xcd, 0xb9, 0xf0,
	0x8e, 0xbe, 0xdf, 0xf3, 0x3e, 0x34, 0xf0, 0x81, 0xcf, 0xfe, 0x56, 0xf0, 0x38, 0xdc, 0xc7, 0x5c,
	0x5a, 0x29, 0x95, 0xa9, 0x95, 0x44, 0x1e, 0xb3, 0x24, 0xdf, 0x0b, 0x9f, 0x92, 0x2c, 0x20, 0x59,
	0x80, 0x12, 0xc1, 0x53, 0x0e, 0x1b, 0x05, 0x8c, 0xb2, 0x19, 0xca, 0x66, 0x9d, 0xbf, 0x8f, 0x40,
	0x77, 0x54, 0xc1, 0xa5, 0x32, 0x9d, 0x45, 0x1e, 0x83, 0x09, 0x68, 0x52, 0xe6, 0xad, 0x22, 0xba,
	0x3e, 0x39, 0x28, 0x3b, 0x84, 0x82, 0xb3, 0x98, 0xb2, 0x54, 0x9a, 0xa5, 0x76, 0xb9, 0xab, 0xf7,
	0xbf, 0xa0, 0x97, 0x64, 0xe8, 0x5a, 0x84, 0xb2, 0x07, 0xbb, 0x28, 0xe3, 0xf7, 0xb9, 0xf6, 0x26,
	0x97, 0xf0, 0x23, 0xa8, 0x26, 0x5e, 0xba, 0x25, 0x82, 0x06, 0xf4, 0x98, 0x48, 0xf3, 0xa1, 0x5d,
	0xee, 0x56, 0xb0, 0x96, 0x65, 0xf8, 0x14, 0xc1, 0x1e, 0x68, 0x5c, 0x20, 0x84, 0x1e, 0xfd, 0x68,
	0xbf, 0xa6, 0xd2, 0x2c, 0x2b, 0x14, 0x16, 0xa8, 0x9d, 0x4f, 0xe0, 0x07, 0x50, 0x51, 0xd7, 0x4f,
	0xbd, 0x40, 0x9a, 0x8f, 0x0a, 0x7b, 0x93, 0x05, 0xae, 0x17, 0x48, 0xf8, 0x09, 0xbc, 0xfd, 0x3f,
	0x2c, 0x5c, 0xaf, 0x15, 0x54, 0xcf, 0xa1, 0xb3, 0xe8, 0x0f, 0xa8, 0xef, 0xa8, 0x60, 0x34, 0x22,
	0x07, 0x2a, 0x64, 0xc8, 0x99, 0x34, 0x9f, 0xda, 0xa5, 0xae, 0xd6, 0x1f, 0xdc, 0xf5, 0x15, 0xbe,
	0xab, 0xee, 0x22, 0xaf, 0x62, 0x7d, 0x77, 0x75, 0x86, 0x0e, 0xa8, 0x4a, 0xee, 0x93, 0x8d, 0x17,
	0x87, 0x51, 0x48, 0xa5, 0xf9, 0xac, 0xd4, 0xbd, 0xbb, 0xd4, 0x0e, 0xf7, 0xc7, 0x79, 0x0f, 0x6b,
	0xb2, 0x38, 0xb4, 0x0c, 0xa0, 0x5f, 0xbf, 0xb6, 0x55, 0x03, 0xda, 0x05, 0xdd, 0x99, 0x80, 0xfa,
	0xcd, 0x5f, 0x80, 0x4d, 0xf0, 0xce, 0xb5, 0x1d, 0x97, 0xb8, 0xbf, 0x66, 0x36, 0x99, 0xff, 0x74,
	0x66, 0xf6, 0xb7, 0xe9, 0x78, 0x6a, 0x8f, 0x8c, 0x57, 0xb0, 0x06, 0x2a, 0x93, 0x21, 0x1e, 0x2d,
	0x97, 0x43, 0x6c, 0x1b, 0x25, 0xa8, 0x81, 0xe7, 0xc5, 0x14, 0xbb, 0xf3, 0xe1, 0x0f, 0xe3, 0xe1,
	0x6b, 0xef, 0x37, 0x0a, 0xf8, 0xf9, 0xb6, 0x88, 0x8b, 0xc0, 0xba, 0xd8, 0x4a, 0x9f, 0xb3, 0x4d,
	0x18, 0x58, 0x01, 0x2f, 0xf6, 0x73, 0xf5, 0xa4, 0xf6, 0x71, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x7a, 0x4c, 0x89, 0x9c, 0xbe, 0x02, 0x00, 0x00,
}
