// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.lab.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/lab/api";

import "chromiumos/config/api/device_config_id.proto";
import "chromiumos/test/lab/api/ip_endpoint.proto";

// Specification of Device Under Test.
message Dut {
  // Unique identifier for the lab device.
  message Id {
    string value = 1;
  }

  Id id = 1;

  oneof dut_type {
    ChromeOS chromeos = 2;
    Android android = 3;
  }

  // Chrome OS specific DUT details
  message ChromeOS {
    // Unique identifiers around the device's hardware, manufacturing, and brand
    // configuration.
    chromiumos.config.api.DeviceConfigId device_config_id = 3;
    // Endpoint for ssh service running on the device
    IpEndpoint ssh = 2;

    reserved 1;
  }

  // Android specific DUT details
  message Android {
  }
}

// Defines the topology of connected devices under test
message DutTopology {
  // Unique identifier for a given dut topology (schedulable lab unit)
  message Id {
    string value = 1;
  }
  Id id = 3;

  // Collection of devices that are used in a given test.
  // Generally, this will contain a single Dut for an functional test that
  // doesn't depend on other devices, but can include a collection of devices
  // used in multi-dut testing (e.g. ChromeOS to ChromeOS, ChromeOS to Android,
  // etc...)
  repeated Dut duts = 4;

  reserved 1, 2;
}

