// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.lab.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/lab/api";

import "chromiumos/config/api/mfg_config.proto";
import "chromiumos/test/lab/api/ip_endpoint.proto";

// Specification of Device Under Test.
message Dut {
  // Unique identifier for the lab device.
  message Id {
    string value = 1;
  }

  Id id = 1;

  oneof dut_type {
    ChromeOS chromeos = 2;
    Android android = 3;
  }

  // Chrome OS specific DUT details
  message ChromeOS {
    // Manufacturing hardware design/component details for a given device
    chromiumos.config.api.MfgConfig mfg_config = 1;
    // Endpoint for ssh service running on the device
    IpEndpoint ssh = 2;
  }

  // Android specific DUT details
  message Android {
  }
}

// Defines the testing topology for a given device under test
message DutTopology {
  // Primary device under test in the topology
  Dut dut = 1;
  // Secondary devices used for peer-to-peer testing.
  repeated Dut peer_duts = 2;
}

