// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.config.api;

option go_package = "go.chromium.org/chromiumos/config/go/api";

// Uniquely identifies a Chromium OS device brand.
message DeviceBrandId {
  string value = 1;

  // Scan config to determine the BrandId
  message ScanConfig {
    // 'whitelabel_tag' value set in the VPD.
    // See
    // https://chromeos.google.com/partner/dlm/docs/factory/vpd.html#field-whitelabel_tag.
    string whitelabel_tag = 1;
  }
}
