// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/test/internal/test_harness.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Defines a test execution framework that can execute test cases and report
// results.
type TestHarness struct {
	// Globally unique (for ChromeOS) identifier of a given test harness
	Id *TestHarness_Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to TestHarnessType:
	//	*TestHarness_Manual_
	//	*TestHarness_Tauto_
	//	*TestHarness_Tast_
	TestHarnessType      isTestHarness_TestHarnessType `protobuf_oneof:"test_harness_type"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *TestHarness) Reset()         { *m = TestHarness{} }
func (m *TestHarness) String() string { return proto.CompactTextString(m) }
func (*TestHarness) ProtoMessage()    {}
func (*TestHarness) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fa2e28e244e6b76, []int{0}
}

func (m *TestHarness) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestHarness.Unmarshal(m, b)
}
func (m *TestHarness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestHarness.Marshal(b, m, deterministic)
}
func (m *TestHarness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestHarness.Merge(m, src)
}
func (m *TestHarness) XXX_Size() int {
	return xxx_messageInfo_TestHarness.Size(m)
}
func (m *TestHarness) XXX_DiscardUnknown() {
	xxx_messageInfo_TestHarness.DiscardUnknown(m)
}

var xxx_messageInfo_TestHarness proto.InternalMessageInfo

func (m *TestHarness) GetId() *TestHarness_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

type isTestHarness_TestHarnessType interface {
	isTestHarness_TestHarnessType()
}

type TestHarness_Manual_ struct {
	Manual *TestHarness_Manual `protobuf:"bytes,2,opt,name=manual,proto3,oneof"`
}

type TestHarness_Tauto_ struct {
	Tauto *TestHarness_Tauto `protobuf:"bytes,3,opt,name=tauto,proto3,oneof"`
}

type TestHarness_Tast_ struct {
	Tast *TestHarness_Tast `protobuf:"bytes,4,opt,name=tast,proto3,oneof"`
}

func (*TestHarness_Manual_) isTestHarness_TestHarnessType() {}

func (*TestHarness_Tauto_) isTestHarness_TestHarnessType() {}

func (*TestHarness_Tast_) isTestHarness_TestHarnessType() {}

func (m *TestHarness) GetTestHarnessType() isTestHarness_TestHarnessType {
	if m != nil {
		return m.TestHarnessType
	}
	return nil
}

func (m *TestHarness) GetManual() *TestHarness_Manual {
	if x, ok := m.GetTestHarnessType().(*TestHarness_Manual_); ok {
		return x.Manual
	}
	return nil
}

func (m *TestHarness) GetTauto() *TestHarness_Tauto {
	if x, ok := m.GetTestHarnessType().(*TestHarness_Tauto_); ok {
		return x.Tauto
	}
	return nil
}

func (m *TestHarness) GetTast() *TestHarness_Tast {
	if x, ok := m.GetTestHarnessType().(*TestHarness_Tast_); ok {
		return x.Tast
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TestHarness) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TestHarness_Manual_)(nil),
		(*TestHarness_Tauto_)(nil),
		(*TestHarness_Tast_)(nil),
	}
}

type TestHarness_Id struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestHarness_Id) Reset()         { *m = TestHarness_Id{} }
func (m *TestHarness_Id) String() string { return proto.CompactTextString(m) }
func (*TestHarness_Id) ProtoMessage()    {}
func (*TestHarness_Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fa2e28e244e6b76, []int{0, 0}
}

func (m *TestHarness_Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestHarness_Id.Unmarshal(m, b)
}
func (m *TestHarness_Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestHarness_Id.Marshal(b, m, deterministic)
}
func (m *TestHarness_Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestHarness_Id.Merge(m, src)
}
func (m *TestHarness_Id) XXX_Size() int {
	return xxx_messageInfo_TestHarness_Id.Size(m)
}
func (m *TestHarness_Id) XXX_DiscardUnknown() {
	xxx_messageInfo_TestHarness_Id.DiscardUnknown(m)
}

var xxx_messageInfo_TestHarness_Id proto.InternalMessageInfo

func (m *TestHarness_Id) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TestHarness_Manual struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestHarness_Manual) Reset()         { *m = TestHarness_Manual{} }
func (m *TestHarness_Manual) String() string { return proto.CompactTextString(m) }
func (*TestHarness_Manual) ProtoMessage()    {}
func (*TestHarness_Manual) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fa2e28e244e6b76, []int{0, 1}
}

func (m *TestHarness_Manual) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestHarness_Manual.Unmarshal(m, b)
}
func (m *TestHarness_Manual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestHarness_Manual.Marshal(b, m, deterministic)
}
func (m *TestHarness_Manual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestHarness_Manual.Merge(m, src)
}
func (m *TestHarness_Manual) XXX_Size() int {
	return xxx_messageInfo_TestHarness_Manual.Size(m)
}
func (m *TestHarness_Manual) XXX_DiscardUnknown() {
	xxx_messageInfo_TestHarness_Manual.DiscardUnknown(m)
}

var xxx_messageInfo_TestHarness_Manual proto.InternalMessageInfo

type TestHarness_Tast struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestHarness_Tast) Reset()         { *m = TestHarness_Tast{} }
func (m *TestHarness_Tast) String() string { return proto.CompactTextString(m) }
func (*TestHarness_Tast) ProtoMessage()    {}
func (*TestHarness_Tast) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fa2e28e244e6b76, []int{0, 2}
}

func (m *TestHarness_Tast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestHarness_Tast.Unmarshal(m, b)
}
func (m *TestHarness_Tast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestHarness_Tast.Marshal(b, m, deterministic)
}
func (m *TestHarness_Tast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestHarness_Tast.Merge(m, src)
}
func (m *TestHarness_Tast) XXX_Size() int {
	return xxx_messageInfo_TestHarness_Tast.Size(m)
}
func (m *TestHarness_Tast) XXX_DiscardUnknown() {
	xxx_messageInfo_TestHarness_Tast.DiscardUnknown(m)
}

var xxx_messageInfo_TestHarness_Tast proto.InternalMessageInfo

type TestHarness_Tauto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestHarness_Tauto) Reset()         { *m = TestHarness_Tauto{} }
func (m *TestHarness_Tauto) String() string { return proto.CompactTextString(m) }
func (*TestHarness_Tauto) ProtoMessage()    {}
func (*TestHarness_Tauto) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fa2e28e244e6b76, []int{0, 3}
}

func (m *TestHarness_Tauto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestHarness_Tauto.Unmarshal(m, b)
}
func (m *TestHarness_Tauto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestHarness_Tauto.Marshal(b, m, deterministic)
}
func (m *TestHarness_Tauto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestHarness_Tauto.Merge(m, src)
}
func (m *TestHarness_Tauto) XXX_Size() int {
	return xxx_messageInfo_TestHarness_Tauto.Size(m)
}
func (m *TestHarness_Tauto) XXX_DiscardUnknown() {
	xxx_messageInfo_TestHarness_Tauto.DiscardUnknown(m)
}

var xxx_messageInfo_TestHarness_Tauto proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TestHarness)(nil), "chromiumos.test.internal.TestHarness")
	proto.RegisterType((*TestHarness_Id)(nil), "chromiumos.test.internal.TestHarness.Id")
	proto.RegisterType((*TestHarness_Manual)(nil), "chromiumos.test.internal.TestHarness.Manual")
	proto.RegisterType((*TestHarness_Tast)(nil), "chromiumos.test.internal.TestHarness.Tast")
	proto.RegisterType((*TestHarness_Tauto)(nil), "chromiumos.test.internal.TestHarness.Tauto")
}

func init() {
	proto.RegisterFile("chromiumos/test/internal/test_harness.proto", fileDescriptor_6fa2e28e244e6b76)
}

var fileDescriptor_6fa2e28e244e6b76 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x14, 0xc4, 0xd3, 0x90, 0x04, 0x78, 0x9d, 0x30, 0x0c, 0x96, 0x27, 0xc4, 0x54, 0x51, 0xe4, 0x48,
	0x85, 0x81, 0x11, 0x15, 0x09, 0xa5, 0x03, 0x8b, 0xd5, 0x89, 0xa5, 0x32, 0x8d, 0x49, 0x2d, 0x25,
	0x76, 0x65, 0xbf, 0x20, 0xf1, 0x75, 0xf9, 0x24, 0x28, 0x0e, 0x7f, 0xc2, 0x50, 0x29, 0xe3, 0xd3,
	0xbb, 0xdf, 0xe9, 0x74, 0x07, 0xf3, 0xed, 0xce, 0xd9, 0x46, 0xb7, 0x8d, 0xf5, 0x39, 0x2a, 0x8f,
	0xb9, 0x36, 0xa8, 0x9c, 0x91, 0x75, 0xb8, 0x36, 0x3b, 0xe9, 0x8c, 0xf2, 0x9e, 0xef, 0x9d, 0x45,
	0x4b, 0xe8, 0x9f, 0x98, 0x77, 0x6f, 0xfe, 0x23, 0xbe, 0xfa, 0x8c, 0x61, 0xba, 0x56, 0x1e, 0x8b,
	0x5e, 0x4f, 0xee, 0x21, 0xd6, 0x25, 0x9d, 0x5c, 0x4e, 0x66, 0xd3, 0xc5, 0x8c, 0x1f, 0xc2, 0xf8,
	0x00, 0xe1, 0xab, 0x52, 0xc4, 0xba, 0x24, 0x4f, 0x90, 0x35, 0xd2, 0xb4, 0xb2, 0xa6, 0x71, 0xa0,
	0x6f, 0xc6, 0xd1, 0xcf, 0x81, 0x29, 0x22, 0xf1, 0x4d, 0x93, 0x47, 0x48, 0x51, 0xb6, 0x68, 0xe9,
	0x51, 0xb0, 0x99, 0x8f, 0xb3, 0x59, 0x77, 0x48, 0x11, 0x89, 0x9e, 0x25, 0x0f, 0x90, 0xa0, 0xf4,
	0x48, 0x93, 0xe0, 0x71, 0x3d, 0xd6, 0xc3, 0x63, 0x11, 0x89, 0x40, 0x32, 0x06, 0xf1, 0xaa, 0x24,
	0x17, 0x90, 0xbe, 0xcb, 0xba, 0x55, 0xa1, 0x91, 0x53, 0xd1, 0x1f, 0xec, 0x04, 0xb2, 0x3e, 0x36,
	0xcb, 0x20, 0xe9, 0x28, 0x76, 0x0c, 0x69, 0x48, 0xb0, 0x3c, 0x87, 0xb3, 0x61, 0xff, 0x1b, 0xfc,
	0xd8, 0xab, 0xe5, 0xdd, 0xcb, 0xa2, 0xb2, 0xbf, 0x19, 0xb8, 0x75, 0x55, 0x3e, 0x58, 0x6f, 0x6b,
	0xcd, 0x9b, 0xae, 0xf2, 0xca, 0xfe, 0xdf, 0xf1, 0x35, 0x0b, 0xdb, 0xdd, 0x7e, 0x05, 0x00, 0x00,
	0xff, 0xff, 0xc1, 0xef, 0x53, 0xba, 0xea, 0x01, 0x00, 0x00,
}
