# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/config/prototype/prototype_config_bundle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromiumos.config.api.test.plan.v1 import plan_pb2 as chromiumos_dot_config_dot_api_dot_test_dot_plan_dot_v1_dot_plan__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/config/prototype/prototype_config_bundle.proto',
  package='chromiumos.config.prototype',
  syntax='proto3',
  serialized_options=_b('Z.go.chromium.org/chromiumos/config/go/prototype'),
  serialized_pb=_b('\n9chromiumos/config/prototype/prototype_config_bundle.proto\x12\x1b\x63hromiumos.config.prototype\x1a-chromiumos/config/api/test/plan/v1/plan.proto\"c\n\x15PrototypeConfigBundle\x12J\n\x0ftest_plan_specs\x18\x01 \x03(\x0b\x32\x31.chromiumos.config.api.test.plan.v1.SpecificationB0Z.go.chromium.org/chromiumos/config/go/prototypeb\x06proto3')
  ,
  dependencies=[chromiumos_dot_config_dot_api_dot_test_dot_plan_dot_v1_dot_plan__pb2.DESCRIPTOR,])




_PROTOTYPECONFIGBUNDLE = _descriptor.Descriptor(
  name='PrototypeConfigBundle',
  full_name='chromiumos.config.prototype.PrototypeConfigBundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_plan_specs', full_name='chromiumos.config.prototype.PrototypeConfigBundle.test_plan_specs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=236,
)

_PROTOTYPECONFIGBUNDLE.fields_by_name['test_plan_specs'].message_type = chromiumos_dot_config_dot_api_dot_test_dot_plan_dot_v1_dot_plan__pb2._SPECIFICATION
DESCRIPTOR.message_types_by_name['PrototypeConfigBundle'] = _PROTOTYPECONFIGBUNDLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrototypeConfigBundle = _reflection.GeneratedProtocolMessageType('PrototypeConfigBundle', (_message.Message,), dict(
  DESCRIPTOR = _PROTOTYPECONFIGBUNDLE,
  __module__ = 'chromiumos.config.prototype.prototype_config_bundle_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.config.prototype.PrototypeConfigBundle)
  ))
_sym_db.RegisterMessage(PrototypeConfigBundle)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
