// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

// Next Tag: 5
message GMSCoreApk {
  //Supported GMS Core architectures.
  enum Architecture {
    ARCHITECTURE_UNSPECIFIED = 0;
    ARMV7 = 1;
    ARM64 = 2;
    X86 = 3;
    X86_64 = 4;
  }
  Architecture architecture = 1;

  // Supported GMS Core build types.
  enum BuildType {
    BUILD_TYPE_UNSPECIFIED = 0;
    PHONE_PRE_LMP = 1;
    PHONE_LMP = 2;
    PHONE_MNC = 3;
    PHONE_PI = 4;
    PHONE_RVC = 5;
    PHONE_SC = 6;
    PHONE_NEXT = 7;
    PHONE_GO = 8;
    PHONE_GO_R = 9;
    PHONE_GO_S = 10;
  }
  BuildType build_type = 2;

  // Supported GMS Core build purposes.
  enum BuildPurpose {
    BUILD_PURPOSE_UNSPECIFIED = 0;
    RAW = 1;
    RELEASE = 2;
    DEBUG = 3;
    DEBUG_SHRUNK = 4;
  }
  BuildPurpose build_purpose = 3;

  // Supported GMS Core densities.
  enum Density {
    DENSITY_UNSPECIFIED = 0;
    MDPI = 1;
    HDPI = 2;
    XHDPI = 3;
    XXHDPI = 4;
    ALLDPI = 5;
  }
  Density density = 4;
}

// Next Tag: 7
message CIPDPackage {
  // Required. Name of a CIPD package to query instances.
  string name = 1;

  // Required. A CIPD package version.
  // Can be defined by ref, tag or specific instance Id.
  oneof version_oneof {
    string ref = 2;
    string tag = 3;
    string instance_id = 4;
  }

  // CIPD server to fetch this package from.
  // chrome-infra-packages.appspot.com is used by default.
  string server = 5;

  message CIPDPackageDetails {
    // List of supported CIPD packages.
    enum PackageType {
      PACKAGE_TYPE_UNSPECIFIED = 0;
      GMS_CORE_APK = 1;
    }
    // Required. Type of the package.
    PackageType package_type = 1;
    // Additional details about the package.
    oneof additional_info_oneof {
      GMSCoreApk gms_core_apk_details = 2;
    }
  }
  // Required. Details about the package.
  CIPDPackageDetails package_details = 6;
}

// Next Tag: 6
message AndroidDeviceProvisionMetadata {
  // Required. The resource name for the DUT.
  string name = 1;
  // Required. Serial number of the DUT.
  string serial_number = 2;
  // Required. Hostname to which the Android DUT is attached to.
  string associated_hostname = 3;
  // A list of adb keys (files or directories).
  repeated string adb_vendor_keys = 4;
  // Required. A list of CIPD packages which should be installed on the DUT.
  repeated CIPDPackage cipd_packages = 5;
}
