// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

// Next Tag: 5
message ApkDetails {
  // Supported Android architectures.
  enum Architecture {
    ARCHITECTURE_UNSPECIFIED = 0;
    ARMV7 = 1;
    ARM64 = 2;
    X86 = 3;
    X86_64 = 4;
  }
  Architecture architecture = 1;

  // Supported APK build types.
  enum BuildType {
    BUILD_TYPE_UNSPECIFIED = 0;
    PHONE_PRE_LMP = 1;
    PHONE_LMP = 2;
    PHONE_MNC = 3;
    PHONE_PI = 4;
    PHONE_RVC = 5;
    PHONE_SC = 6;
    PHONE_NEXT = 7;
    PHONE_GO = 8;
    PHONE_GO_R = 9;
    PHONE_GO_S = 10;
  }
  BuildType build_type = 2;

  // Supported APK build purposes.
  enum BuildPurpose {
    BUILD_PURPOSE_UNSPECIFIED = 0;
    RAW = 1;
    RELEASE = 2;
    DEBUG = 3;
    DEBUG_SHRUNK = 4;
  }
  BuildPurpose build_purpose = 3;

  // Supported APK densities.
  enum Density {
    DENSITY_UNSPECIFIED = 0;
    MDPI = 1;
    HDPI = 2;
    XHDPI = 3;
    XXHDPI = 4;
    ALLDPI = 5;
  }
  Density density = 4;
}

enum AndroidPackage {
  ANDROID_PACKAGE_UNSPECIFIED = 0;
  GMS_CORE = 1;
}

// Next Tag: 8
message CIPDPackage {
  // Required. CIPD package name.
  string name = 1;

  // Required. CIPD package version.
  // Can be defined by ref, tag or specific instance Id.
  oneof version_oneof {
    string ref = 2;
    string tag = 3;
    string instance_id = 4;
  }

  // CIPD server URL to fetch this package from.
  // chrome-infra-packages.appspot.com is used by default.
  string service_url = 5;

  // Required. Android package type.
  AndroidPackage android_package = 6;

  // APK details (arch, build type, screen density)
  ApkDetails apk_details = 7;
}


// Next Tag: 2
message AndroidProvisionMetadata {
  // Required. A list of CIPD packages to install.
  repeated CIPDPackage cipd_packages = 1;
}
