// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

import "google/protobuf/wrappers.proto";
import "chromiumos/test/api/dut_attribute.proto";
import "chromiumos/test/api/test_suite.proto";

// CoverageRule specifies a set of tests that must be executed, and criteria for
// the DUTs to execute tests on.
// Next ID: 7
message CoverageRule {
  // Optional human friendly name of the rule, e.g.
  // "kernel:5.4_soc:geminilake_wifi:intel-5600".
  string name = 1;

  // Test suites that must be executed.
  repeated TestSuite test_suites = 2;

  // DutTargets to execute the tests on.
  //   - At least one target must be specified.
  //   - Additional targets will target compound scheduling units (for units
  //     with multiple physical duts)
  repeated DutTarget dut_targets = 4;

  // Whether the rule is considered critical. For example, this value determines
  // whether failures in this rule fail a CQ or postsubmit run. Note that the
  // default is true.
  google.protobuf.BoolValue critical = 5;

  // If true, then run test suites in this rule via CFT workflow.
  bool run_via_cft = 6;

  // Graveyard
  repeated DutCriterion dut_criteria = 3 [deprecated = true];
}
