// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

import "chromiumos/test/api/dut_attribute.proto";
import "chromiumos/test/api/test_suite.proto";

message CoverageRule {
  // Optional human friendly name of the test coverage rule
  // E.g. kernel:5.4_soc:geminilake_wifi:intel-5600
  string name = 1;

  // Test suites that must be executed.
  repeated TestSuite test_suites = 2;

  // Dut criteria that must be met to execute the tests.
  //   - At least one list of criteria must be specified
  //   - Additional criteria lists will target compound scheduling units
  //       (units with multiple physical duts)
  //   - All criteria in each list must be met (logical AND) to match a DUT
  //
  repeated DutTarget dut_targets = 4;

  // Graveyard
  repeated DutCriterion dut_criteria = 3 [deprecated = true];
}
