// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

import "chromiumos/test/api/test_suite.proto";

// CrosTestFinderRequest specifies test suites with or without tags.
message CrosTestFinderRequest {
  // Test suites to run (by tag or explicit list of tests).
  repeated TestSuite test_suites = 1;
}

message CrosTestFinderResponse {
  // Test suites to run (explicit list of tests).
  repeated TestSuite test_suites = 1;
}

