// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

import "chromiumos/test/api/cros_provision_cli.proto";
import "chromiumos/test/lab/api/ip_endpoint.proto";

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

// Wrapper message of one of container-specific templates
message Template {
  oneof container {
    CrosDutTemplate cros_dut = 1;
    CrosProvisionTemplate cros_provision = 2;
    CrosTestTemplate cros_test = 3;
    CrosPublishTemplate cros_publish = 4;
    CrosFirmwareProvisionTemplate cros_fw_provision = 5;
    CacheServerTemplate cache_server = 6;
  }
}

// Plain template to demonstrate the usage of cros-dut container. All fields are
// required.
message CrosDutTemplate {
  // Reserved for network and artifact_dir that have been moved to upper level.
  reserved 1, 2;
  // Cache server address
  chromiumos.test.lab.api.IpEndpoint cache_server = 3;
  // Dut ssh address
  chromiumos.test.lab.api.IpEndpoint dut_address = 4;
}

// Plain template to demonstrate the usage of cros-provision container. All
// fields are required.
message CrosProvisionTemplate {
  // Reserved for network and artifact_dir that have been moved to upper level.
  reserved 1, 2;
  // CrosProvisionRequest payload can have template placeholders, to be populated
  // and write to a json file inside the artifact directory and pass along to
  // cros-provision server. Note that inventory_server is no longer needed
  chromiumos.test.api.CrosProvisionRequest input_request = 3;
}

// Plain template to demonstrate the usage of cros-test container. network and
// artifact_dir in the StartTemplatedContainer message are required.
// artifact_dir: Host directory, two sub-directories will be created and mounted
// into the container. `<artifact_dir>/cros-test/cros-test` for logs and
// `<artifact_dir>/cros-test/results` for result artifacts to be published
message CrosTestTemplate {
  // Reserved for network and artifact_dir that have been moved to upper level.
  reserved 1, 2;
}

// Plain template to demonstrate the usage of cache-server container. All fields are
// required.
message CacheServerTemplate {
}

// Plain template to demonstrate the usage of cros-publish container. publish_type
// is required. publish_src_dir is required for GCS and TKO publish types.
message CrosPublishTemplate {
  enum PublishType {
    PUBLISH_UNSPECIFIED = 0;
    PUBLISH_GCS = 1;
    PUBLISH_TKO = 2;
    PUBLISH_RDB = 3;
  }

  PublishType publish_type = 1;
  // Source directory of artifacts that needs to be published.
  // If provided, will be mounted to "/tmp/<publish_type>-publish-test-artifacts/"
  // (Ex: gcs-publish-test-artifacts). Required for GCS and TKO publish types.
  string publish_src_dir = 2;
}

// Plain template to demonstrate the usage of cros-fw-provision container.
message CrosFirmwareProvisionTemplate {
}
