// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

import "chromiumos/test/api/test_suite.proto";

// CrosTestPlatform2 ...
service CrosTestPlatform2Service {
  rpc RequestResolver(CTPRequest2)
      returns (CTPResponse2);
}

// CTPRequest2 ...
message CTPRequest2 {
  // Likely will need to change to a CTPv1 style defintion of a request.
  repeated TestSuite test_suites = 1;

  repeated Filter karbon_filters = 2;
  repeated Filter koffee_filters = 3;

  string build = 4;
  // Currently filtering will be done on _board_ level.
  // Other variants (model, hwid, etc) to follow.
  // TTCP resitrction will also go in here.
  oneof variant {
  string board = 5;
  }

}

// CTPResponse2...
message CTPResponse2 {
  repeated TestSuite test_suites = 1;
}

message Filter {
  ContainerInfo container = 1;
  // Dependent Containers signal that a container has a need to be networked with
  // another. For example the filter is "container1", but needs to use "container2",
  // as part of its execution.
  repeated ContainerInfo dependent_containers = 2;
}


// ContainerInfo...
message ContainerInfo {
  string service_name = 1;
  string container_path = 2;
}
