// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

import "chromiumos/test/api/provision.proto";
import "chromiumos/test/api/test_suite.proto";
import "chromiumos/test/api/test_case_metadata.proto";
import "chromiumos/build/api/container_metadata.proto";
import "chromiumos/test/lab/api/dut.proto";
import "google/protobuf/any.proto";

// CrosTestPlatform2 ...
service CTPv2Service {
  rpc RequestResolver(CTPv2Request)
      returns (CTPv2Response);
}

// GenericFilter is what all the filters will implement as their RPC.
service GenericFilterService {
  rpc Execute(InternalTestplan)
      returns (InternalTestplan);
}

// CTPv2Request ...
message CTPv2Request {
  SuiteRequest suite_request = 1;
  repeated Targets targets = 2;

  repeated CTPFilter karbon_filters = 3;
  repeated CTPFilter koffee_filters = 4;

  string pool = 5;

  google.protobuf.Any scheduke_metadata = 6;
}

message SuiteRequest {
  oneof suite_request {
    TestSuite test_suite = 1;
    Reserved hierarchical_plan = 2;
  }
}

message KeyValue {
  string key = 1;
  string value = 2;
}

message Targets {
  HWTarget hw_target = 1;
  repeated SWTarget sw_targets = 2;
}

message HWTarget {
  oneof target {
    LegacyHW legacy_hw = 1;
    DDDHW ddd_hw = 2;
  }
}

message SWTarget {
  oneof sw_target {
    LegacySW legacy_sw = 1;
    DDDSW ddd_sw = 2;
  }
}

message LegacySW {
  string build = 1;
  string gcs_path = 2;
  repeated KeyValue key_values = 3;
  string variant = 4;

}

// DDDSW is not yet defined.
message DDDSW {}

message LegacyHW {
  string board = 1;
  string model = 2;
  // In the process of deprecation. Do not set.
  string variant = 3 [deprecated = true];
  MultiDut multi_dut = 4;
}

message DDDHW{}

message Pair {
  string primary = 1;
  string secondary = 2;
}

message MultiDut{
  Pair boards = 1;
  Pair model  = 2;
}



message CTPFilter {
  chromiumos.build.api.ContainerImageInfo container = 1;
  // Dependent Containers signal that a container has a need to be networked with
  // another. For example the filter is "container1", but needs to use "container2",
  // as part of its execution.
  repeated chromiumos.build.api.ContainerImageInfo dependent_containers = 2;
  google.protobuf.Any container_metadata = 3;

}

message Reserved {}

message InternalTestplan {
  repeated CTPTestCase test_cases = 1;
  SuiteInfo suite_info = 2;
}


// Information to be populated by the filters.
message CTPTestCase {
  string name = 1;
  TestCaseMetadata metadata = 2;

  // HWRequirements are an AND field
  repeated HWRequirements hw_requirements = 3;

  // SWRequirement impl is still tbd.
  repeated SWRequirements sw_requirements = 4;
}

message SuiteInfo {
  SuiteMetadata suite_metadata = 1;
  SuiteRequest suite_request = 2;
}

// Everything by CTPv2, less provision_info.
message SuiteMetadata {
  repeated TargetRequirements target_requirements = 1;
  repeated string channels = 2;
  string pool = 3;
}

message TargetRequirements {
  HWRequirements hw_requirements = 1;
  // One HW, can have multiple SW configs., eg Cros + Lacros + FW + Kernel.
  repeated LegacySW sw_requirements = 2;
}

message HWRequirements {
  repeated SwarmingDefinition hw_definition = 1;
  enum State {
    REQUIRED = 0;
    OPTIONAL = 1;
    PREFERRED = 2;
    BANNED = 3;
    ONEOF = 4;
  }
 State state = 6;
}

message SWRequirements{}
message ProvisionInfo {
  // Should this be a generic string? Then we don't have to touch proto when new provision comes.
  enum Type {
   CROS = 0;
   ANDROID = 1;
   ROFW = 2;
  }
  InstallRequest install_request = 1;
  string identifier = 2;
  Type type = 3;

}

message SwarmingDefinition {
 // This is effectively the UFS proto. This will be the universal language spoken by all filters.
  chromiumos.test.lab.api.Dut dut_info = 1;
  repeated ProvisionInfo provision_info = 2;
  repeated string swarming_labels = 3;
};

// CTPv2Response...
message CTPv2Response {
  repeated CrosTestRunnerRequest test_requests = 1;
}

message CrosTestRunnerRequest {}