// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

import "chromiumos/longrunning/operations.proto";
import "chromiumos/test/api/test_case_result.proto";
import "chromiumos/test/api/test_suite.proto";

// Stable (build-agnostic) testing interface for executing tests and
// extracting results.
service ExecutionService {
  // RunTests runs the requested tests.
  rpc RunTests(RunTestsRequest) returns (longrunning.Operation) {
    option (longrunning.operation_info) = {
      response_type: "RunTestsResponse",
      metadata_type: "RunTestsMetadata"
    };
  }
}

// For RunTests, clients can specify both lists of suites and test cases.
// Both will be run as part of a single request.
message RunTestsRequest {
  // Test suites to run (by tag or explicit list of tests)
  repeated TestSuite test_suites = 1;

  reserved 2;
}

message RunTestsResponse {
  repeated TestCaseResult test_case_results = 1;
}

message RunTestsMetadata {}

