// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

import "chromiumos/test/api/coverage_rule.proto";
import "chromiumos/test/api/provision_state.proto";

// A unit is the fundamental building block of a test plan.  It specifies
// a coverage rule (a set of tests to execute, and dut attributes required to
// execute them), and a provisioning state for the device.
//
// The scheduling backend MAY split a unit into multiple units to actually
// execute, but it can be logically considered a single unit of execution.
message HWTestUnit {
    CoverageRule    coverage_rule    = 1; // Tests to run and required dut attributes
    ProvisionConfig provision_config = 2; // Provisioning config for the DUT
}

// A hardware test plan is composed of multiple units.
message HWTestPlan {
    // Unique name to identify the test plan, recommend reverse domain name
    // rooted at chromeos:
    //   chromeos.release.wifi....
    message TestPlanId {
        string value = 1;
    }

    TestPlanId id = 1;
    repeated HWTestUnit test_units = 2;
}