// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

import "chromiumos/build/api/firmware_config.proto";
import "chromiumos/longrunning/operations.proto";
import "chromiumos/storage_path.proto";

// Stable (build-agnostic) interface for installing software (provisioning)
// on a Chrome OS device.
service ProvisionService {
  // InstallCros installs a specified version of Chrome OS on the DUT, along
  // with any specified DLCs.
  //
  // If the DUT is already on the specified version of Chrome OS, the OS will
  // not be installed.
  //
  // If the DUT already has the specified list of DLCs, only the missing DLCs
  // will be installed.
  rpc InstallCros(InstallCrosRequest)
      returns (longrunning.Operation) {
    option (longrunning.operation_info) = {
      response_type: "InstallCrosResponse",
      metadata_type: "InstallCrosMetadata"
    };
  }

  // InstallLacros installs a specified version of Lacros on the DUT.
  //
  // If the DUT already has the specified version of Lacros, Lacros will not be
  // installed.
  rpc InstallLacros(InstallLacrosRequest)
      returns (longrunning.Operation) {
    option (longrunning.operation_info) = {
      response_type: "InstallLacrosResponse",
      metadata_type: "InstallLacrosMetadata"
    };
  }

  // InstallAsh installs a specified version of ash-chrome on the DUT.
  //
  // This directly overwrites the version of ash-chrome on the current root
  // disk partition.
  rpc InstallAsh(InstallAshRequest)
      returns (longrunning.Operation) {
    option (longrunning.operation_info) = {
      response_type: "InstallAshResponse",
      metadata_type: "InstallAshMetadata"
    };
  }

  // InstallArc installs a specified version of ARC on the DUT.
  //
  // This directly overwrites the version of ARC on the current root
  // disk partition.
  rpc InstallArc(InstallArcRequest)
      returns (longrunning.Operation) {
    option (longrunning.operation_info) = {
      response_type: "InstallArcResponse",
      metadata_type: "InstallArcMetadata"
    };
  }

  // InstallFirmware installs all of the firmware images specified.
  rpc InstallFirmware(InstallFirmwareRequest)
      returns (longrunning.Operation) {
    option (longrunning.operation_info) = {
      response_type: "InstallFirmwareResponse",
      metadata_type: "InstallFirmwareMetadata"
    };
  }
}

message InstallSuccess {
}

message InstallFailure {
  // When the status code is other than OK, details in Status message should be
  // parsed for ErrorInfo message with the following Reasons as the reason.
  enum Reason {
    // status code: INVALID_ARGUMENT
    REASON_INVALID_REQUEST = 0;
    // status code: FAILED_PRECONDITION
    REASON_DUT_UNREACHABLE_PRE_PROVISION = 1;
    // status code: FAILED_PRECONDITION
    REASON_DOWNLOADING_IMAGE_FAILED = 2;
    // status code: DEADLINE_EXCEEDED
    REASON_PROVISIONING_TIMEDOUT = 3;
    // status code: ABORTED
    REASON_PROVISIONING_FAILED = 4;
    // status code: ABORTED
    REASON_DUT_UNREACHABLE_POST_PROVISION = 5;
  }

  Reason reason = 1;
}

message InstallCrosRequest {
  StoragePath cros_image_path = 1;

  // Reference DLCs developer documentation:
  // https://source.corp.google.com/chromeos_public/src/platform2/dlcservice/docs/developer.md
  message DLCSpec {
    // id is the DLC ID which is a unique identifier.
    // The DLC ID must follow a specific format that can be found in the DLC
    // developer doc below.
    string id = 1;
  }
  // dlc_specs specifies which DLCs to install on the DUT after provisioning.
  repeated DLCSpec dlc_specs = 2;
  // preserve_stateful specifies whether the stateful partition should be preserved during
  // provisioning. If preserve_stateful is not set to true, the stateful partition is
  // block-level wiped and reset during provisioning.
  bool preserve_stateful = 3;
  // Prevents device reboot during system image provisioning.
  bool prevent_reboot = 4;

  // Provides a possible tar file to overwrite current install files
  StoragePath overwrite_payload = 5;
}

message InstallCrosResponse {
  oneof outcome {
    InstallSuccess success = 1;
    InstallFailure failure = 2;
  }
}

message InstallCrosMetadata {
}

message InstallLacrosRequest {
  StoragePath lacros_image_path = 1;
}

message InstallLacrosResponse {
  oneof outcome {
    InstallSuccess success = 1;
    InstallFailure failure = 2;
  }
}

message InstallLacrosMetadata {
}

message InstallAshRequest {
  StoragePath ash_image_path = 1;
}

message InstallAshResponse {
  oneof outcome {
    InstallSuccess success = 1;
    InstallFailure failure = 2;
  }
}

message InstallAshMetadata {
}

message InstallArcRequest {
  StoragePath ash_image_path = 1;
}

message InstallArcResponse {
  oneof outcome {
    InstallSuccess success = 1;
    InstallFailure failure = 2;
  }
}

message InstallArcMetadata {
}

message InstallFirmwareRequest {
  chromiumos.build.api.FirmwareConfig firmware_config = 1;
}

message InstallFirmwareResponse {
  oneof outcome {
    InstallSuccess success = 1;
    InstallFailure failure = 2;
  }
}

message InstallFirmwareMetadata {
}
