// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "chromiumos/storage_path.proto";
import "chromiumos/test/api/test_case.proto";
import "chromiumos/test/api/test_harness.proto";

// Result of a single execution of a given TestCase
message TestCaseResult {
  // Unique ID of test case executed
  TestCase.Id test_case_id = 1;

  // Location of the test result artifacts generated during execution.
  StoragePath result_dir_path = 2;

  oneof verdict {
    // Set if test ran successfully and passed.
    Pass pass = 3;
    // Set if test ran successfully and failed.
    Fail fail = 4;
    // Set if test execution encountered errors (i.e. started/attempted).
    Crash crash = 5;
    // Set if test execution was aborted before finishing either due to system
    // limitation or user requests.
    Abort abort = 6;
    // Set if test was skipped due to dependency requirements.
    Skip skip = 7;
    // Set if test did not run.
    NotRun not_run = 8;
  }

  // Reason associated with status above to provide more information.
  string reason = 9;

  // Test harness information.
  TestHarness test_harness = 10;

  // The time when the test case started to execute.
  google.protobuf.Timestamp start_time = 11;

  // Duration of the test case execution.
  google.protobuf.Duration duration = 12;

  // Bool to show if the test was a retry or not.
  bool retry = 13;

  message Artifacts {
  }

  message Pass {
  }

  message Fail {
  }

  message Crash {
  }

  message Abort {
  }

  message Skip {
  }

  message NotRun {
  }

}
