// Copyright 2021 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.test.api;

option go_package = "go.chromium.org/chromiumos/config/go/test/api";

import "chromiumos/test/api/test_case.proto";
import "chromiumos/test/api/test_harness.proto";

// Defines all metadata about a given test case to support the entire
// test case lifecycle (planning, execution, debugging, triage, reporting, ...).
message TestCaseMetadata {
  api.TestCase test_case = 1;
  TestCaseExec test_case_exec = 2;
  TestCaseInfo test_case_info = 3;
}

// Contains details needed to execute a given test case.
message TestCaseExec {
  TestHarness test_harness = 1;
}

// Contains informational details about a test case which doesn't affect
// scheduling or execution behavior.
message TestCaseInfo {
  // Contacts for ownership / flakiness notification etc.
  repeated Contact owners = 1;
  repeated Requirement requirements = 2;
  BugComponent bug_component = 3;
  Criteria criteria = 4;
  HwAgnostic hw_agnostic = 5;
}

// Contact information of individuals or teams.
message Contact {
  // Can be individual user or group email
  string email = 1;
}

// Requirements satisfied by test case
message Requirement {
  string value = 1;
}

// Bug component for filing bugs against test case
message BugComponent {
  string value = 1;
}

// A brief description of the test case.
message Criteria {
  string value = 1;
}

// Specifies if a test can be run on VM or not.
message HwAgnostic {
  bool value = 1;
}

// A list of TestCaseMetadata for ease of serialization into a file.
message TestCaseMetadataList {
  repeated TestCaseMetadata values = 1;
}
