// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package chromiumos.config.api;

import "src/config/api/component.proto";
import "src/config/api/topology.proto";

option go_package = "go.chromium.org/chromiumos/config/go/api";

// Contains hardware related system features that are tracked by Google to
// differentiate distinct hardware build configurations. Generally these
// hardware-related system features are not easily probe-able at run time.
//
// This SHOULD NOT be used to track second sourced components that are drop in
// replacements.
//
// Note the types here are strings instead of enums. The individual Design
// repos should check that any CL landing has acceptable values for the string.
// Most values are effectively stringly typed enums.
message HardwareTopology {
  // Specify hardware screen topology hardware. This includes differences in
  // size, technology, and touch screen.
  // Example Ids: "NONE" (chomebox), "OLED-15", "TFT-12", "TFT-12-TOUCH"
  Topology screen = 1;

  // Specify functional form factor type of hardware. This includes different
  // functions like clamshell, convertible, tablet, detachable, chromebox
  // Example Ids: "CLAMSHELL", "TABLET", "CONVERTIBLE", "CHROMEBOX"
  Topology form_factor = 2;

  // Specify the audio codec topology.
  // Example Ids: "RT5682"
  Topology audio_codec = 3;

  // Specify the stylus topology. This includes differences in stylus presence,
  // garage type, or technology type.
  // Example Ids: "NONE", "GARAGED-USI", "EXTERNAL-EMR"
  Topology stylus = 4;

  // Specify the internal topology. This includes differences in presence,
  // key layout, or backlight functionality.
  // Example Ids: "NONE", "DEFAULT", "DEFAULT-BL", "NO-PWR-BL"
  Topology keyboard = 5;

  // Specify which thermal toplogy. This includes any differnce that would
  // require new thermal tuning parameters.
  // Example Ids: "DEFAULT",  "LARGE-CHASIS", "LARGE-CHASIS-HIGH-PERF"
  Topology thermal = 6;

  // Specify the camera toplogy.  This includes differences in count,
  // location, camera features, or drivers.
  // Example Ids: "NONE", "2A1B", "1A1B1D-ARC"
  Topology camera = 7;

  // Specify the microphone toplogy. This includes differences in count,
  // location, and drivers.
  // Example Ids: "NONE", "2C", "2C-ARRAY"
  Topology mic = 8;

  // Specify the accelerometer toplogy. This includes differences in count,
  // location, and drivers.
  // Example Ids: "NONE", "1LID1Base", "1LID-LSM-1BASE-BMI"
  Topology accel = 9;

  // Specify the gyroscope toplogy. This includes differences in count,
  // location, and drivers.
  // Example Ids: "NONE", "1LID", "1BASE-L3GD"
  Topology gyro = 10;

  // Specify the magnetometer/eCompass toplogy. This includes differences in
  // count, location, and drivers.
  // Example Ids: "NONE", "1BASE-BMM"
  Topology magnetometer = 11;

  // Specify the fingerprint sensor toplogy. This includes differences in
  // count, location, and drivers.
  // Example Ids: "NONE", "1C-ELAN"
  Topology fingerprint = 12;

  // Specify the proximity sensor toplogy. This includes differences in
  // count, location, and drivers.
  // Example Ids: "NONE", "1B-ELAN"
  Topology proximity_sensor = 13;

  // Specify the daugher board toplogy. Every unique daughter board should have
  // a unique ID based on function
  // Example Ids: "NONE", "1C1A", "HDMI-1A", "LTE"
  Topology daugher_board = 14;

  // Specify the non-volatile storage toplogy. This includes differences in
  // required tuning parameters or drivers.
  // Example Ids: "EMMC", "NVME"
  Topology non_volatile_storage = 15;

  // Specify the ddram toplogy. This includes differences in speed, channel
  // count, size. This does not include different vendors of memory unless
  // special driver consideration is required. Each unique ID value here should
  // map to a specific resistor strappping configuration on the SoC.
  // Example Ids: "DUAL-8GB-2400",
  Topology ddram = 16;
}

// Each Design repo will translate HardwareTopology into
// HardwareFeatures. It is entirely possible for different values of
// a HardwareTopology message to generate identical verions of
// HardwareFeatures. For example, multiple different sensor
// topologies (caused by placement differences) may have the same normalized
// HardwareFeatures. This HardwareFeatures message drives the rest of the
// configuration system
message HardwareFeatures {
  UsbC usb_c = 1;
  message UsbC {
    int32 count = 1;
  }

  UsbA usb_a = 2;
  message UsbA {
    int32 count = 1;
  }

  Lte lte = 3;
  message Lte {
    bool present = 1;
  }

  Hdmi hdmi = 4;
  message Hdmi {
    bool present = 1;
  }

  FirmwareConfiguration fw_config = 5;
  message FirmwareConfiguration {
    int32 value = 1;
  }

  Audio audio = 6;
  message Audio {
    AudioCodec audio_codec = 1;
    enum AudioCodec {
      AUDIO_CODEC_UNKNOWN = 0;  // Also used for non-public audio codecs
      RT5682 = 1;
    }
  }

  Camera camera = 7;
  message Camera {
    bool has_a_panel_camera = 1;  // Front camera
    bool has_b_panel_camera = 2;  // User facing camera
  }

  Accelerometer accelerometer = 8;
  message Accelerometer {
    bool has_lid_accelerometer = 1;
    bool has_base_accelerometer = 2;
  }

  Gyroscope gyroscope = 9;
  message Gyroscope {
    bool has_lid_gryoscope = 1;
    bool has_base_gryoscope = 2;
  }

  Magnetometer magnetometer = 10;
  message Magnetometer {
    bool has_lid_magnetometer = 1;
    bool has_base_magnetometer = 2;
  }

  LighSensor light_sensor = 11;
  message LighSensor {
    bool has_lid_lightsensor = 1;
    bool has_base_lightsensor = 2;
  }

  Screen screen = 12;
  message Screen {
    int32 inch_millis = 1;

    bool supports_touch = 2;
  }

  FormFactor form_factor = 13;
  message FormFactor {
    FormFactor form_factor = 1;
    enum FormFactor {
      FORM_FACTOR_UNKNOWN = 0;
      CLAMSHELL = 1;
      CONVERTIBLE = 2;
      DETACHABLE = 3;
      CHROMEBASE = 4;
      CHROMEBOX = 5;
      CHROMEBIT = 6;
      CHROMESLATE = 7;
    }
  }

  Stylus stylus = 14;
  message Stylus {
    Stylus stylus = 1;
    enum Stylus {
      STYLUS_UNKNOWN = 0;
      NONE = 1;
      INTERNAL = 2;  // Garaged stylus
      EXTERNAL = 3;  // Non-garaged stylus
    }
  }

  Touch touch = 15;
  message Touch {
    bool has_touch = 1;
  }

  Keyboard keyboard = 16;
  message Keyboard {
    bool has_internal_keyboard = 1;
    bool has_backlight = 2;
    bool has_power_button = 3;
  }

  Memory memory = 17;
  message Memory {
    Component.Memory.Class class = 1;
  }
}
