# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//create.star", "create")

def _faft_bios_ro_qual():
    return create.suite(
        suite_id = "faft_bios_ro_qual",
        owners = [
            "chromeos-faft@google.com",
            "jbettis@chromium.org",
        ],
        bug_component = "b:792402",
        criteria = "Qualify the AP firmware for RO+RW release.",
        tests = [
            "firmware_CbfsMcache",
            "firmware_CheckEOPState",
            "firmware_CorruptBothFwSigAB",
            "firmware_CorruptBothFwSigAB.dev",
            "firmware_CorruptBothKernelAB",
            "firmware_CorruptBothMiniosAB",
            "firmware_CorruptFwBodyA",
            "firmware_CorruptFwBodyA.dev",
            "firmware_CorruptFwBodyB",
            "firmware_CorruptFwBodyB.dev",
            "firmware_CorruptFwSigA",
            "firmware_CorruptFwSigA.dev",
            "firmware_CorruptFwSigB",
            "firmware_CorruptFwSigB.dev",
            "firmware_CorruptMinios.minios_a",
            "firmware_CorruptMinios.minios_b",
            "firmware_CorruptRecoveryCache",
            "firmware_CorruptRecoveryCache.dev",
            "firmware_DevMode",
            "firmware_DevScreenTimeout",
            "firmware_FAFTSetup",
            "firmware_FWupdateThenSleep",
            "firmware_FWupdateThenSleep.batteryonly",
            "firmware_FWupdateThenSleep.wp",
            "firmware_FwScreenCloseLid",
            "firmware_FwScreenPressPower",
            "firmware_InvalidUSB",
            "firmware_LegacyRecovery",
            "firmware_MenuPowerOff",
            "firmware_MiniDiag",
            "firmware_MiniosMenu",
            "firmware_MiniosMenu.old",
            "firmware_MiniosPriority.minios_a",
            "firmware_MiniosPriority.minios_b",
            "firmware_RecoveryCacheBootKeys",
            "firmware_RecoveryCacheBootKeys.dev",
            "firmware_RollbackKernel",
            "firmware_RollbackKernel.dev",
            "firmware_SelfSignedBoot",
            "firmware_TPMNotCorruptedDevMode",
            "firmware_TryFwB",
            "firmware_TryFwB.dev",
            "firmware_UpdateFirmwareDataKeyVersion",
            "firmware_UpdateFirmwareVersion",
            "firmware_UpdateKernelDataKeyVersion",
            "firmware_UpdateKernelSubkeyVersion",
            "firmware_UpdaterModes",
            "firmware_UserRequestRecovery",
            "firmware_UserRequestRecovery.dev",
            "firmware_WilcoDiagnosticsMode",
            "firmware_WriteProtect",
            "firmware_WriteProtect.dev",
            "firmware_WriteProtectFunc",
            "platform_ServoPowerStateController.usb",
            "tast.firmware.APBmpblk",
            "tast.firmware.BootMode.dev_cold",
            "tast.firmware.BootMode.dev_to_rec",
            "tast.firmware.BootMode.dev_warm",
            "tast.firmware.BootMode.normal_cold",
            "tast.firmware.BootMode.normal_dev",
            "tast.firmware.BootMode.normal_warm",
            "tast.firmware.BootMode.rec_cold",
            "tast.firmware.BootMode.rec_warm",
            "tast.firmware.CorruptBothSignedAMDFWAB.dev_mode",
            "tast.firmware.CorruptBothSignedAMDFWAB.normal_mode",
            "tast.firmware.CorruptFWBothAB.body_dev",
            "tast.firmware.CorruptFWBothAB.body_normal",
            "tast.firmware.CorruptKernelAB.a",
            "tast.firmware.CorruptKernelAB.a_dev",
            "tast.firmware.CorruptKernelAB.b",
            "tast.firmware.CorruptKernelAB.b_dev",
            "tast.firmware.CorruptSignedAMDFW.dev_mode",
            "tast.firmware.CorruptSignedAMDFW.normal_mode",
            "tast.firmware.DevBootUSB.button",
            "tast.firmware.DevBootUSB.keyboard",
            "tast.firmware.DevBootUSB.late_insert",
            "tast.firmware.DevBootUSB.menu",
            "tast.firmware.DevBootUSBDisallowed",
            "tast.firmware.DevDefaultBoot.menu_internal",
            "tast.firmware.DevDefaultBoot.menu_usb",
            "tast.firmware.DevDefaultBoot.timeout_internal",
            "tast.firmware.DevDefaultBoot.timeout_usb",
            "tast.firmware.DevInsertUSBScreen.back",
            "tast.firmware.DevInsertUSBScreen.insert_usb",
            "tast.firmware.ECPowerG3.power_state",
            "tast.firmware.Eventlog.dev",
            "tast.firmware.Eventlog.normal",
            "tast.firmware.Eventlog.normal_rec",
            "tast.firmware.Eventlog.rammus_dev",
            "tast.firmware.Eventlog.rammus_normal",
            "tast.firmware.Eventlog.rec_normal",
            "tast.firmware.Eventlog.suspend_resume",
            "tast.firmware.Eventlog.watchdog",
            "tast.firmware.FWSysfsVPD",
            "tast.firmware.FWTries.dev",
            "tast.firmware.FWTries.normal",
            "tast.firmware.Fixture.dev_rec",
            "tast.firmware.Fixture.rec",
            "tast.firmware.Fmap.bios",
            "tast.firmware.Fmap.bios_dev",
            "tast.firmware.Fmap.ec",
            "tast.firmware.Fmap.ec_dev",
            "tast.firmware.FwmpDevDisableBoot",
            "tast.firmware.ISH",
            "tast.firmware.LockedME",
            "tast.firmware.MemoryTrainingUI",
            "tast.firmware.RollbackFirmware.dev",
            "tast.firmware.RollbackFirmware.normal",
            "tast.firmware.ServoGBBFlags",
            "tast.firmware.TPMExtend.dev",
            "tast.firmware.TPMExtend.dev_recovery",
            "tast.firmware.TPMExtend.normal",
            "tast.firmware.TPMExtend.recovery",
            "tast.firmware.TPMKernelVersion.dev",
            "tast.firmware.TPMKernelVersion.dev_usb",
            "tast.firmware.TPMKernelVersion.normal",
            "tast.firmware.UpdateKernelVersion",
            "tast.firmware.VerityCorruptRootfs.dev",
            "tast.firmware.VerityCorruptRootfs.normal",
            "tast.firmware.WilcoNormalToDev",
            "tast.firmware.WilcoPowerBehavior",
            "tast.firmware.WilcoPowerBehavior.lid_close_open",
            "tast.firmware.WilcoTPMKeyLadderVerification",
            "tast.firmware.WilcoTPMKeyLadderVerification.verify_recovery_screen",
            "tast.hwsec.TPMContest",
            "tast.video.HWDRMInit",
            "tast.wifi.CheckIntelSARTable",
            "tast.wifi.SetTXPower",
            "tast.wifi.SetTXPower.vpd",
        ],
    )

def _all_suites():
    return [
        _faft_bios_ro_qual(),
    ]

faft_bios_ro_qual = struct(
    all_suites = _all_suites,
)
