# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//create.star", "create")

def _faft_bios_ro_qual():
    return create.suite(
        suite_id = "faft_bios_ro_qual",
        owners = [
            "chromeos-faft@google.com",
            "jbettis@chromium.org",
        ],
        bug_component = "b:792402",
        criteria = "Qualify the AP firmware for RO+RW release.",
        tests = [
            "tast.firmware.APBmpblk",
            "tast.firmware.BootMode.dev_cold",
            "tast.firmware.BootMode.dev_to_rec",
            "tast.firmware.BootMode.dev_warm",
            "tast.firmware.BootMode.normal_cold",
            "tast.firmware.BootMode.normal_dev",
            "tast.firmware.BootMode.normal_warm",
            "tast.firmware.BootMode.rec_cold",
            "tast.firmware.BootMode.rec_warm",
            "tast.firmware.BrokenToDev",
            "tast.firmware.CorruptBothMiniOSAB",
            "tast.firmware.CorruptBothSignedAMDFWAB.dev_mode",
            "tast.firmware.CorruptBothSignedAMDFWAB.normal_mode",
            "tast.firmware.CorruptFW.body_dev",
            "tast.firmware.CorruptFW.body_normal",
            "tast.firmware.CorruptFW.sig_dev",
            "tast.firmware.CorruptFW.sig_normal",
            "tast.firmware.CorruptFWBothAB.body_dev",
            "tast.firmware.CorruptFWBothAB.body_normal",
            "tast.firmware.CorruptFWCBFS.dev_mode_a_depthcharge_file",
            "tast.firmware.CorruptFWCBFS.dev_mode_a_file_attributes",
            "tast.firmware.CorruptFWCBFS.dev_mode_a_file_header",
            "tast.firmware.CorruptFWCBFS.dev_mode_a_file_length",
            "tast.firmware.CorruptFWCBFS.dev_mode_a_file_loaded_in_ramstage",
            "tast.firmware.CorruptFWCBFS.dev_mode_a_file_loaded_in_romstage",
            "tast.firmware.CorruptFWCBFS.dev_mode_b_depthcharge_file",
            "tast.firmware.CorruptFWCBFS.dev_mode_b_file_attributes",
            "tast.firmware.CorruptFWCBFS.dev_mode_b_file_header",
            "tast.firmware.CorruptFWCBFS.dev_mode_b_file_length",
            "tast.firmware.CorruptFWCBFS.dev_mode_b_file_loaded_in_ramstage",
            "tast.firmware.CorruptFWCBFS.dev_mode_b_file_loaded_in_romstage",
            "tast.firmware.CorruptFWCBFS.normal_mode_a_depthcharge_file",
            "tast.firmware.CorruptFWCBFS.normal_mode_a_file_attributes",
            "tast.firmware.CorruptFWCBFS.normal_mode_a_file_header",
            "tast.firmware.CorruptFWCBFS.normal_mode_a_file_length",
            "tast.firmware.CorruptFWCBFS.normal_mode_a_file_loaded_in_ramstage",
            "tast.firmware.CorruptFWCBFS.normal_mode_a_file_loaded_in_romstage",
            "tast.firmware.CorruptFWCBFS.normal_mode_b_depthcharge_file",
            "tast.firmware.CorruptFWCBFS.normal_mode_b_file_attributes",
            "tast.firmware.CorruptFWCBFS.normal_mode_b_file_header",
            "tast.firmware.CorruptFWCBFS.normal_mode_b_file_length",
            "tast.firmware.CorruptFWCBFS.normal_mode_b_file_loaded_in_ramstage",
            "tast.firmware.CorruptFWCBFS.normal_mode_b_file_loaded_in_romstage",
            "tast.firmware.CorruptKernelAB.a",
            "tast.firmware.CorruptKernelAB.a_dev",
            "tast.firmware.CorruptKernelAB.b",
            "tast.firmware.CorruptKernelAB.b_dev",
            "tast.firmware.CorruptSignedAMDFW.dev_mode",
            "tast.firmware.CorruptSignedAMDFW.normal_mode",
            "tast.firmware.DevBootInternal.button",
            "tast.firmware.DevBootInternal.insert_usb_screen",
            "tast.firmware.DevBootInternal.keyboard",
            "tast.firmware.DevBootInternal.keyboard_with_usb",
            "tast.firmware.DevBootInternal.menu",
            "tast.firmware.DevBootInvalidUSB.back",
            "tast.firmware.DevBootInvalidUSB.restore_usb",
            "tast.firmware.DevBootTimeout",
            "tast.firmware.DevBootUSB.button",
            "tast.firmware.DevBootUSB.keyboard",
            "tast.firmware.DevBootUSB.late_insert",
            "tast.firmware.DevBootUSB.menu",
            "tast.firmware.DevBootUSBDisallowed",
            "tast.firmware.DevDefaultBoot.menu_internal",
            "tast.firmware.DevDefaultBoot.menu_usb",
            "tast.firmware.DevDefaultBoot.timeout_internal",
            "tast.firmware.DevDefaultBoot.timeout_usb",
            "tast.firmware.DevInsertUSBScreen.back",
            "tast.firmware.DevInsertUSBScreen.insert_usb",
            "tast.firmware.ECPowerG3.power_state",
            "tast.firmware.Eventlog.dev",
            "tast.firmware.Eventlog.normal",
            "tast.firmware.Eventlog.normal_rec",
            "tast.firmware.Eventlog.rammus_dev",
            "tast.firmware.Eventlog.rammus_normal",
            "tast.firmware.Eventlog.rec_normal",
            "tast.firmware.Eventlog.suspend_resume",
            "tast.firmware.Eventlog.watchdog",
            "tast.firmware.FWScreenCloseLid.broken",
            "tast.firmware.FWScreenCloseLid.dev",
            "tast.firmware.FWScreenCloseLid.to_norm",
            "tast.firmware.FWScreenPressTab.chromebox",
            "tast.firmware.FWScreenPressTab.dev",
            "tast.firmware.FWSysfsVPD",
            "tast.firmware.FWTries.dev",
            "tast.firmware.FWTries.normal",
            "tast.firmware.Fixture.dev_rec",
            "tast.firmware.Fixture.rec",
            "tast.firmware.FlagsPreservation",
            "tast.firmware.Fmap.bios",
            "tast.firmware.Fmap.bios_dev",
            "tast.firmware.Fmap.ec",
            "tast.firmware.Fmap.ec_dev",
            "tast.firmware.FwScreenPowerOff.broken",
            "tast.firmware.FwScreenPowerOff.dev",
            "tast.firmware.FwScreenPowerOff.rec",
            "tast.firmware.FwmpDevDisableBoot",
            "tast.firmware.ISH",
            "tast.firmware.LockedME",
            "tast.firmware.MemoryTrainingUI",
            "tast.firmware.MiniDiag",
            "tast.firmware.RecScreenInvalidUSB",
            "tast.firmware.RecScreenMiniOS.menu",
            "tast.firmware.RecScreenMiniOS.menu_old",
            "tast.firmware.RecScreenMiniOS.priority_minios_a",
            "tast.firmware.RecScreenMiniOS.priority_minios_b",
            "tast.firmware.RecScreenUSBInserted.dev",
            "tast.firmware.RecScreenUSBInserted.normal",
            "tast.firmware.RecToDevFromECRW",
            "tast.firmware.RecToDevUntrusted",
            "tast.firmware.RollbackFirmware.dev",
            "tast.firmware.RollbackFirmware.normal",
            "tast.firmware.ServoGBBFlags",
            "tast.firmware.TPMExtend.dev",
            "tast.firmware.TPMExtend.dev_recovery",
            "tast.firmware.TPMExtend.normal",
            "tast.firmware.TPMExtend.recovery",
            "tast.firmware.TPMKernelVersion.dev",
            "tast.firmware.TPMKernelVersion.dev_usb",
            "tast.firmware.TPMKernelVersion.normal",
            "tast.firmware.TPMNotCorruptedDevMode",
            "tast.firmware.TryFWB.dev_mode",
            "tast.firmware.TryFWB.normal_mode",
            "tast.firmware.UIModeTransition",
            "tast.firmware.USBAnnotations",
            "tast.firmware.UpdateKernelVersion",
            "tast.firmware.UserRequestRecovery.dev",
            "tast.firmware.UserRequestRecovery.normal",
            "tast.firmware.VerityCorruptRootfs.dev",
            "tast.firmware.VerityCorruptRootfs.normal",
            "tast.firmware.WilcoNormalToDev",
            "tast.firmware.WilcoPowerBehavior",
            "tast.firmware.WilcoPowerBehavior.lid_close_open",
            "tast.firmware.WilcoTPMKeyLadderVerification",
            "tast.firmware.WilcoTPMKeyLadderVerification.verify_recovery_screen",
            "tast.hwsec.TPMContest",
            "tast.video.HWDRMInit",
            "tast.wifi.CheckIntelSARTable",
            "tast.wifi.CheckMtkMTCL",
            "tast.wifi.SetTXPower",
            "tast.wifi.SetTXPower.vpd",
            "tauto.firmware_CbfsMcache",
            "tauto.firmware_CheckEOPState",
            "tauto.firmware_CorruptBothKernelAB",
            "tauto.firmware_CorruptMinios.minios_a",
            "tauto.firmware_CorruptMinios.minios_b",
            "tauto.firmware_CorruptRecoveryCache",
            "tauto.firmware_CorruptRecoveryCache.dev",
            "tauto.firmware_DevMode",
            "tauto.firmware_FwScreenPressPower",
            "tauto.firmware_RecoveryCacheBootKeys",
            "tauto.firmware_RecoveryCacheBootKeys.dev",
            "tauto.firmware_RollbackKernel",
            "tauto.firmware_RollbackKernel.dev",
            "tauto.firmware_SelfSignedBoot",
            "tauto.firmware_TPMNotCorruptedDevMode",
            "tauto.firmware_UpdateFirmwareDataKeyVersion",
            "tauto.firmware_UpdateFirmwareVersion",
            "tauto.firmware_UpdateKernelDataKeyVersion",
            "tauto.firmware_UpdateKernelSubkeyVersion",
            "tauto.firmware_UpdaterModes",
            "tauto.firmware_WilcoDiagnosticsMode",
            "tauto.firmware_WriteProtect",
            "tauto.firmware_WriteProtect.dev",
            "tauto.firmware_WriteProtectFunc",
            "tauto.hardware_TPMCheck",
            "tauto.platform_ServoPowerStateController.usb",
            "tauto.power_CPUFreq",
            "tauto.power_CPUIdle",
        ],
    )

def _all_suites():
    return [
        _faft_bios_ro_qual(),
    ]

faft_bios_ro_qual = struct(
    all_suites = _all_suites,
)
